### ISSUE TITLE
Allow whole-target instead of just per-entry-point output

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#1018]
Both Slang and modern HLSL support multiple entry points in a file using the `[shader("...")]` attribute, and several output formats (notably SPIR-V and DXIL) support having multiple shader entry points in a single file.

Right now the Slang API/compiler assumes that binary output is generated per-entry-point. Our command-line parsing logic for `-o` option associates each `-o` with a specific target (usually there is only one target in a command-line compile), but gives an error if there is more than one entry point, claiming it can't tell which `-o` goes with which entry point.

Ideally we should have a notion of output formats that support multiple entry points natively, and allow the API user to request a single binary for an entire target rather than for each entry point. For command-line use, a `-o` option for such a target should be valid even in the presence of multiple entry points, and should indicate that per-target rather than per-entry-point code is desired.

The CPU codegen targets should probably support this multiple-entry-point model, at least for shared libraries.

One gotcha with adding whole-target codegen support is that it would be a semantic change for users of the current DXIL and SPIR-V targets if we start defaulting to generating monolithic binaries instead of per-entry-point. We will need to think about how to roll that out (should the new feature be opt-in?).

**Comment by tfoleyNV** [comment]
Recent work (#1100 and its follow-ups) has re-introduced some basic support for outputting a “container” file that captures the outputs of a compile request. It would be logical to extend that work so that both DXIL and SPIR-V modules are allowed as container formats (albeit limited in the kinds of outputs they can contain).

**Comment by tfoleyNV** [comment]
One roadblock for whole-target outputs is that the current code emit logic (for generating HLSL/GLSL) is geared toward outputting one entry point at a time. For the most part this is inessential and the logic could accept zero or more entry points without major complications.

One place where this *does* matter is whenever HLSL/GLSL emit logic queries the target pipeline stage, since there might not be a single value. One particular example of this is when translating DXR shaders to VKRT, since there are cases where a single DXR function for accessing a built-in input maps go different VKRT functions depending on the stage.

The right fix for that kind of issue is to incorporate pipeline stages into the “profile-based overloading” feature, so we can select between multiple stage-specific variants in the IR rather than at codegen time.

The sticking point then is that we have so far assumed profile-based overloading is purely done at link time, and always yields exactly one version of each caller function. Supporting multiple call sites with different constraints, and then selecting the right caller at each call site would introduce a lot of new complexity.

**Comment by csyonghe** [comment]
Done.
