### ISSUE TITLE
TEST_INPUT is not order independent

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#1036]
With more complex slang shaders it has become more common-place to instead of placing //TEST_INPUT at the top of the test file, but to place them just before their definition. 

It should not matter what order //TEST_INPUT are specified if they use 'name=', style reflection or they specify their binding (as they do typically in the slang tests). But the ordering does matter, as changing the order of the definition can break tests.

To repeat a change of tests/compute/byte-address-buffer.slang
Change to 

```
//TEST_INPUT:ubuffer(data=[0 0 0 0]):dxbinding(1),glbinding(1),out,name=outputBuffer
//TEST_INPUT:ubuffer(data=[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15]):dxbinding(0),glbinding(0),name=inputBuffer
RWByteAddressBuffer inputBuffer;

RWByteAddressBuffer outputBuffer;
```

And all tests fail.

**Comment by tfoleyNV** [comment]
I think the problem here starts in `ShaderRendererUtil::createBindingState`. We currently compute a register range for each `ShaderInputLayoutEntry`, but then we don't actually *use* that register range for anything.

We end up creating the `gfx::DescriptorSetLayout::SlotRangeDesc`s based on the order things are declared in the input file. The `SlotRangeDesc` type doesn't even have a field to use for specifying a `register` or `binding`. Instead, the different `Renderer` implementations currently use an API-specific default rule when expanding a `gfx::DescriptorSetLayout` into what the underlying API needs (e.g., on Vulkan it just assigns sequential `binding`s to everything).

The net effect is that the `dxbinding`s and `glbinding`s are seemingly just a placebo right now, which helps to explain why when I create a new test I never seem to have a bug related to setting them incorrectly.

Thinking in terms of the `gfx` abstraction layer, there are really two ways to proceed.

The first is to add a `baseIndex` field (and probably `space` as well) to `SlotRangeDesc` which will then go on to set the API-specific register/binding index stuff.  The up-side to this approach is that it makes the `Renderer` abstraction more flexible/general, because then there would be nothing that D3D12 or Vulkan can express that you can't fit through the abstraction. The down-side is that those fields would be something client code can't fill in without knowledge of the underlying target API (because the rules for what would be valid depend on the target). That's a non-issue when Slang reflection (or `TEST_INPUT` is providing API-specific information), but makes it harder for just plain C++ code that wants to do graphics stuff independent of the target API.

The second option is to hold firm and say that a `gfx::DescriptorSetLayout` is restricted to working with shaders that adopt its required policy on each API (assign things the next index/register/binding available in sequential order). That is the obvious policy, and it isn't onerous (and of course it matches how Slang operates). The main down-side to this approach would be that we'd be unable to test code that does some really convoluted things with manual parameter layout, and if there are API constructions (e.g., emulated bindless) that require a register/binding assignment policy other than the default one, we'd have to move it under the `gfx` abstraction (but that is arguably the Right Thing since such policies are ultimately API-dependent). The biggest concern might just be that we accidentally make the `gfx` layer too Slang-specific.

I suppose a third option is to present both options: have a simple `DescriptorSetLayout::Desc` that uses the current approach (no need to explicitly identify registers/bindings), plus a `DescExt` or similar that takes the additional data so that we can be future-proof for the cases that would need it. If we decide to have both options, we'd still need to decide which `TEST_INPUT` maps to.

If we go with the first option (adding explicit register/binding indices at the `gfx` layer), then it should be possible to make the `TEST_INPUT` lines order-independent at the cost of suddenly requiring that they actually get all the `dxbinding`s and `glbinding`s correct (where they hadn't been so encumbered before).

On the flip side, if we decide to stick with the status quo at the `gfx` layer, the easiest thing would be to remove support for `dxbinding` and `glbinding` and embrace the order-dependence, at least for now. In most common cases, the Slang rules for automatic assignment of registers/bindings (and the natural inclinations of reasonable programmers laying things out by hand) would mean that the order-dependence isn't an issue for code that places `TEST_INPUT` lines together with the declarations they apply to.

In the long run, if we take this second option, we could add support for specifying a `set(...)` and `range(...)` index for a `TEST_INPUT` line, for cases where we want to manually order things. We could extend that model to say that the input layout parsing starts at set zero and range zero, and auto-increments the range for each `TEST_INPUT`, with manual settings just overriding that carried state. That `enum`-like approach would hopefully make it so that we don't need to specify anything manually in the common case where a `TEST_INPUT` comes right after whatever preceded it.

**Comment by natduca** [comment]
We're doing a bug bankrupcy --- please file a new bug or reopen if you see a specific thing we should do.
