### ISSUE TITLE
Linkage Decoration not on Entry Point at emit point

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#1074]
As part of effort to separate backend such that it only uses IR, it was necessary to make emitting of the entry point not have to use EntryPointLayout and the FuncDecl to get the original name in the source. An initial fix was to use the NameHintDecoration - but the decoration is optional and may be stripped. 

One way to solve the problem would be to use IRLinkageDecoration, and extract the name by demangling the linkage symbol. This works on most tests but was found to break on at least 

`tests/bugs/gh-357.slang`

In the test when IRFunc was emitted it did not have any IRLinkageDecoration. This test has an entry point that is specialized - so perhaps the linkage is not generated or copied when the specialization takes place. 

PR #1073 - works around the problem for now by adding the entry point name as an operand to IREntryPointDecoration such that is always available. 

If we expect all entry points to have linkage then we need to fix such that invariant is true. Once it is true we may want to remove the name from IREntryPointDecoration, and go back to using IRLinkageDecoration.

**Comment by tfoleyNV** [comment]
The current solution of attaching the desired symbol name for output to the `IREntryPointDecoration` is probably sufficient, especially if (as per #1113) we decide to allow some level of application control over the name that gets used when emitting an entry point.

The Right Way to handle this in the long run (which completely ignores the need to preserve our current behavior for existing users) is to always emit entry points using the mangled name of the entry point (including specialization args), and to fix whatever is going on right now that leads to specialized entry points not having a linkage decoration.

(Aside: part of the reason that specialized entry points run into this problem is that they get emitted as an `IRSpecialize` instruction with the linkage decoration, and then specialization creates an `IRFunc` from that. We don't currently have logic to transfer a linkage decoration from an `IRSpecialize` to the thing it expands into, because that case has never come up as significant before now.)

**Comment by csyonghe** [comment]
Fixed.
