### ISSUE TITLE
Implementing tangent space lights

### ISSUE THREAD

**Issue by Dynamitos** [shader-slang/slang#1106]
First of all i would like to thank you for this project, it makes working with shaders so much easier and my shader library so much more comprehensible.

However I would like to ask you how you would go about normal mapping and using tangent space. The solution to multiple lights in the model-viewer example is fine for normal shading, but when going into tangent space, where each polygon has its own coodinate system, you would need to modify the light environment on a per-fragment basis, since transforming them in the vertex shader doesn't work for the global ParameterBlock.

There are of course solutions for that in "normal" HLSL, but I would like to hear your opinion on it, since you are a lot more aware of the possibilities/limitations of slang than me, a passion programmer.

Thank you in advance

**Comment by tfoleyNV** [comment]
You are correct that the example programs like `model-viewer` don't always illustrate best practices for building a complex 3D rendering engine. The assumption is that many people who are considering using Slang will already have a renderer in place, and will be looking for ways to integrate the new language into their existing code. We don't want to imply that Slang can only be used with certain very specific approaches to shading/lighting, so the examples are intentionally simplistic.

On the specific question of the space used for light and BRDF evaluation, the obvious point is that if you want to use tangent space (or half-vector space, or any surface-relative coordinate space) then you will need to transform your lights into this space.

The simplest answer is to go ahead and do this transformation as part of the per-fragment shading logic. This approach wouldn't seem to require any changes to the interface definitions in `model-viewer`. Where the current code for `DirectionalLight` does this:

```hlsl
    float3 illuminate<B:IBRDF>(SurfaceGeometry g, B brdf, float3 wo)
    {
        return intensity * brdf.evaluate(wo, direction, g.normal);
    }
```

a version of `model-viewer` that lights in tangent space could define that `wo` and `g.normal` are now tangent-space vectors instead of world-space, and the code would change to something like:

```hlsl
    float3 illuminate<B:IBRDF>(SurfaceGeometry g, B brdf, float3 wo)
    {
        float3 transformedDirection = g.transformVectorFromWorldToLocal(direction);
        return intensity * brdf.evaluate(wo, transformedDirection, g.normal);
    }
```

Here the `transformVectorFromWorldToLocal()` method would need to be added to the `SurfaceGeometry` type, where it might make use of the tangent frame basis vectors. A similar `transformPointFromWorldToLocal()` function could also be defined.

Transforming lights into tangent/local space inside the fragment shader has the benefit of being a relatively small and local code change. It also doesn't require any difficult code changes to deal with higher-level accelleration structures like tiled/clustered light lists.

The main down-side to transforming lights in the fragment shader is that it costs additional ALU instructions. On most modern desktop GPUs this is likely to be an acceptable cost, but in your question you mention:

> ... transforming them in the vertex shader ...

Using vertex shader logic to transform a light into the right coordinate space is something that might be appropriate on older or less powerful hardware, and when rendering with only a few lights. While I wouldn't recommend this approach for forward-looking workloads, I will note that it *can* be expressed somewhat cleanly with the mechanisms Slang provides.

The key idea is that each light-source type will need some amount of logic to run in the vertex stage to produce its transformed coordinates, as well as some data to store those coordinates as they are passed from vertex to fragment. This can be handled using the feature of "associated types" in Slang.

We can extend the `ILightEnv` interface to define an associated type for vertex-to-fragment data, and a method to produce it:

```hlsl
interface ILightEnv {
    // data for transformed light coordiantes
    associatedtype Transformed;

    // method to produce transformed data in vertex shader
    Transformed getTransformed(PerVertexData v);

    // illuminate method now gets transformed data as input
    float3 illuminate<B:IBRDF>(Transformed t, SurfaceGeometry g, B brdf, float3 wo);
}
```

With this change, every light environment type gets to define two methods: a `getTransformed` method that runs in the vertex stage, and an `illuminate` method that runs in the fragment stage. Each type also gets to define a custom `Transformed` type for the data that passes from one stage to the other.

A simple concrete light type might look like:

```
struct DirectionalLight : ILightEnv {
    float3 direction;

    struct Transformed { float3 transformedDirection; }

    Transformed getTransformed(PerVertexData v) {
        Transformed result = { v.transformVectorFromWorldToLocal(direction) };
        return result;
    }

    float3 illuminate<B:IBRDF>(Transformed t, SurfaceGeometry g, B brdf, float3 wo)
    {
        return intensity * brdf.evaluate(wo, t.direction, g.normal);
    }
}
```

(Writing the revised implementations of all the other `ILightEnv` implementations is left as an exercise for the reader...)

If you follow this approach, then you'd need to modify the `CoarseVertex` type to include a field of type `TLightEnv.Transformed`:

```hlsl
struct CoarseVertex
{
    // ...
    TLightEnv.Transformed transformedLightEnv;
};
```

Then you would also need to modify the vertex entry point to fill in that field, and the fragment entry point to use it.

As already stated above, I would not actually recommend the approach that puts the transformation logic in the vertex shader unless you are planning to only support a small number of lights and will be running on older/slower hardware where this seems necessary (benchmarking to be sure!).

Hopefully this gives you some idea of the options available to you in Slang.

At a high level, I would note that it is often best to approach a task using a "normal" HLSL approach first, and only start applying Slang mechanisms once you have a clear idea of the pain points in the traditional approach. This is akin to how developers who learn about C++ templates are often best advised to only apply them when a non-template-based solution is causing problems.

**Comment by Dynamitos** [comment]
Thank you very much for taking the time for such a detailed answer.

> On most modern desktop GPUs this is likely to be an acceptable cost...

This seems kind of counter intuitive to me. Since the tangent space is different for every polygon, but the same for each fragment of that polygon it seemed to me that a per-fragment matrix multiplication would be a massive use of computation. Since I am a beginner this seemed like a big deal, but of course if it's not, it would make it a lot easier.

**Comment by tfoleyNV** [comment]
In my experience most applications don't actually use per-*primitive* tangent frames.

If you go back to a much earlier era of graphics, people typically faked the appearance of smooth surfaces by storing per-vertex normals and then interpolating those over the face of polygons. Those normals would only rarely agree with the geometric normal of the underlying face, but shading using these "smooth" per-vertex normals would give a better final image.

Rendering with tangent frames in modern games tends to follow a similar model. Usually a tangent frame is stored per-vertex. Since a "smooth" normal is usally stored at vertices anyway, in the simplest case expanding this to a full tangent frame amounts to also storing a single tangent vector on the surface, with the other vector being reconstructed as needed by assuming an orthonormal basis. Sometimes renderers assume a fixed handedness to these frames, and other times they figure out a way to encode an additional bit for left- vs. right-handed frames. It is also possible to store the tangent frame in the form of a unit quaternion, if that is your style.

No matter what, it is typical then to interpolate between these per-vertex tangent frames and then use the resulting "smooth" tangent frames for per-fragment shading even if they don't often agree with the true tangent frame of the underlying polygon. Things like normal maps are often encoded relative to the "smooth" tangent space, and this leads to a smoother image for the normal map that can be filtered with fewer artifacts.

There are a large number of "gotchas" that can come with storing tangent frames on vertices, and a lot of competing ways to compute those per-vertex frames in the first places (the engine runtime and the asset creation pipeline usually need to agree on the method). Some programmers use clever tricks to avoid actually storing tangent vectors as part of their assets, and instead construct an *arbitrary* tangent frame for each fragment at the start of fragment shader execution, using screen-space gradient information (this seemingly limits them to isotropic reflectance functions).

There's a lot of detail to this issue and I'm by no means an expert. This is a case where some web searching and reading could be more helpful than anything I can say.

On this comment:

> it seemed to me that a per-fragment matrix multiplication would be a massive use of computation

there's a potentially important thing to note about modern computer architecture trends, which is that historically, increases in raw compute power have tended to outpace increases in memory bandwidth. As a result, on many modern throughput processors (including GPUs) it can be beneficial to re-compute something (or compute it redundantly on different cores/threads) rather than compute it once and re-use that result through memory. There are a number of cases I've run into in my time working with GPUs where pretending that "compute is free" has been a good idea, and focusing on fetching/communicating as few bytes as possible has been a bigger win.

That is by no means a guarantee for all applications, and you should always rely on careful benchmarking and measurement when you want to achieve best performance.
