### ISSUE TITLE
Improved command-line parsing infrastructure

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#1128]
The way that Slang handles command-line parsing is currently ad hoc. There are some things that would benefit from a more systematic design approach.

It is likely that a good approach to command-line parsing is going to rely on a more data-driven representation of what options the compiler allows, and what operands they allow/expect.

In terms of user-facing improvements, it would be good to use the data-driven representation to automatically generate help/usage information including the available options and, where applicable, the available operands and/or default values.

In the code, the hope would be that a data-driven representation would eliminate a lot of the one-off parsing logic along with string-to-enum conversion and related diagnostic messages.

**Comment by tfoleyNV** [comment]
One major issue with our command-line handling today is that it is highly stateful and order-dependent in cases where there are multiple targets, source files, entry points, etc.

The order-dependence seems necessary when looking at the complexity of specifying:

* Multiple targets, each with a format (e.g., SPIR-V or DXIL) and profile (e.g., `sm_4_0`). There may also be target-specific options related to optimizations or debug info - we currently punt on those and make them global to all targets.

* Multiple translation units. This by itself is easy enough, but it involves a baked in assumption in the command-line parser that each `.hlsl` or `.glsl` file should be its own translation unit (C/C++ style), while all `.slang` files specified on the command line are assumed to be part of a single translation unit (C#/Java/... style).

* Multiple entry points, where each entry point is parented to a single translation unit, and also has to allow specifying the entry point name and stage

* Specialization arguments, where there might be both global and per-entry-point specialization parameters.

* Output files for compiled kernel code, which logically need to be per-entry-point *and* per-target. This is currently restricted so that you can have per-entry-point output files only in the case where a single target is specified.

* There's also a fair bit of "do what I mean" inference logic. The most notable is inferring that if *no* entry point is specified and the source language is HLSL or GLSL, then there must be a single entry point called `main`. There's also similar logic for inferring the stage when taking GLSL input (which is only relevant for pass-through...) so that something like `slangc foo.vert` Just Works and doesn't need any entry point or stage name.

The current logic has to juggle all of these along with some subtle "do what I mean" rules around the ordering constraints:

* If there is only one of a "thing" (only one target, only one entry point, only one translation unit) then options that refer to that thing (either to set a property on it, or to create a "child" thing) can come in any order, since there is no ambiguity

* If there is more than one thing, then options apply to the last one specified, and any options *before* a compatible thing need to be diagnosed as errors.

The thing is, these complicated rules and ordering constraints are primarily just there to support the Slang testing code. I'm not aware of any clients of `slangc` who rely on multiple targets, multiple translation units, or multiple entry points in a single invocation.

One thing I'd like to consider if we do an overhaul of the command-line parsing interface is to explicitly remove support for all these cases that only exist to support testing. Instead, the testing code should be built on top of something that is a more general-purpose data-driven interface to the slang compiler functionality. Some options for what that interface might be:

* We could use a JSON format that represents the "things" the command line works on in a structured hierarchical representation, so that we can easily express multiple targets, entry points, etc. along with all their properties without ambiguity.

* We could expose the Slang API to one or more scripting languages with a set of bindings to the C/C++ API, and then have complex use cases be implemented as scripts that make explicit Slang API calls.

With either of those options, we could in principle embed a multi-line configuration into our test files using the same trickery we do for `//TEST_INPUT:` lines, just with something like `//TEST_SCRIPT:` or similar.

It would be possible for the command-line `slangc` to then take a "complex" configuration as input either via a referenced file, or as a string (albeit an ugly one) on the command line.

My hope is that if we can jetison the complexity of supporting complex test cases from the main command-line parsing interface, then we can get away with much simpler logic and rules for the command line.
