### ISSUE TITLE
Slang compiles a `slang` shader with `texture2D`

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#119]
GLSL style declarations should fail compilation.
Check ParallelReduction.fs.slang

**Comment by tfoleyNV** [comment]
Mystery solved. The following lines appear verbatim in the Slang "standard library":

```
// `typedef`s to help with the fact that HLSL has been sorta-kinda case insensitive at various points
typedef Texture2D texture2D;
```

The HLSL compiler actually accepts `texture2D` to this day, and there are some shaders in the wild (including some from the DX SDK that I pulled as test cases) that use it.

At some point HLSL officially claimed that these type names were case-insensitive, but I don't know of anybody actually making use of that and writing `tExTuRe2d`.

A few ad hoc typedefs to keep a shader here and there happy seems fine. I am *not* going to go and make a habit of it, though.

Note: the `texture2D` typedef isn't quite a stand-in for `Texture2D`, since a typedef (in HLSL/Slang) can't take generic arguments. So there is no way to write `texture2D<uint4>` - you need to use `Texture2D` for that.

I'm not in a hurry to support the "case-insensitive" stuff more fully, so I think I'm going to leave things as they are.
