### ISSUE TITLE
What locations should be computed for GLSL when system values are in use?

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#131]
```C++
struct ShadowPassPSIn
{
    float4 pos : SV_POSITION;
    float2 texC : TexCoord;
    uint rtIndex : SV_RenderTargetArrayIndex;
};
```

In HLSL, `SV_POSITION` consumes an input register, so the location will be 0. In GLSL, it's a global variable and doesn't consume a location. In that case Slang will set `texC` location to 0.

I don't know if that's bug or by design. It's confusing for people who will write raw-API VS/GS. The ShadowPass GS, for example, assumes that texC will be bind location 1.

Is that a Slang issue or a user error?

**Comment by tfoleyNV** [comment]
I can see the confusion here, and I'm trying to figure out if there is anything Slang can/should do.

The basic rule in Slang right now is that I never allocate registers/bindings/locations/etc. to a parameter that doesn't consume them, which seems pretty natural. The `pos` field in your example doesn't consume any varying input/output resources, so I don't allocate any for it.

Allocating of register/binding/location space is always based on the *target* API (Vulkan in this case). We don't currently try to compute layouts based on the source language and then impose them downward. That might change at some point if we, e.g., decide that a `cbuffer` in Slang should always be laid out according to D3D rules, even when targeting Vulkan.

The alternative for this `SV_Position` case would be that when we are processing HLSL-style varying input/output in a shader that will target GLSL/Vulkan, we go ahead and allocate a `location` for the system value, but then don't actually emit anything for it in the output code. There is no particular down-side to this other than it violating the "don't allocate resources to a parameter that doesn't actually consume them" principle. I guess it would make it easier for a shader to run into the implementation limits on maximum number of `location`s, but most shaders are unlikely to hit that (and the API spec might count system inputs/outputs against the totals anyway).

Either option maintains the most important property for varying input/output, which is that if a shader stage declares outputs with certain types in a certain order, and the next stage declares inputs with the same types in the same order (perhaps just a prefix of what the first stage output), and nobody uses explicit locations, then things will match up.

The case where you ran into problems was using explicit locations in one stage, but not the other, and wasn't using the same type for the input/output across the stages, so I feel like it is reasonable to say that such a shader needs to have more intimate knowledge of the Slang rules.

One last parting shot is that my general advice for shader authors (which I would give even in the absence of Slang) is:

- Per-stage input/output should always be declared with *all* ordinary user values first, followed by system values.
- As much as possible, the user should *not* use system values for just passing data between stages (that is, if you declare something as a system value, it should be because it will be directly produced or consumed by the system)

The common HLSL idiom of using an `SV_Position` as a VS output and FS input is super gross because it doesn't actually mean what it looks like it means (the data read by the fragment shader is *not* the data written by the vertex shader).

I'm not inclined to change Slang's rules when targetting GLSL, just because the case where this would bite somebody is such a corner case anyway, and the altered rules that would be needed to "fix" this case would no doubt bite somebody else in another case.

However, this issue has made me realize that Slang currently computes varying input/output locations incorrectly for HLSL. I currently apply the GLSL rules (skip system values when assigning locations) all the time, rather than only doing so for GLSL. That probably requires a fix, but I'm not sure how many users will look at or care about the locations I assign in HLSL mode.

**Comment by tfoleyNV** [comment]
I’m going to close this, since we haven’t run into any user-facing issues around locations for varying input/output on quite some time. What Slang does today seems to work for the 99% case.
