### ISSUE TITLE
Investigate a proper boilerplate code generator

### ISSUE THREAD

**Issue by tangent-vector-personal** [shader-slang/slang#137]
The compiler code currently has two major uses of "code generation" in the sense of "code to generate part of the compiler source code":

- The shader "standard library" is built at runtime out of a combination of static strings and C++ logic to generate repetitious boilerplate (e.g., all the various `Texture*` types and their members)

- Various compiler data structures - most notably the AST nodes themselves - are defined in the various `*-defs.h` files via macros, that then get expanded in many different ways to generate declarations and definitions for processing them (e.g., the entire "visitor" setup")

Both of these work well enough for now, but they aren't easy to understand, and don't produce great error messages when things go wrong.

Now that we can package up releases via CI, it might be okay to accept a bit of extra build complexity by using/building a slightly more "real" metaprogramming tool to generate all this. My ideal would be something like a "template engine" where the files can look mostly like the target language (instead of the current macro mess).

Maybe build something small and simple in Lua?

A key point here is that the deployed "source release" can include the generated code, so that builds for users can stay just as simple as they are today.

**Comment by tfoleyNV** [comment]
There has been work done on this front, but the situation is still very messy. Instead of writing the standard library code as C++ that builds strings of Slang, we now write the code in `*.meta.slang` files that are processed by the tool `slang-generate` to produce `.h` files with... C++ code that builds strings of Slang. Still, this is a reasonable improvement for cases where the stdlib code has large blocks of raw Slang.

The big issue here is that actually parsing all those generated strings is getting to be heavy-weight, and so we will eventually want a solution where the Slang code is generated and compiled offline, and then embedded into the library. Using C++ as the language for the generation part is maybe overkill in this case.

I'm considering switching to Lua as a generator language, simply because we can include the source code under `externals/` and wrap it up in our build without too much fuss, but I wouldn't consider that a slam dunk either.

**Comment by tangent-vector** [comment]
At this point we have many different code synthesis strategies all vying for their place. There is no need to track this as a distinct gap.
Closing.
