### ISSUE TITLE
Generate dynamic dispatch code for generics and existential types

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#1385]
One of the biggest design decision we made when designing the Slang language is to adopt interface-constrained generics instead of something more similar to C++ templates. The argument made back then is that the type-system-aware generics semantics allows the compiler to offer more producitivity benefits, including better support of modular compilation and late-binding the decision to use dynamic dispatch or static specialization when composing the modules.

Back then, Slang was implemented with a priority to address modularity issues in rasteriziation based graphics applications, where developers almost always want specialization over dynamic dispatch. For this reason, generics is carefully designed so that all uses can be translated to specialized code, and is implemented so in the compiler.

With the development of real-time rendering technologies and wider adoption of ray tracing techniques, shaders are becoming much more complex than those in rasterization-only renderers. At the same time, we expect future GPUs to provide more flexible dispatching mechanisms that are more or less equivalent to C function pointers. It is time for Slang to deliver its full potential to shader developers, by supporting both static specialization and dynamic dispatch with the same generics and existential types syntax. This allows the developers to express the modular constructs of their code in one syntax, and use specialized or dynamic code for different scenarios with minimal change of source code.

Here is the roadmap for dynamic dispatch support:

Step 1. Booting up (#1386). We start this adventure by supporting a minimal test case of dynamic dispatch. We will implement CPU code generation for a generic function that calls a static function from a interface. We will add a compiler flag that disables the specialization pass in the backend, and start handling the minimal cases exposed by the simple test case. This includes code-gen for witness tables, `IRSpecializeInst`, and translating generic functions to ordinary functions that takes additional generic arguments as ordinary arguments. Expected time for this step is 1-2 weeks.

Step 2. Support calling non-static functions from an interface. This requires generating code properly for pointers in the IR. Estimated time: 0.5-1 week.

Step 3. Harden the implementation with more general use cases, including objects that transitively implements many interfaces, generic interfaces and interface members, and associatedtypes, etc. Estimated time: 1 week.

Step 4. Support code generation for existential types. This includes handling of all the existential type related instructions: `makeExistential`, `wrapExistential`, `extractExistentialValue`, `extractExistentialType` and `extractExistentialWitnessTable`. Estimated time: 1-2 week.

Step 5. Support CUDA code generation. CUDA code gen should share most logic with cpu code gen. Estimated time: 1-2 weeks.

Step 6. When inheritance is implemented, we need to consider the cases where `struct`s implements `interface`s from inheritance, and make sure code gen works correctly with inheritance. Estimated time: 2 weeks.

Step 7. Design and implement the right syntax or compilation mechanism for specifying the choice of dynamic dispatch vs. static specialization. Estimated time: 1-2 weeks.

The follow-up work for dynamic dispatch code generation is to think about how this affects our modular compilation story: how can we leverage this capabilty to code gen to the bottom as much as possible for each IR module?

**Comment by tfoleyNV** [comment]
That list looks like a good start, and we should probably start splitting those items out into their own issues, and then make the top post on this issue work as a checklist for those sub-issues (there is support for checklists in [GitHub markdown](https://help.github.com/en/github/managing-your-work-on-github/about-task-lists)).

The big work items I don't see listed explicitly here:

* As part of your "step 2" for supporting non-`static` functions on interfaces, we also need to do work to support local variables and function parameters of generic type in the dynamic case. A function parameter of generic type `T` needs to become a `T*`, and a local variable of type `T` needs to be a `T*` initialized with an `alloca()`. (We should confirm what level of support there is for `alloca()` in CUDA; we might need to implement our own stack in the worst case)

* A very large chunk of work arises around supporting generic types (both `struct`s and `interface`s) in the presence of dynamic dispatch. This interacts deeply with things like layout, because the offsets of fields in a `SomeType<T>` may depend on the specific `T`, so that code to access a field may need to dynamically compute the offset of that field. Another large issue is how to create/allocate type metadata (RTTI information) for types that get instantiated dynamically. We also need to have a POR for how to apply specialization to generic witness tables.

I think that we can consider most of the complications around generic types to be out of scope for a first pass at this work, but we probably want to be aware of it as a big-ticket item.
