### ISSUE TITLE
Inheritance for Struct Types

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#1405]
A common request from users is support for inheritance on `struct` types so that they can easily factor out repeated code among a range of types (often these are types that all implement a common `interface`).

An initial stake in the ground would be to support `struct` inheritance with some caveats:

* Inheritance is supported, but there are no `virtual` methods or polymorphic dispatch.

* When passing a `Derived` to a function that takes a `Base` (whether as an `in`, `out`, or `inout`), only the `Base` data gets passed (this is called "object shearing" in the C++ world).

* Only single inheritance will ever be supported for `struct`s (plus multiple inheritance from `interface`s).

**Comment by tfoleyNV** [comment]
Initial steps toward this feature have been made in #1366 and #1403. With the functionality in those changes we should in theory support:

* A `struct` can inherit from zero or one other `struct`, plus zero or more `interface`s

* A `Derived` struct can be passed to any function that expects a `Base` struct

* In a `Derived` struct declares a conformance to an `interface ISomething`, then it can use methods inherited from `Base` to satisfy the requirements of `ISomething`

The main feature that is missing is then:

* We ought to be able to have `Derived` conform to `ISomething` when `Base` conforms to `ISomething`, but currently this scenario leads to internal compiler errors.

**Comment by tfoleyNV** [comment]
The case of a type inheriting an interface conformance is actually a tricky one because of how it interacts with a few advanced features of interfaces.

Suppose we have:

```
interface ISomething { ... }
struct Base : ISomething { ... }
struct Derived : Base { ... }
```

For most kinds of requirements in `ISomething` it is straightforward to synthesize (or re-use) a declaration in `Derived` that implements the requirement using what is already present in `Base`.

For example, if `ISomething` has a method requirement and `Base` implements it:

```
interface ISomething { void doThings(); ... }
struct Base : ISomething { void doThings() { ... } }
```

it is clear that in the worst case we could synthesize a method like:

```
struct Derived { void synthesized_doThings() { this.doThings(); } }
```

and use `synthesized_doThings()` as the witness for the `doThings()` requirement.

Where things get tricky is when interface requirements interact with the type of `this`:

```
interface ISomething
{
    __init(int value); // required initializer
    This addedTo(This other); // returning `This` type
}
```

Now we have the problem that the implementations of those requirements on `Base` will only involve the `Base` type itself:

```
struct Base : ISomething
{
    int state = 0;

   __init(int value) { state = value; }

   This addedTo(This other) { return Base(state + other.state); }
}
```

In this case, we can't trivially re-use those definition in `Base` to synthesize matching declarations in `Derived`:

```
struct Derived
{
    int extra;

    /* synthesized */ __init(int value)
    {
        ((Base) this) = Base(value); // re-use `Base` initializer
        // ... still need to iniitialize `Derived`'s fields
    }

    Derived synthesized_addedTo(Derived other)
    {
        // We can re-use the `Base.addedTo` method
        Base b = ((Base) this).addedTo((Base) other);

        // ... but we can't return the result
        return b;
    }
}
```

From a type-system perspective, there are two important added checks/constraints that we need the front-end to enforce to make this work:

1. Initializers from `interface`s count as "required" initializers, and when a derived type is declared it *must* provide (either explicitly or implicitly) initializers that match/override the required initializers of all its bases

2. When a type may be used as a base type, then `This` within that type needs to be treated as if it is a subtype of the concrete outer type, and not synonymous with it. Any functions that return `This` must be implemented in a way that is polymorphic so that they can return the suitable sub-type.

The combination of these features introduces polymorphism as a *de facto* requirement.

These constraints suggest a simple-sounding rule:

* A `struct Derived` cannot inherit from a `struct Base` if `Base` conforms to any interface `ISomething` that includes initializer requirements or has any requirements that reference the `This` type.

The catch with the simple-sounding rule is that it doesn't account for conformances added to `Base` via `extension`s, which might not have been visible at the time `Derived` has being checked.

One possible way out is to require an explicit marker on `struct` types that can be used as base types (not just for the cross-module case) and then to make it illegal for so-marked types to conform to interfaces with the problematic features.

Alternatively, we might say that an `extension` can't introduce conformances to interfaces with certain kinds of requirements (e.g., required initializers).

Yet another way out would, of course, be to implement the more general case of inheritance, such that for `struct` types that might be inherited from we lower their methods into a form that can be specialized (either using generics or some kind of "existential box" type).

**Comment by natduca** [comment]
Got far enough.
