### ISSUE TITLE
Policy for generated CUDA kernel signatures

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#1424]
Background
========

Our CUDA target is based heavily on the earlier work on a CPU C++ target. One thing that was inherited from the CPU target is the way that shader parameters get packaged up.

If we have input HLSL like the following:

```hlsl
StructuredBuffer<A> gA; // global shader parameters
StructuredBuffer<B> gB;
...
void myKernel(
    uniform StructuredBuffer<X> x, // entry-point uniform parameters
    uniform StructuredBuffer<Y> y,
    uint3 tid: SV_DispatchThreadID)
{ ... }
```

Then we currently generate a CUDA C++ entry point that is something like:

```c++
struct GlobalUniforms {
    StructuredBuffer<A> gA;
    StructuredBuffer<B> gB;
};
struct EntryPointUniforms {
    StructuredBuffer<X> x;
    StructuredBuffer<Y> y;
};

extern "C" __global__ void myKernel(void* g, void* e)
{
    auto globalParams = (GlobalUniforms*) g;
    auto entryPointParams = (EntryPointUniforms*) e;
}
```

For our CPU target this transformation provides an important benefit: all of our generated CPU compute kernels have the exact same signature. This means that a single piece of data-driven code can invoke any Slang-generated compute kernel with any number and type of parameters. Reflection information can be used to allocate and fill in `GlobalUniforms` and `EntryPointUniforms` at runtime, and then the logic for actually kicking off compute can be agnostic to their size and layout.

The main down-sides of this approach aren't very significant for CPU:

* Access to the global and entry-point parameters is indirected through these two pointer parameters (rather than being accessible directly through the parameter list). Indirection isn't as expensive on CPU as on other targets, and in practice we could load the entirety of `EntryPointUniforms` at the start of the entry point to only pay for those loads once.

* It is not possible to directly call a generated CPU compute kernel with the "expected" signature. If somebody wanted to have an `extern` declaration for `myKernel` in their code and invoke it directly, that would be made messier because the function wouldn't have the signature they might expect. On CPU this could easily be mitigate by writing or generating a wrapper function.

Those same limitations are more significant for CUDA, where pointer indirections cost more in general, and there is potentially more desire to call a generated entry point directly (and to avoid the pointer-indirection overhead of emitting a wrapper function).

In contrast to most CPU platforms, CUDA already provides an API that allows a kernel function with any signature to be invoked in a data-driven manner: `cudaLaunchKernel` takes an array of entry-point parameter values to pass through, and can thus be used for entry points with different numbers of parameters while abstracting over the exact ABI used per-parameter.

Proposal
======

At the very least, a compiled CUDA kernel should probably take its `EntryPointUniforms` as a value parameter rather than a GPU device address. That change would remove the need for the user to allocate a GPU buffer to hold the direct entry-point parameters, and would potentially reduce the indirection overhead in generated code.

As a further change, it might be desirable for generated CUDA kernels to take the entry-point parameters as individual kernel function parameters instead of as a bundled `struct`. This change would alter how an application needs to invoke the kernels, and might cause more complexity for applications that prefer the bundled mode, but it would mean that a Slang compute kernel written in a CUDA-like style would translate to the obvious equivalent CUDA kernel.

Finally, along the same lines: if the entry-point function is being compiled in a linked program that doesn't include any global shader parameters, then we can potentially eliminate the `GlobalUniforms` parameter entirely. For applications that *never* use global shader parameters, this would again simplify reasoning about the generated signature, and would lead to fewer surprises. For applications that may use global shader parameters, it could create complexity if some kernels use global parameters and others don't (it might be nice to know if `cudaLaunchKernel` is robust against providing more parameters than a kernel actually declares).

For the running example used above, the proposed new output would either be:

```c++
// struct declarations as before
extern "C" __global__ void myKernel(EntryPointUniforms entryPointParams, GlobalUniforms* globalParams)
{ ... }
```

or:

```c++
// GlobalUniforms declaration as before
extern "C" __global__ void myKernel(
    StructuredBuffer<X> x,
    StructuredBuffer<Y> y,
    GlobalUniforms* globalParams)
{ ... }
```

If the kernel hadn't used global shader parameter declarations, then the `globalParams` parameter on the generated kernel would be removed.

**Comment by csyonghe** [comment]
Removing the indirection seems to right thing to do. Do we plan to also change the C++ entry point signature to match this new format? We can always generate a wrapper that provides the same signature as today and call into the actual entry point to retain the benefits of the current signature.

**Comment by tfoleyNV** [comment]
You are right that it would make some sense to have the CPU C++ path change in the same way. I'm not especially concerned about the performance implications for CPU, but it might be nice if/when anybody wants to call their kernel as an `extern` function from C/C++.

There are a few challenges for CPU C/C++ that don't arise for CUDA, though:

* In theory, we already want multiple entry points to be generated for CPU because you want both a "leaf" entry point that runs one or more thread blocks on the current CPU thread context, and a "full-service" entry point that is intended to run an entire dispatch and "go wide" across cores/threads. The leaf entry point is useful for anybody who wants to implement their own scheduler on top of our kernel code, while the full-service one is useful for anybody who wants an easy path to parallelism on CPU. Adding two entry point signature styles compounds with this choice space.

(Note also that a "full-service" entry point would end up needing to package up the uniform parameters into a `struct` anyway, in order to share that data across threads.)

* CPU entry points already need to contend with having a signature that isn't a good one-to-one match with the Slang original, because we need to figure out where to stuff the "dispatch" parameters that control the number of blocks to invoke in the parameter list. That isn't a strong argument against having a more natural signature, but it is one more bit of policy the user needs to understand to know the generated signature.

The other thing that potentially makes the CPU case a bit different (or maybe this applies to CUDA too...) is that we could choose to only put a single version of functions into our generated source, and then have the other verion(s) be exposed as `inline` wrapper functions that are header-only. In that model, having the only non-`inline` function be the one we can data-drive makes a lot of sense.

All told, I'm leaning toward leaving the CPU codegen alone for this.
