### ISSUE TITLE
Coercion controls

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#1608]
The Slang language like HLSL, has silent coercions between certain built in type combinations.  Such coercions can be the source of bugs and can have significant performance implications. 

On testing on Slang it seems...

* u/int/64/32 <-> float/double
* u/int64/32 <-> u/int64/32
* float16/float64/double <-> float16/float64/double

Which seems to indicate that any float/integral built in type can silently coerce to any other built in type(!)

On DXC we do get some warnings.. (I didn't test this exhaustively)

```
D:\local\Temp\1980f0cd-8f60-495c-8061-54a9d0a38635.hlsl:16:9: warning: conversion from larger type 'uint64_t' to smaller type 'int', possible loss of data [-Wconversion]
    int h = f;
        ^
D:\local\Temp\1980f0cd-8f60-495c-8061-54a9d0a38635.hlsl:18:11: warning: conversion from larger type 'double' to smaller type 'float', possible loss of data [-Wconversion]
    float i = e;
          ^
```

I think it could be argued that Slang *not* have the warnings that DXC has is a bug.

That in the C based languages conversions with same sized integrals but signed/unsigned isn't typically an error. This can lead to some hard to find bugs. 

So in terms of a way forward...

* Slang should give (with a disable options) a warning in the same places DXC (and/or FXC does) 
 * We can't rely on downstream compiler(!)
 * Arguably this should be default behavior
* Should have an option to warn/silent/error for integral sign changes 
* Should have an option to warn/silent/error for floating point coercion's that lose information
* Should have an option to warn/silent/error for float/int and int/float conversions
  * This might be a bit more subtle, as we might want to allow int32 -> double as no loss of information, but might be a perf hit

That coercion to larger types that that can hold without loss/sign issues work as normal (that is silently)...

* float16 -> float -> double 
* int8->int16->int32->int64
* uint8->uint16->uint32->uint64

As hinted at above integral to float conversions are more subtle. Is int -> float to silently coerce ok? It does lose some information (not every int is directly representable as float) but it's never going to inf/nan. That isn't it somewhat expected behavior that some information is lost when working with float? It may not be necessary to answer this other than making our default sensible, and having the option of warning/error on such conversions.   

Where float16->double etc is ok too.

**Comment by tfoleyNV** [comment]
The part of this about emitting warnings is probably relatively easy to add to the current codebase. We already have a core function (`_coerce()`) that handles the details of implicit coercion of a value of one type to another type, and that function returns (via an output parameter) the "cost" of the conversion using the `ConversionCost` enumeration. These costs are what we use to rank different function overloads, when that is required.

The `ConversionCost` enumeration already partitions things so that the "safe" conversions (those guaranteed not to loose information) are ranked as lower cost than those that might lose information. The compiler logic currently only uses the actual values to issue an error when the cost is `>= kConversionCost_Explicit` which represents conversions which should not be performed implicitly. It should be a simple enough matter to pick another point on the `ConversionCost` scale where we start issuing warnings.

Note that the main cases of warnings called out here are already in the enumeration: we have `SignedToUnsignedConversion` to catch casts that preserve all bits but could change sign, `IntegerToFloatConversion` to catch all implicit conversions from integral to floating-point types (currently we don't distinguish cases where the integer's magnitude can be encoded losslessly in the mantissa bits), and `GeneralConversion` which should include all potentially-lossy conversions.

The harder bit of the proposed feature here would giving users fine-grained control over enabling/disabling the individual warnings. Part of the difficulty is that we don't really have a ton of infrastructure in place for enabling/disabling warnings yet, and the other part is that the single ranking of conversion costs we have today would make it a bit tricky to enable/disable the different cases of conversions separately.

A third issue we need to be aware of here is that enabling warnings for conversions like this is likely to produce a lot of "false positive" issues when it is applied to literals. By default, our literals have type `int` or `float`, so that initializing a variable of type `half` with `half h = 0` or `half h =0.0` technically involves an `int->half` or `float->half` conversion, and that might create warnings. My experience is that users would want this feature to not warn on "obviously correct" code involving literals (which is reasonable), which means we may need to greatly improve our handling of literals and constant folding before we can reliably add and enable these warnings.

If we decide to pursue this work and want the fine-grained enable/disable or warnings for specific kinds of conversions, it might make sense to push the details out to attributes used in the stdlib. We could define an attribute `[implicitConversionWarning("...")]` that we add to the functions representing implicit conversions, and then in the logic that introduces function calls to perform implicit conversion we could check if the callee function has an associated warning attribute, and then emit the given warning if it is not disabled. That would allow each conversion to be associated with whatever warning makes sense, independent of its numerical conversion cost.

**Comment by jsmall-nvidia** [comment]
Just a comment to flag that this is still and issue - and int64_t will silently coerce to int.

**Comment by csyonghe** [comment]
Closing this issue now.
We currently do diagnose on lossy conversions, except that we silently allow same-size signed->unsigned or unsigned->signed conversions to not being annoying.
