### ISSUE TITLE
Multiple arguments to compute shader

### ISSUE THREAD

**Issue by Checkmate50** [shader-slang/slang#1639]
The following code causes a DXBC compiler error when compiled with the flag `-target dxbc`:

```
[shader("compute")]
[numthreads(4, 1, 1)]
void computeMain(uniform RWStructuredBuffer<float> ioBuffer, uniform RWStructuredBuffer<float> ioBuffer2, uint3 dispatchThreadID : SV_DispatchThreadID)
{
    uint tid = dispatchThreadID.x;
    ioBuffer[tid] = 0;
    ioBuffer2[tid] = 1;
}
```

Specifically, compiling this code produces the error: `fxc: examples/heterogeneous-hello-world/shader.slang(7,28-55): error X4509: maximum UAV register index exceeded, target has 1 slots, manual bind to slot u1 failed`

The offending line in the generated HLSL code is: `RWStructuredBuffer<float > entryPointParams_ioBuffer2_0 : register(u1);`

Am I misunderstanding how HLSL works?  Is there another argument / parameter I should be setting to use multiple arguments to a shader?

**Comment by tangent-vector** [comment]
This seems like a case where you need to specify a target "profile" that is more capable.

Rather than just a `-target dxbc`, you probaly also need a `-profile sm_5_0` or similar to establish the supported "shader model." The big catch there is that the command-line `slangc` tool has rules for matching a `-profile` option up with the right `-target` option when there are more than one, but I honestly cannot remember what the ordering constraint is. I *think* the rule is that you want to specify a `-target` first, and then any `-profile` or other options specific to that target.

**Comment by Checkmate50** [comment]
Thanks so much, that worked perfectly!  I'll read through the available documentation to try and understand why.  For reference `-target cpp -target dxbc -profile sm_5_0` in that order is what worked for me.
