### ISSUE TITLE
CUDA error messages fail to write

### ISSUE THREAD

**Issue by Checkmate50** [shader-slang/slang#1663]
Messages generated by the CUDA renderer fail to write to standard output.  The writer fails on [line 58](https://github.com/shader-slang/slang/blob/master/tools/gfx/cuda/render-cuda.cpp#L58) with a read access violation (`this was 0x10`).  Calling `StdWriters::initDefaultSingleton()` manually beforehand changes the error message to a different access violation.

Reproducing this error is a bit complicated, since a minimal CUDA example involves many lines of code (and a failing example may be fixed), but an illustration can be viewed by running the cuda-hello-world example on the current version of this experimental [branch](https://github.com/Checkmate50/slang/tree/cuda).

**Comment by tfoleyNV** [comment]
Are you able to debug this issue more and work toward a fix? If so, that is probably the easiest path forward.

If you don't think you have line-of-sight to a fix, then we will need to figure out some way to provide a repro to the other devs. Can you point me at a branch that has your CUDA example, so that I can use it to reproduce the issue?

**Comment by Checkmate50** [comment]
I'm working on debugging this issue, so I think I can push out a fix shortly.  I'll let you know if I get stuck for some reason though; [this branch](https://github.com/Checkmate50/slang/tree/cuda) should allow reproduction of the issue if needed.
