### ISSUE TITLE
Supporting raw type casting for local variables 

### ISSUE THREAD

**Issue by tankiJong** [shader-slang/slang#1689]
It's tedious to do memory aliasing only with `asuint` and `asfloat` and raw bit shift operation.
In fact, people create a lot of packing utility functions to do those kinds of stuff. 

If we can agree on a scope to support raw memory typecasting, it will be great.

I understand that it won't work in all general ways, so instead, I think we should support a smaller scope that behaves as people will expect and report errors for those unsure cases.

Some examples:

Be able to perform cast between types
```
struct A {
uint a = 1;
uint b = 2;
};

struct B {
float a;
}

B b = raw_cast<B>(A()); // b.a == asfloat(1)
A a = raw_cast<A>(B()); // error, memory overload
```

Be able to perform cast with an offset in a local buffer
```
struct A {
uint a;
float b;
};

uint data[6] = {1, 2, 3, 4, 5, 6};

A a = raw_cast<A>(data+2); // a.a == 3, a.b == asfloat(4)
A a = raw_cast<A>(data+5); // error, memory overload
```

**Comment by tfoleyNV** [comment]
I think that the first version of `raw_cast` proposed here would probably be relatively easy to support if we could agree on some initial rules/restrictions:

* The sequence of "leaf" scalar fields/elements in the two types needs to match in terms of size (no casting a structure with two `uint` fields over to a structure with a `double` field for now)
* There are no provisions for alignment or padding affecting the output; this would just be a blind field-for-field operation.
* If the destination type is smaller than the source type, there are no errors/warnings, and it just a prefix of the fields
* If the destination type is *larger* than the source type, then the remaining fields get zero-iniitialized

The second operation is interesting but more challenging. I suppose that if it is expressed as `raw_cast<A>(data, 2)` that might make it easier to support, since it would be a distinct operation. The rules would need to be similar as for the struct-to-struct case, just with array elements treated as the "leaf" fields instead.

For the benefit of anybody just reading this issue now, it is worth noting that, yes, most of what you could so with this feature could be done with a full `union` feature, but supporting unions in a shading language raises a lot of thorny questions about how they interact with stuff like memory layout (e.g., the way that an HLSL `cbuffer` uses different layout than a `StructuredBuffer` means that which fields alias could depend on where a `union` type gets used). This proposed feature could be a reasonable stopgap to support many kinds of code that would otherwise need `union`s without the complexity of full `union` support.

**Comment by tankiJong** [comment]
That is a good start. But the following example is desired:
```
struct A { half a; half b; };
struct B { uint a; };
```
This is one of the common cases where we do packing and unpacking. Another example would be:
```
struct PayloadBuffer {
uint data[4];
};
struct TypedPayload {
float a;
half b;
half c;
float d;
uint g;
};
```

Definitely, padding is a concerning issue but I think it makes more sense to respect the padding? As the intention is raw cast, I want it does behave like memory aliasing instead of a vaguely defined syntax sugar to do the auto mapping between fields.

> If the destination type is larger than the source type, then the remaining fields get zero-iniitialized
I am afraid that I need to insist for reporting errors on such a cast. Correct me if I am wrong, but I think it is UB if you do it in C++ and I think we will more appreciate error instead of zero-initialized, which is nice but happens under the hood and can cause people to step on their own foot.

**Comment by csyonghe** [comment]
We have `reinterpret<T>()` that does exactly this thing now.
