### ISSUE TITLE
slang-repro.cpp:LoadContext is leaking memory

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#1787]
The `m_sourceFileMap`, `m_fileToPathInfoMap` and `m_pathInfoMap` dictionaries are not owning the lifetime of its values (Value types are raw pointers instead of `RefPtr`s), and because of it this class is leaking memory.

Memory leak can be detected by running the `tests/compute/dump-repro.slang` test (need to enable DLL CRT to detect this).

**Comment by jsmall-nvidia** [comment]
There are a few  legitimate problems. The most tricky to fix is that the CacheFileSystem::PathInfo ownership, is based on unique identities, and that the repro system (and to a lesser extent the ISlangFileSystem) for historical reasons treats unique identities as something that applies to 'files'. This is unfortunate because the unique identities can be for files or directories. The serialized repro format doesn't make this distinction - making a straightforward fix not so simple. 

That there are plans to replace repro storage with zip and json manifest. Also fortunately the repro system is not used as part of compilation in general. So seems best to fix as part of that refector.

Also perhaps worth noting that I do not see any memory leaks when running dump-repro.slang. I'm on VS2017.

**Comment by csyonghe** [comment]
I just run it with 2017 projects and can reproduce the leaks. Need to enable dll crt by uncommenting `premake5.lua` line 265.

**Comment by csyonghe** [comment]
Unfortunately I can't just enable dll crt for debug builds because Team City is having issues with static crt builds.
