### ISSUE TITLE
CUDA resource format conversion 

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#1798]
In TextureRW<T> types allow for format conversion between the underlying resources format and the T used within the shader. On DX this is handled transparently. On vulkan/glsl it is necessary to markup the resource with the backing format using `[format("...")]` on the resource. 

CUDA implements the TextureRW types via the CUsurfObject. Unfortunately CUDA does not support any conversions during reading or writing of the backing resource - the resources data must be held in the same format as T.

An immediate problem here is that it is therefore not possible to access some resource formats at all - for example half based ones. This is discussed in #1796.

The desire with this issue is to be able to bring CUDA support in line with VK such that RWTexture resources can have their backing format specified via the `[format("...")]` attribute. If the format and T are different types Slang will introduce code into the CUDA output which will automatically perform the conversions.

Also of note `sust.p`...

https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#surface-instructions-sust

> sust.p performs a formatted store of a vector of 32-bit data values to a surface sample. The source vector elements are interpreted left-to-right as R, G, B, and A surface components. These elements are written to the corresponding surface sample components. Source elements that do not occur in the surface sample are ignored. Surface sample components that do not occur in the source vector will be written with an unpredictable value. The lowest dimension coordinate represents a sample offset rather than a byte offset. 

It may be possible to use inline PTX in generated CUDA (or perhaps in prelude), to use this instruction and use HW to do the conversion.

**Comment by tfoleyNV** [comment]
I wonder if there is any merit in supporting `Texture2D<half4>` and similar as explicit types? I rather dislike having format information that is significant to the allowed operations on a texture being carried in attributes rather than the type itself, just because it raises confusion as soon as those textures are being passed as function parameters:

* Must function parameter declarations also reiterate the attributes? (I would assume so since they affect the code that would be generated for operations on those textures in a subroutine)
* What sort of checking must the front-end perform when a texture-type argument is passed to a function that expects a texture? (We catch you passing a `Texture2D<int>` as a `Texture2D<float>`, so why shouldn't we diagnose passing an `RGBA8_UNORM` texture to a function that expects an `RGBA32_FLOAT` texture?)

An ideal long-term solution in my mind is to think of these types as `Texture2D<Format>` instead of just `Texture2D<T>`, so that the generic parameter represents what the compiler knows of the encoded format of the texture. Conceptually the load/store/sample opeations on a texture would take/return values of type `Format` but certain types that represent formats would be defined so that they don't support any operations except format conversion (e.g., an `RGBA8_UNORM` type would exist, but could only be used by converting to/from `float4`). The front-end would then see code like:

```
Texture2D<RGBA8_UNORM> t;
float4 val = t.Sample(...);
```

and it would see both the texture `Sample` operation (returning `RGBA8_UNORM`) and an (implicit) conversion to `float4`. The back-end would then need to recognize that those two ops are actually both covered by the actual texture-sampling operation and merge them at the IR level.

I don't think we can implement this solution right away (and maybe there are fundamental issues with it that I'm not seeing), so this shouldn't stop us from doing whatever makes sense to support `[format("...")]` as a solution for CUDA code generation.

**Comment by jsmall-nvidia** [comment]
In terms of the idea to have formats instead of the type - I can see the appeal especially in the light of observations elsewhere where format attributes are not propagated in general. 

For Texture2D the fact that it only returns as float or vector<float> types make this somewhat appealing. That said from a type system point of view there is an appeal to having TextureND<floatN> and have functions conform to that. That TextureND<T> could be considered an interface, and that the different conversions are implementations. That using the format means programmer would have to know the mapping (not super hard I spose, but it is implicit) and that our type system would work for those scenarios without types (!)

For RWTexture the situation is not that different as it can convert and there are more types than just floatN. 

Perhaps we can consider the format attribute as being something more akin to semantic sugar for 

```
class FormatTextureND<format> : TextureND<floatM>
{ 
  ///... some impl that does conversion
}
```

Then this allows (for example) to specify in the type system a resource that has a format, or the type it is trafficing in.

**Comment by jsmall-nvidia** [comment]
Format conversion for CUDA is supported. For writing sust.p is used and so whatever that mechanism supports is available. For reading format conversion is only supported in SW for half based types. As previously discussed the RWTexture surface is bound as a Texture, Textures read and sampling mechanisms are available.
