### ISSUE TITLE
Testing: How to build good IR tests?

### ISSUE THREAD

**Issue by tfoleyNV** [shader-slang/slang#185]
For the existing AST-based source-to-source path, our testing strategy has mostly been to confirm that our code produces the exact same (textual) output as `fxc` or `glslang`. In some cases we feed slightly different input to `slangc` than we do to `fxc` or `glslang` either to test that Slang is added annotations it is supposed to, or to confirm that Slang is generating appropriate GLSL.

The challenge that arises once we have the IR in the picture is that this kind of comparison-based testing isn't really viable, since it is *much* harder to guarantee that we will produce identical output to the existing compilers (down to small details of instruction ordering, etc.).

The right testing strategy here is probably two-fold:

1. We should have isolated IR tests where we output Slang IR and compare it to a baseline. These need to be kept narrow, so that we don't have to repeatedly update baselines whenever we change the lowering pass and/or optimizations.

2. We need more end-to-end tests where we generate code and then actually *run* it. The challenge there is that we don't have support for running GPU work on AppVeyor. We might be able to run some tests through "refrast" just to confirm that things work. Another alternative is to have some focused tests where we generate CPU code and/or interpret the IR.

Each of these options requires work. We need to front-load this work before we get too deep into the IR implementation process, or else we are going to have a hard time having any confidence in what we build.

**Comment by tangent-vector** [comment]
On item (2) above, I've confirmed that we can use the Microsoft "Warp" software renderer to run D3D11 tests on AppVeyor, so that will suffice for some end-to-end testing. The `render-test` fixture should probably be expanded to support running compute shaders too, so it is a "one stop shop" for end-to-end tests. The current bytecode VM should then be integrated into that application as an alternative back-end (akin to D3D11 vs. GL).

For cross-compilation to GLSL we probably need to continue to use hand-crafted GLSL for examples of desired output (and then hand-crafted SPIR-V when we can bypass glslang). The main issue there will be if we have to keep reviving the expected output for every little change to the IR or optimizations.

**Comment by tfoleyNV** [comment]
Closing this, since we have resolved the original question. We still need to actually implement IR tests around cross-compilation, but we know how they need to work.
