### ISSUE TITLE
Reflection API question 

### ISSUE THREAD

**Issue by Lumengine** [shader-slang/slang#1912]
Hi,

I'm trying to use the Slang reflection API. I just want to have the layout of SPIRV shader and I was wondering what was the best way to do it ?
For now, I'm doing a loop over 
`		Uint32 parameterCount = layout->getParameterCount(); 
		for (Int64 i = 0; i < layout->getParameterCount(); ++i)` 

and a switch with the parameter category but I have trouble recovering the BindingType of the resource. Am I doing it right or totally in the wrong way ?

Thanks

**Comment by Lumengine** [comment]
And is it possible to have combined image sampler ?

**Comment by tfoleyNV** [comment]
> And is it possible to have combined image sampler ?

Issue #1891 tracks some of the work I did just recently to try to get combined image/sampler types working again. That is a feature that Slang is supposed to support in general, but it hadn't been in active use so we had failed to keep it up-to-date with the separate texture/sampler case. Feel free to comment there if you run into specific things that aren't working.

**Comment by tfoleyNV** [comment]
As for the bigger questions around the reflection API, part of the issue is that the surface area for reflection is very large and the API has evolved over time as we discovered new wrinkles (while still needing to maintain backwards compatibility with old code).

There are broadly two different ways to interact with Slang's reflection information: the hierarchical/recursive way, and a newer "flat" way. I'm going to try to follow up with two posts here to try to describe each of those options.

**Comment by tfoleyNV** [comment]
(Apologies if any of this is redundant given code you've already written. It might still be helpful to anybody reading through issues later on to try to learn things)

In the hierarchical/recursive case (which is the easiest one to get started with) you end up wanting to recurse over the structure of the `slang::VariableLayoutReflection` and `slang::TypeLayoutReflection` values that describe the parameters of the program. You can do something non-recursive, but then your application likely won't be able to handle `struct`s of resources.

So the idea in that case is that you look at the *kind* of a type layout (array, struct, texture, etc.) and then having a recursive case for an array/struct while passing off leaf cases to some other kind of routine.

In order to figure out the correct `set` and `binding` for a parameter, you need to add up the contributions from all the variables the recursive path drilled down through. For a single variable, you can do `varLayout->getOffset(ParameterCategory::DescriptorTableSlot)`. The reason you need to add things up recursively is because of nested `struct`s. The Slang reflection information tries to only hold one copy of layout information for each type, which means that if you have:

```hlsl
struct Stuff
{
    Texture2D t;
    SamplerState s;
}
```

then the offset of `s` is `binding=1` when you look at `Stuff` in isolation, but then if you do:

```hlsl
struct Things
{
    Texture2D a;
    Stuff b;
}
```

then the offset of `b.s` is `binding=2` relative to the start of `Things`. Properly keeping track of the base `set` and `binding` is probably best handled as part of the recursion through shader parameters.

But none of the above was your question: you wanted to know how to get the `BindingType` once you have a leaf resource parameter. The short answer is that you can do something like:

```c++
auto varLayout = ...;
auto typeLayout = varLayout->getTypeLayout();
int bindingRangeCount = typeLayout->getBindingRangeCount();
assert(bindingRangeCount == 1); // should be true for a leaf resource parameter
BindingType bindingType = typeLayout->getBindingRangeType(0);
```

You could make that code more robust by handling cases where `getBindingRangeCount` returns something other than `1`, but that should mostly answer your direct question. So long as your logic is recursively walking the structure of the shader parameters and their types, you should be able to ensure that you only call `getBindingRangeType` on leaf parameters that you already know to be resources.

**Comment by Lumengine** [comment]
First, thanks for the answer! It will help me a lot. I think I implemented quite correctly the first part that you mentionned, keeping up binding / set of the parent. I still have some difficulties to know when to use ->getKind() or parameter category or even to know if I'm in a leaf or not. But I will first read the whole documentation (I only read a part of it for now) before bothering you.
Thanks a lot !

**Comment by Lumengine** [comment]
Ok ! I will try all of that thanks ! 
One more question : I know you support compile time specialization but what about layout(constant_id =0) xxx in SPIRV. Is that possible with slang or not ?

**Comment by tfoleyNV** [comment]
We don't currently support SPIR-V specialization constants as part of layout. I don't think it would be especially difficult to support them in a simple fashion, and we'd definitely accept a PR or work toward that goal.

For our own contributions to Slang, we haven't really felt a desire to support specialization constants because of two reasons:

1. Specialization constants aren't portable. Even if we supported them for SPIR-V output, that wouldn't provide a solution for D3D DXBC/DXIL, CUDA, or OpenGL-compatible GLSL output. We'd rather focus our effort on specialization features that work across all targets.

2. Specialization constants are quite limited in what they can specialize. Basically, specialization constants can include/exclude code via conditional branches, and change the sizes of arrays. That's it. They can't change function signatures, change what fields types have, etc.

The focus of our work in Slang has been on generics and interfaces, which provide us a system for specialization that addresses both of those gaps. While our system of generics isn't feature-complete (and there are some use cases for specialization constants that our generics don't yet cover), they have proven to be quite useful for developers doing development of large cross-API shader libraries.

I'd be happy to discuss this stuff in more detail; perhaps even just getting on a video call.

**Comment by Lumengine** [comment]
Hello again, sorry for the delay, I was on holidays. I understand your point on specialization constants. But I have another "blocking" point, I succeeded to specialize a shader but didn't for a type. For example :
 `interface ITest
{
    float3 test(float3 wo, float3 wi, float3 N);
};`
`
ITest iTest;
`
`struct SimpleTest : ITest
{
    float3 test(float3 wo, float3 wi, float3 N) 
    {
        return wo + wi + N;
    }
};
`
`[shader("fragment")]
float4 fragmentMain()
    : SV_Target
{
   float3 result = iTest.test(float3(0,1,0), float3(1,0,0), float3(3,2,1));
   return float4(result, 1);
}`

I thought I should use specializeType from the session but it seems that the shader-example doesn't break in this function. So I'm a bit loss on this point. I tried to understand the whole example but I rapidly get into your gfx implementation but I just want to know what slang function to use. I hope you will be able to help me. 
Thanks a lot !

**Comment by Lumengine** [comment]
Up ?

**Comment by tfoleyNV** [comment]
Sorry for the slow turnaround on some of this. I have been juggling a few different things related to this project that aren't visible on the public GitHub.

I don't think that you need to use `specializeType()` as part of specializing that shader. To reformat the code example for readability:

```hlsl
interface ITest
{
    float3 test(float3 wo, float3 wi, float3 N);
};

ITest iTest;

struct SimpleTest : ITest
{
    float3 test(float3 wo, float3 wi, float3 N)
    {
        return wo + wi + N;
    }
}

[shader("fragment")]
float4 fragmentMain()
    : SV_Target
{
    float3 result = iTest.test(float3(0,1,0), float3(1,0,0), float3(3,2,1));
    return float4(result, 1);
}
```

In this example, the overall *program* has one potential specialization point - the unknown type of `iTest`. This is reflected in the Slang system's model as an "existential type parameter" of the program. None of the types in the program have specialization parameters themselves, so there are no types that require specialization.

In order to do fine-grained specialization you will probably need to drive the compiler programmatically, and use the `ISession` interface. The basic flow (omitting error checks and lots of details) is:

### Create a Session

```
ISession* session;
globalSession->createSession(sessionDesc, &session);
```

### Load one or more modules through the session

```
// Load Slang code module from `stuff.slang`
IModule* stuffModule;
session->loadModule("stuff", &stuffModule);
```

### Use reflection to look up entry points, types, etc. by name in that module.

```
IEntryPoint* myComputeEntryPoint;
module->findEntryPointByName("myComputeEntryPoint", &myComputeEntryPoint);
```

### "Link" together all the relevant pieces to form a complete program

```
IComponentType* components[] = { stuffModule, myComputeEntryPoint };
IComponentType* linkedProgram;
session->createCompositeComponentType(components, 2, &linkedProgram);
```

### Specialize the program to type parameters; one per "specialization point" in the program

```
IComponentType* specializedProgram;
linkedProgram->specialize(&specializedArgs, specializationArgCount, &specializedProgram);
```

### Use the resulting specialized program

```
ProgramLayout* reflectionLayout = specializedProgram->getLayout();
specializedProgram->getEntryPointCode(0, ...);
```

---

The above might seem like a lot of detail (and indeed there are even more details we can drill into if you have questions). The reason there are so many steps here as opposed to a simple "here's a file, please compile it" model is that there are many choices that a developer can make at various points in this process. The order that you use when you "link" the module and entry point (or multiple entry points, or multiple modules, ...) determines a lot of details about the layout of the final program. Whether you specialize pieces and then link them, or link everything and then specialize can also affect layout. The right policy choices here will depend on the needs of a given application.
