### ISSUE TITLE
Stack overflow bug in type checking when using auto type deduction in a generic method.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#1990]
```
// Stack overflow bug in type checking when using auto type deduction in a generic method.

//TEST(compute):COMPARE_COMPUTE_EX:-slang -compute -dx12 -profile sm_6_0 -use-dxil -output-using-type
//TEST(compute):COMPARE_COMPUTE_EX:-slang -compute -dx11 -profile sm_5_0 -output-using-type
//TEST(compute, vulkan):COMPARE_COMPUTE_EX:-vk -compute  -output-using-type

[anyValueSize(12)]
interface IBSDF
{
    uint getLobes();
}

[anyValueSize(16)]
interface IMaterial
{
    associatedtype BSDF : IBSDF;
    BSDF setupBSDF();
}

struct StandardBSDF : IBSDF
{
    uint getLobes()
    {
        return 0;
    }
}

struct StandardMaterial : IMaterial
{
    typedef StandardBSDF BSDF;
    StandardBSDF setupBSDF() { StandardBSDF g; return g; }
};

//TEST_INPUT:ubuffer(data=[0], stride=4):out,name=gOutputBuffer
RWStructuredBuffer<float> gOutputBuffer;

//TEST_INPUT: type_conformance StandardMaterial:IMaterial = 0

interface IInterface
{
    void randomStuff();
};
struct Impl : IInterface
{
    void randomStuff(){}
};

void test<R : IInterface>(R r, int id)
{
    float result = 0.0;
    // Use of auto type deduction from a generic method leads to stack overflow during
    // type checking for `bsdf.getLobes`.
    let bsdf = createDynamicObject<IMaterial, int>(id, 0).setupBSDF();
    result = bsdf.getLobes();
    gOutputBuffer[0] = float(result);
}

[numthreads(1, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    Impl impl;
    test(impl, dispatchThreadID.x);
}
```

Expected result:
```
type: float
0.000000
```

**Comment by tfoleyNV** [comment]
The one somewhat suspicious bit that I think could be to blame here is that when we create an `ExtractExistentialType`, it ends up holding a member `interfaceDeclRef` that refers to the underlying interface, with a `ThisTypeSubstitution` that ultimately refers back to the `ExtractExistentialType` itself. The structure we create in memory is thus circular, and it is unsurprising that it leads to an infinite recursion when we try to perform subsitution on it.

**Comment by tfoleyNV** [comment]
It seems like we either need to stop the circularity from happening at all, or make sure it doesn't lead to infinite recursion.

On the latter option, we could special-case the substitution logic for `ExtractExistentialType` so that it bypasses the recursion into `interfaceDeclRef`, and instead just re-create the "right" decl-ref on demand there. That seems risky because we'd have to special-case any other paths that recurse over the structure of the type (e.g., even just *dumping* the type for debugging purposes could lead to issues).

(Another similar option would be to make the substitution step maintain a mapping from input values to already-substituted results, so that it can some more general cases of circularity)

My preference is to avoid the circularity, and it seems like the easiest way to do that would be to *not* store this special decl-ref as part of the `ExtractExistentialType`, and instead store enough information that it could be created on-demand in client code that might need it. There don't seem to be too many places that *actually* need the particular form that is being stored, and there isn't anything stopping a client from constructing the reference they want.
