### ISSUE TITLE
Initializers on member variables need better documentation

### ISSUE THREAD

**Issue by jsmall-zzz** [shader-slang/slang#2031]
If one writes

```HLSL
struct SomeStruct
{
   int value = 1;
};

[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
  SomeStruct s;

   int a = s.value;
}
```

This does compile, and looks like `a` will equal 1, but looking at generated hlsl, the =1 part is ignored, and therefore a is undefined.

Using the `__init` method to initialize value does work correctly. Perhaps the = 1 style is not intended to be supported and `__init` used. 

I'm assuming that currently this isn't a feature of the language. That being the case the `int value = 1;` should produce an error.

**Comment by tfoleyNV** [comment]
The situation is more complicated and a bit deeper than it initially appears. The inconsistency in what the implementation currently does is in part based on decisions that have yet to be made on the underlying philosophy of the language around initialization.

The short version of the current situation is, IIRC:

* Default initial values for fields are respected whenever a value is created from an initializer list and an explicit initializer for that field is not provided. Thus `SomeStruct s = {};` would yield to `s.value` being `1`.

* By default, a local variable declared without an initial-value expression does *not* get default-initialized. This is consistent with the precedent of all earlier HLSL language versions. Thus, `SomeStruct s;` leaves `s` as an uninitialized variable. This behavior would be independent of the type, except...

* The `RayQuery<>` type introduced in DXR 1.1 de facto requires that the type semantically have a "default constructor" with the kind of semantics that C++ uses. Slang was hacked to support that feature as a special case when a type has a zero-parameter `__init()`, in order to allow DXR 1.1 shaders to be compiled without modification.

**Comment by jsmall-nvidia** [comment]
Okay - well that makes more sense.

Although it's a rather awkward collection of aspects that would probably be 'surprising' to people new to the language.

The HLSL precedent is perhaps not a significant constraint, since having default member initialization is also not part of HLSL.

**Comment by tfoleyNV** [comment]
Really the design choice comes down to a decision between a few different mental models:

1. Everything is always default-initialized (example precedent: the original version of C#). In some languages, every variable gets default-initialized if the user doesn't initialize it explicitly. This works "fine" in languages that have pervasive null pointers/references, but it isn't clear that this could ever apply to a shading language in the style of HLSL/GLSL/Slang, where types like `Texture2D` do not have a meaningful default/null value.

2. Things are only initialized if it is done explicitly (example precedent: Swift). In some languages, the rules are simple: a variable with an initial-value expression gets initialized, while one without is uninitialized (until assigned to). Furthermore, in most of these languages any access to a variable that *could* (through some control-flow path) be uninitialized when used is an error (not just a warning). This model is internally consistent and 100% compatible with the needs of a shading language, and it is where I had *planned* for us to take Slang over time.

3. Whether or not something is initialized is a complicated property that requires global knowledge of the language and the particular codebase being compiled (example: C++). I will claim without a detailed case that this is an undesirable situation. The rules for what does or does not get initialized (and *how* initialization occurs) are some of the more complicated corners of C++, and the Right Way to declare a simple variable seems to change on a regular basis. Slang users with a C++ background sometimes ask for this, and the `RayQuery<>` mess shows that this model has found its way into HLSL (whether intentionally or by accident).

My primary goal is to not get dragged into (3). I would consider (1) preferable to (3) if we have to get pulled into supporting C++-style "default constructor" nonsense, but we don't have a compelling answer for how opaque/resource types fit into that world.

I would still like to pursue option (2) as our long-term direction, and the main thing we are missing there is the analysis passes that would make use of potentially-uninitialized variables an error. If possible, I would be happy supporting (2) as the official language semantics, but with a carve-out for `RayQuery<>` and any other types that show up in HLSL features we decide to support in Slang. (Yes, I know that amounts to just having (3), but having it only be for compatibility rather than a fundamental feature makes it more palatable)

**Comment by jsmall-nvidia** [comment]
2 seems reasonable. You could also have syntax to disable initialization such as `= _` (can't remember what language had this). Disabling is presumably the more rare scenario.

I did scan the documentation before writing the issue, but didn't see anything that seemed to talk about the current behavior.

**Comment by bmillsNV** [comment]
@ArielG-NV can you ensure  #3738  addressed all issues on this? If so, please close it.

**Comment by ArielG-NV** [comment]
It looks like we need to add to documentation, then the issue can be closed.
I can finish this up.
