### ISSUE TITLE
Compilation id/hash 

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2050]
The [repro feature](https://github.com/shader-slang/slang/blob/master/docs/repro.md) is a useful way to provide everything needed to repeat a compilation. The `-dump-repro-on-error` option provides a slang-repro dump file when a compilation fails. 

One problematic scenario is when compilation crashes. When this happens the code to dump out the repro is never hit and so no repro is produced.

One idea might be to dump all compilations. This could be achieved by first 'compiling' with code gen disabled. Dumping and then compiling again. This wouldn't work if prior to code gen the crash occurred, but in practice this isn't the common scenario. Then the last repro saved is presumably the one that failed. When compilation happens in parallel this complicates things, because the last compilation may not be the one that failed - so it would be necessary to check 'some' of the latest repros.

The idea here is before compiling being able to produce a hash and/or data (like say the equivalent command line) that uniquely identifies the compilation. If the crash occurs whilst the debugger is attached, a developer can look at the callstack and see what the hash is. They can then restart and have a check for the has before compilation. They could then do a 'no code gen' compile dumping the repro - and in doing so only have to deal with the compilation they care about.

You could also imagine using this mechanism outside of the developer environment. That if we can have a mechanism that can make available the hash of a failing compilation, we could have a command line (or other) option to dump the repro based just on the hash. The hash could also be useful for other scenarios - for example identifying something that is slow to compile, or produces warnings etc.

The difficulty here is how to make available to the user the hash of the failed compile. One straight forward way would be to serialize compilation, and just write out the hashes to a file or the console.

So how might an id/hash be produced? We could hash (in effect) the command line equivalent. If we were using the component system, some more thought might be needed to ensure a hash would be same every run. A hash/id in this scenario:

* Can be local to a compilation environment - as it only identifies a compilation on a system
* Doesn't need to include source - such as includes/imports
* Must produce the same hash/id for each run

One significant issue would be compilations that inject code (say into includes/imports - that aren't seen on 'command line'). In that scenario two compilations - based on their command line parameters *could* look the same, even though because of the injection they produce different results, and are different compilations so *should* produce different hash/id.

One way to work around this perhaps would be to push this issue back on the application. That if it is going to inject code, it should produce a hash of all the injected source, and then (for example) define it in a macro that would go on the command line. This implies the injection isn't on demand, and can be known before a compilation.

**Comment by tfoleyNV** [comment]
This sounds really interesting and I do agree that there would be value in the compiler infrastructure being able to produce stable hashes that identify compilation requests.

My naive thought when it comes to the repro system, though, was along the lines of:

* Every compile request gets dumped at multiple steps during its compilation (always to the same file), so any time a failure/crash occurs, the most recently dumped state will be in the file. If we use a zip-based container format and design things carefully there is the possibility of writing to the repro file in an append-only fashion (not re-writing data that was already dumped) to avoid the cost of repeated dumping.

* When a compilation *succeeds*, the compiler would automatically erase the associated repro that was dumped, so that the only repros left on disk would be those that were in flight when the process crashed

Such an approach would seem to remove the need to a hash-based multi-pass approach, but maybe there is something naive in what I've described above.

We certainly want and need to start incorporating hashing into more of the compiler logic, since in the long run for things like shader caching we need a way to identify (1) whether the input arguments/configuration for a compile request match a previous request and (2) whether the current state of all the files touched by that request are exactly the same as they were for that previous request.

Naively, such an approach then uses multiple hashes linked together. The user submits a request for some compilation to occur, and the direct arguments to the request (1) get hashed and looked up in a cache. If there is a cache entry for that hash, it would include a list of all the files touched by that request last time it was performed, and their hashes at the time (2). Only on a match between both the (1) and (2) hashes would the compiled outputs for the cache entry be used.

This seems to be a case where it would help for Slang to enforce a more clear separation between the compilation "request" objects and the compilation "result" objects, with each ideally being more-or-less stateless, and a caching layer to map from one to the other. Right now our "request" objects often internally cache the relevant outputs, and that seems to complicate the logic of computing a good hash for them.

**Comment by natduca** [comment]
We added some caching/hashing. We think some of this might exist. Lets open for what still needs doing, but close this one so what we have is fresh.
