### ISSUE TITLE
How to detect whether a parameter is unused via reflection api?

### ISSUE THREAD

**Issue by WeakKnight** [shader-slang/slang#2093]
```
struct Camera
{
    float3 cameraPos;
    float pad0;
    float4x4 cameraTransform;
};

struct Scene
{
    Camera camera;
    StructuredBuffer<float4> vertexBuffers;
    StructuredBuffer<float4> instanceBuffers;
    StructuredBuffer<float4> useless;

    float scale;
    uint pad0;
    uint pad1;
    uint pad2;

    float4 getMagicNumber()
    {
        return instanceBuffers[0] + vertexBuffers[0] + camera.cameraPos.xyzz;
    }
};

Scene gScene;
Texture2D<float4> avatar;
RWTexture2D<float4> gOutput;

[numthreads(16, 16, 1)]
void main(uint3 dispatchThreadId : SV_DispatchThreadID)
{
    gOutput[dispatchThreadId.xy] = gScene.getMagicNumber() + avatar[dispatchThreadId.xy];
}
```

in _gScene_, the StructuredBuffer _useless_ is unused. I need to know this via reflection api so that I can create a correct binding layout for DirectX12.

**Comment by jsmall-nvidia** [comment]
Sorry for the late reply to this issue.

The first thing to say is that Slangs layout is deterministic and depends (largely) on the ordering of declarations within your source file. Slang will keep the same layout even if a binding is not used - this is a design choice. There is more information about this [here](https://github.com/shader-slang/slang/blob/master/docs/layout.md). 

As it stands today there isn't a way to tell if a binding is used or not. 

The current technical reason relates to how Slang performs layout - this is something that happens on the AST (Abstract Syntax Tree). The AST representation matches fairly closely to the source code. It doesn't take into account any of the nuance of the transformations that are later made for specific targets. So there is no way to ask the AST what binding is used - as that isn't known until it has been converted into target specific IR.

It would "in principal" be possible to take Slang reflection bindings and see if they used once IR was available for a target. For simple scenarios (like `avatar` in your example), this might be relatively straight forward. The use within Scene would be more complicated - because the binding isn't just a global variable, its a field of a type that is a global variable. You could imagine more complex binding scenarios again - such as arrays of structs and so forth. Depending on the transformation/s needed for the target, and how it relates back to the original source it could get quite complex.

It could be argued not knowing which bindings are used might leave some performance on the table - if the application knew which bindings were used it could vary what is set. In practice though in most scenarios this seems to be a false economy - as most things most of the time need to be set, and conditionally handling increases code complexity and has performance implications (such as branch prediction).  

If you have examples where having this information would remain important for your usage, please let us know.

**Comment by WeakKnight** [comment]
Yes, now I let unused variables reside in the binding layout, and the program works well. If unified memory or bindless programming model becomes the new trend, this will no longer be a problem.
