### ISSUE TITLE
Glslang error with unsized array.

### ISSUE THREAD

**Issue by Lumengine** [shader-slang/slang#2110]
Hi,

I'm trying to do something like this
```
struct Scene
{
	StructuredBuffer<float4> transformData; // Contains transform of the whole scene
	StructuredBuffer<GeometryInstanceData> instanceData;

        Texture2D textures[]; // Contains all the textures 2d,

     uint GetColorId(const uint instanceID)
     {
        uint materialId = instanceData[instanceID].materialId;
        return materialData[materialId].colorId;
    }
}
```

It compiles in glsl , but not in spirv as glslang complains about the generated function "GetColorId" which look like this in glsl :
`uint Scene_GetColorId_0(texture2D  _S14[], sampler _S15, uint _S16)`

The error is : 
```

glslang:  Scene.slang(23): error :  '' : array size required
glslang:  Scene.slang(23): error :  '' : compilation terminated
glslang: note : ERROR: 2 compilation errors.  No code generated.
```

Any idea how can I fix that ? Am I doing something wrong ?
Thank you ! 

Best regards,

Baptiste

**Comment by jsmall-nvidia** [comment]
I think the problem here is the use of unsized array (as in `Texture2D textures[];`). That having arrays defined in this style is a desired feature although has some caveats. Here it is defined 'at the end of the struct' which is a prerequisite of of that style, but the output GLSL isn't actually correct. 

For this use case though you can just use an array type. Such as

```HLSL
Texture2DArray textures;
```

This compiles correctly as SPIR-V, and will require the appropriate array style binding.

**Comment by tfoleyNV** [comment]
To follow up on this, it seems that in principle the original code with the unsized array of textures under the `struct` type should work, and the fact that it doesn't is down to compiler/implementation problems.

If the workaround of putting that array at the global scope is acceptable, then we can potentially let this issue sit for a while. If your engine design depends on being able to get this kind of nesting working, please do let us know and we can try to prioritize the necessary fixes.

There are a lot of subtle issues around handling unsized arrays nested inside of types, and while we have a lot of implementation work in place to support it, it turns out that some of our assumptions about how the layout behavior ought to work across different platforms (not just D3D/Vulkan but also CUDA/OptiX and CPU) aren't really tenable.

The feature needs an overhaul to really be usable, but most of our current users have been happy with just using global-scope parameters for their unsized arrays. I believe that is because most users who want unsized arrays like this are using them to implement user-space solutions for "bindless" textures, and as such they really do want true global arrays that all points in the code can access.

**Comment by Lumengine** [comment]
The workaround is ok for me for now. I'll let you know if I'll need it at some point.

Baptiste

**Comment by tangent-vector** [comment]
I created issue #2187 to track the goal of revamping Slang's support for unsized arrays of textures/resources in more contexts. I am going to close out this issue in favor of that one.
