### ISSUE TITLE
run examples/model-viewer report an error!

### ISSUE THREAD

**Issue by qianqians** [shader-slang/slang#2133]
![image](https://user-images.githubusercontent.com/1223332/154409629-6fc0d6f8-c594-4b43-9bd6-b85d9cc5c5ec.png)

**Comment by qianqians** [comment]
I copy cube.mtl cube.obj shaders.slang to bin\windows-x86\debug also report this error

**Comment by jsmall-nvidia** [comment]
Sorry for the delay replying.

On looking at your warning above I notice that you are testing for `x86`. You almost certainly want to use the `x64` option for the processor type. x86 implies 32 bit code and the "old" instruction set. You should only use if you *really* need support on 32 bit x86 based systems, which would be very unusual. 

I did try testing out this example with the same debug-x86 combination you have with Visual Studio 2019 and couldn't repeat the problem.

Could you confirm you still have this problem with the latest version of Slang? If you still have the problem can you provide information about your machine - CPU/Memory/OS/GPU also Version of Visual Studio?

**Comment by qianqians** [comment]
windows 10
i7-9700
32GB
RTX-2060
VS2022

**Comment by qianqians** [comment]
![image](https://user-images.githubusercontent.com/1223332/163542810-42f0e777-5d86-496c-82aa-cfee1ed7f551.png)
use latest code from github master branch SHA-1: ac81614974700806e8257b8483a0ba97b925971a, report this error

**Comment by jsmall-nvidia** [comment]
I've installed visual studio 2022 to try and replicate this issue. The normal Slang Visual Studio project is actually for VS 2019. If I upgrade the projects to VS 2022, it doesn't compile, directly complaining about some variables defined which aren't used. I've fixed those fairly small issues in commit cc9c8f5787d46e8e9609c3110cd8652afd008f76.

The model-viewer sample does work correctly for me.

I'm testing also on windows 10 with VS2022 and RTX-2080.

Since you didn't see the compilation issues perhaps you are actually using the 2019 tool chain, from 2022. I'm going to try that and see what happens.

**Comment by jsmall-nvidia** [comment]
When building model-viewer using VS2019 tooling from VS2022, when I run the sample from within Visual Studio it also works correctly.

If I go the the bin\windows-x64\release directory and try and run the sample directly, it doesn't crash but nothing happens. The problem is that it can't find the model to load. The sample *assumes* the working directory is where the items it needs are. In Visual Studio this is set within the Working Directory on that project.

If you want to run the application *outside* visual studio, it's probably easiest to do so from the `command prompt`. Use `cd` to get into the `examples\model-viewer` directory, and then type `..\..\bin\windows-x64\release\model-viewer`. (assuming you built release).

It would be good to know which version of the windows SDK you are using. You can check this in visual studio in `properties` on the project, and then see what `Platform Toolset` is set to. If it says 'latest' click the box and list the latest version number in that list. And `Platform Toolset` would be good to know too.
