### ISSUE TITLE
CPU Ray Tracing Support

### ISSUE THREAD

**Issue by WeakKnight** [shader-slang/slang#2141]
I use Slang heavily in our in-house Pre-Computed GI Baker. Slang is a powerful and elegant shader solution. The problem is the Ray Tracing part is not cross-platform enough. We need to ship our in-house Baker with our UGC Tools to our community but many of our users do not have a RTX GPU. It would be very very helpful to have a CPU Ray Tracing backend(like Embree + ispc).

Currently for our project, I plan to use macros to abstract Embree api and DXR api and link Slang as C++ when using CPU Ray Tracing functionality.

**Comment by tangent-vector** [comment]
We would welcome work on adding some level of support for ray tracing (whether DXR 1.0 / `TraceRay` style or DXR 1.1 / `TraceRayInline` style) on CPU. We don't currently have anybody working on this topic, but we would be happy to accept PRs in that direction, and to coordinate with any contributor who wants to work on it.

Some things to note:

* The current CPU code generation path from Slang does not produce SIMD kernels. It is likely that a contributor could do work to extend our current CPU C++ code generation strategy to something that could work with ISPC. That isn't likely to be the option we prefer in the long run, but could be useful in the short term.

* If one wanted to add ray-tracing support (at least `TraceRayInline`) to the current CPU code generation path, it would mostly be a matter of adding to the C++ "prelude" definitions for CPU, to add the missing operations/types. One could look at the way that code generation path currently abstracts texture types as a prototype for how to define an interface for acceleration structures that supports tracing rays.

* If CPU support for ray tracing gets added, we would like to eventually connect that to the CPU back-end in the `gfx` library nested under the Slang project, since that is what we use for testing and examples.

If anybody wants to work on this topic, please let us know here on GitHub (or contact me separately), and I can try to provide guidance on how it could best be approached.

**Comment by natduca** [comment]
WE love this idea but as we focus on our top priorities, we have to close thigns that we aren't going to get to in the next few quarters. So closing as not planned for now.
