### ISSUE TITLE
`class` doesn't work as expected

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2206]
In C++, `class` behaves in exactly the same way as struct except member visibility is `private` by default.

In HLSL `class` behaves in exactly the same way as `struct` - there are no visibility modifiers in HLSL.

In Slang `class` can compile but appears to broadly **not work** correctly. This is perhaps because there is an intention that `class` is *not* the same long term within Slang. One difference might be that `struct` indicates a value type, whereas `class` indicates a reference type.

This could be *very* confusing for a user coming from HLSL, trying to port code with `class` and it not working in Slang.

A few non mutually exclusive paths seem plausible:

* Make `class` in slang source not compile, producing an error around it being a reserved keyword
* Make `class` be a `struct` if the the source file is HLSL (for compatibility purposes)
* Make `class` the same as `struct`, and allow the use of another mechanism to indicate reference type (say `ref`)

**Comment by tangent-vector** [comment]
(Do we already have an open issue about `class`?)

There's multiple different design questions overlapping here, which is fine. I'd like to briefly sketch my own vision for where we are going with `class`, which is not the same as any "official" Slang POR:

Slang should use the `struct` and `class` keywords in a way that is consistent with the precedent in C# and Swift. Specifically, the `struct` keyword introduces a user-defined type with by-value semantics for assignment, etc. while the `class` keyword should introduce a user-defined type with *reference* semantics for assignment, etc.

Like Java/C#/Swift/..., the type `X` introduced by `class X { ... }` should be usable directly as a reference type (e.g., `X someVar = ...;`), and should *not* require forming a pointer/reference/whatever type in order to get reference semantics as in C++/Rust (e.g., `X*` in C++, `&X` in Rust).

When generating output source in C++, a variable/field of a `class` type `X` should map to the semantics of something like `RefPtr<X>` in C++. The reference-counting mechanism for `class`es should mostly be invisible to Slang users (no need for them to use `RefPtr`s directly), but will surface in places where we will need language support (cycle-breaking and weak references).

Visibility rules for `class` members will follow the same approach as the rest of the language, which is tentatively expected to be C#-inspired. That means that declarations (including `class` members) are `internal` by default (visible everywhere within the module that declared them, but not outside), but can be manually marked `public` (visible everywhere, including outside the module).

My proposed fix for all of these issues is:

* @csyonghe adds preliminary support for `class`es with the semantics above in his work on improving host CPU output code
* As part of that work, we add some kind of error when attempts are made to emit `class` types for targets that cannot support them with our semantics

In the longer run, there could be cases where we want to support very limited subsets of `class` semantics even in GPU code, in cases where the actual memory-management side of things would be too expensive to implement. I don't think we are at a point where we can/should think about those options right now.

Random notes:

* I doubt there is much HLSL code in the wild using `class`, simply because there is no reason to use it over `struct`

* It is entirely likely that we will get some push-back on making our syntax and semantics for this stuff significantly different from C++. It is possible that overwhelming demand from users could lead us to implement a plan very different from the above. I don't expect it to come to that, though.

**Comment by jsmall-nvidia** [comment]
I seem to remember a previous discussion around `class` but I can't remember if it was an issue or not. I couldn't see a stand alone issue.

My underlying worry here is: 

* Divergence from HLSL
* It could be *very* surprising to a HLSL programmer (probably to a C++programmer, but perhaps less so) 
  * The difference could be silent, and hard to diagnose
* Programmers may apply their own meaning to the differentiation/convention (as is fairly common to do C++)
* HLSL/DXC would seem to be likely to support yet more C++ type usage 

If there was some aspect of our use of `class`, which would mean it could be identified to produce error/warning if the programmer really wanted a struct, then this would perhaps be less worrying.

**Comment by jsmall-nvidia** [comment]
Fixed on #2212
