### ISSUE TITLE
Confusing error message around namespace

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#2209]
Take the example (as used in our test infrastructure)

```HLSL
//TEST:SIMPLE:-profile cs_6_3 -target dxil -entry computeMainn
namespace Zing {} 

RWStructuredBuffer<int> outputBuffer;

[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    int index = (int)dispatchThreadID.x;
    outputBuffer[index] = index;
}
```

NOTE, that the entry point name is incorrect in the command line `computeMainn` when it should actually be `computeMain`.

Slang outputs the error

```
tests/language-feature/modules/import-check/import-check.slang(6): error 38000: no function found matching entry point name 'computeMainn'
namespace Zing {}
^~~~~~~~~
}
```

**Comment by tangent-vector** [comment]
The basic problem here is that the logic we have for outputting the `^~~~~~` lines is not really complete/functional.

IIRC, right now we simply find the token that contains (or starts with) the location of the diagnostic, and then highlight that token. That isn't ideal/correct in general, and in a case like this where the error message just points to the entire file, it results in us pointing at the first (semantically-significant) token in the file. I actually don't know what we do if we have a multiple-file module and need to emit this error.

The right long-term fix here is for the logic that prints the `^~~~` stuff to be more conservative and less heuristic-based about what it displays, and for the rest of the front-end code to be better about tracking meaningful locations (and *ranges* for syntactic constructs).

In principle, a diagnostic message can be emitted with a source *location*, a source *range* or one of each. If there is a location, or if the range fits on a single line, we can print out that appropriate line, with a `^` for the location, and `~~~` for the range. In cases where all we have is a range, and the range spans multiple lines, we should in theory just emit the range of lines (no printing of source text), and as a special case we ought to be able to detect a range that spans an entire file and not print *any* contextual information on lines.

A short-term fix is perhaps to detect when a source location for a diagnostic points to the start of a file and not emit the context information in that case?

Implementing the longer-term fix probably requires that we add some richer source location information to our AST nodes to be able to track everything we'd need for richer context on diagnostics.

**Comment by jsmall-nvidia** [comment]
Right, I think the underlying issue here is nothing to do with namespace. It's just the first loc in the file. This is probably already an issue....

Having a loc which is 'the file' (and distinct from any loc possible from a parse) could suppress output in that scenario. Such 'special' loc could be made by `just` making loc range one larger, and using a value that isn't in parse (first or last).

**Comment by tangent-vector** [comment]
Yeah, having a dedicated representation of a location/range for the entire file (or to represent an "unknown" location in a file) would probably work.

We already carve out chunks of `SourceLoc`s from the `SourceManager` for an entire file in one go, so we could conceivably just allocate one extra loc at that point to represent the file itself. I guess the thing in my mind is that a `SourceRange` that covers the entire file conveys the same basic info.

I think our logic was that we need a way to emit errors related to an entire module / translation unit being compiled, and in cases where that translation unit only has a single source file, it makes sense to refer to that file in error messages so that a user who is batch compiling 100s of shader files will see the error message associated with an "obvious" and reasonable location instead of *no* location.

**Comment by natduca** [comment]
Language ease of use, q3
