### ISSUE TITLE
Generate GLSL bindings for separate texture/sampler objects

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#231]
To support OpenGL applications, Slang needs to have a story for generating GLSL bindings of separate texture / sampler objects.

While it is relatively easier to just add support for combined texture/sampler objects for all targets, it feels limiting since it forces developers who wish to target OpenGL to author shader code using only combined texture/samplers. 

Ideally, I should be able to write the following code:
```
Texture2D tex1;
Texture2D tex2;
SamplerState samplerState;

void func()
{
    vec4 v1 = tex1.Sample(samplerState, uv);
    vec4 v2 = tex2.Sample(samplerState, uv);
}
```

Slang should generate the following GLSL:
```
layout(binding = 0) sampler2D tex1;
layout(binding = 1) sampler2D tex2;
...
```

And provide the following reflection data:
```
tex1: type = texture2D,  binding = 0
tex2: type = texture2D, binding = 1
samplerState: type = sampler, binding = {0, 1} // this sampler is used at texture unit 0 and 1
```

There is one case that we cannot easily handle: when the shader code samples one Texture2D object with two different sampler objects, it actually needs two different sampler2D declarations in GLSL, and need to tell the host to setup two different combined texture/samplers and bind them to the pipeline. I don't see a easy way to do this without adding complexity to the reflection API and the host logic. So it might be helpful for the compiler to just emit error message when this happens.

**Comment by tfoleyNV** [comment]
This feature is going to be messy, because if cross-cuts the phases of compilation as I’ve been thinking of them. In particular, the compiler currently assumes that binding generation and type layout can be done in a modular fashion (no need to know the full call graph), and based only on AST-level information (no need to generate, specialize, and optimize IR). When I think about what “shader components” need, I don’t see a way around these constraints.

My gut instinct is that binding generation for GL should follow the same model, but only use a contrived abstract binding space for separate textures and samplers (unrelated to the real GL binding space). Then kernel codegen for GL would generate both the kernel code as GLSL and also the additional layout information you describe that maps the abstract texture and sampler bindings to the actual GL binding space.

Whenever switching variants/kernels, a GL renderer would need to be prepared to re-bind all of these resources in case the mapping changed (an engine could try to optimize to minimize changes, but Slang wouldn’t do any special work on that front).

This means the existing reflection API wouldn’t need modification, since the extra GL-specific data would be packed in with the kernel code (it could even just be embedded as comment text at the start of the generated GLSL...).

How does this sound? Yong, do you see a way to generate this extra data without it being specific to a kernel variant?

**Comment by csyonghe** [comment]
No, I can't think of way to avoid that either. However, I have never thought about maintaining binding layout consistency when targeting OpenGL. For OpenGL it is really just provide a cross-compilation solution, and not about efficient parameter binding (OpenGL is just not efficient).

**Comment by csyonghe** [comment]
Also it would be convenient to have the reflection API slightly modified to query the "legacy gl binding" as it existed in the old spire codebase. Having the user to parse the comments in the resulting GLSL doesn't seem to be a very friendly interface...

**Comment by tfoleyNV** [comment]
One more note: as described so far, the pass to generate the GL binding map could fail of code uses textures/samplers in certain complex ways (e.g., pair a texture with a sampler selected from an array).

The only robust way I can see around that is to use a notion of rates to enforce that texture-sampler pairing must be `@Uniform` (at least when targeting GL), and to report the error to the user in those terms when they try to make a non-uniform pairing.

Under that model, the GL codegen would need to extract a uniform-rate kernel (“parameter shader”) that takes the separate textures/samplers as input and outputs the paired textures/samplers. This is the same thing that your mapping’s above encode, but with the added ability to deal with uniform indexing into arrays or textures/samplers.

The problem there is that it forces an GL-based engine to be able to execute such “parameter shaders” which is probably more invasive than they’d like.

**Comment by csyonghe** [comment]
I think it is fine to require samplers be deducible at compile time. If the compiler cannot figure that out statically, or finds at least two different Sample() calls that uses conflicting samplers, report an error or warning message. It covers 99% of the cases that people care and does not impose extra complexity to the engine.

**Comment by tfoleyNV** [comment]
Ah, I see. So, if I understand things correctly, what you are proposing is that:

- During ahead-of-time binding generation:
  - All texture-sampler pairs get appropriate bindings slots
  - All separate textures *also* get binding slots from the same register range as the texture-sampler pairs
  - All separate samplers get "fake" binding slots in an imaginary register range for samplers

- During kernel code generation for a specific variant
  - Use the IR to analyze usage of separate textures/samplers and try to determine a unique sampler used by each of the separate textures. Error out if there isn't a unique statically determined sampler for a given texture.
  - Generate a mapping that identifies for each of the texture binding slots which of the fake sampler binding slots it should get paired with (this mapping can include missing entries, since a texture might be unused).

That approach avoids the need to delay binding of textures until after variant selection (textures can be bound at the time you bind a component), but you still need to bind samplers late, and be prepared to switch them when switching variants), so I'm not sure how much it really buys you.

Just to be 100% clear, the scenario I think is challenging here is:

```
interface IUseSamplers { float4 use(Texture2D t, SamplerState s0, SamplerState s1); }
struct A : IUseSamplers { float4 use(Texture2D t, SamplerState s0, SamplerState s1) {
    return t.Sample(s0, 0.0f);
} }
struct B : IUseSamplers { float4 use(Texture2D t, SamplerState s0, SamplerState s1) {
    return t.Sample(s1, 0.0f);
} }

Texture2D t; SamplerState s0; SamplerState s1;
float4 myEntryPoint<X : IUseSamplers>( X x ) {
    return x.use(t, s0, s1);
}
```

In this example it is impossible to statically determine which sampler goes with `t` by just analyzing the code as written; we need to know the concrete specialization that will be used before we can figure out how things pair up.

**Comment by csyonghe** [comment]
For OpenGL I don't think there is an easy solution to generate and use pre-specialization binding info. An OpenGL renderer should always use post-specialization binding info, and Slang should also be able to generate those.

**Comment by tangent-vector** [comment]
Closing. There is very little demand for OpenGL support right now, and even if we decide to revamp it I believe we will do better with the same model we use for CUDA:

* Resource types like `Texture2D` map to a combined texture/sampler type in the output
* Sampler types like `SamplerState` map to an empty type, and consume no space in layout
