### ISSUE TITLE
Wrong type-conversion handling

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#237]
My shader contains this line
`v.normal = normalize(mul((float3x3)gWorldInvTransposeMat, v.normal).xyz);`

It looks like slang is converting the `float3x3` into `ErrorType`. This is the error message I'm getting from dxcompiler:
```Shader:1505:31: error: use of undeclared identifier 'ErrorType'
    v.normal = normalize(mul((ErrorType) gWorldInvTransposeMat, ```

**Comment by tfoleyNV** [comment]
I've investigated the original code that caused the problem, and it turns out that `gWorldInvTransposeMat` is an array, and the above expression is failing to index the array, so that the cast fails. Rewriting code so that there is only a single matrix, or so that the shader indexes the array of matrices works around the problem.

There is still a Slang bug here, though, because Slang should be printing out the original type the user wrote, and not `ErrorType`. I have a minimal repro, and will work on a fix.

**Comment by nbenty** [comment]
I'm not sure how the original code works at all... Shouldn't HLSL require an explicit index?

**Comment by tfoleyNV** [comment]
It seems like it doesn't. This is probably an accidental feature where they wanted to allow casts from arrays to matrices and vice-versa, but maybe let more cases Just Work than intended.

Anyway, the right fix is for Slang to properly pass along the code unmodified when it gets confused (which it does, because I don't intend to support all these more fancy conversion rules...).
