### ISSUE TITLE
Support for buffer_reference in GLSL

### ISSUE THREAD

**Issue by gareth-morgan-autodesk** [shader-slang/slang#2447]
I notice that while you can generate buffers tagged with shaderRecordExt in GLSL (using [[vk::shaderRecord]] annotation) you can't generate types tagged with buffer_reference.

So this:
```
[[vk_shader_record]]
ConstantBuffer<Bloop> gBloop;

```
will generate this GLSL:
```
layout(shaderRecordEXT)
buffer _S1
{
    Bloop_0 _data;
} gBloop_0;

```

But there is no way to generate this GLSL, which makes it very hard to generate any Vulkan raytracing code:
```
layout(buffer_reference, std430, buffer_reference_align=4, scalar) buffer Indices     { uint i[]; };
layout(buffer_reference, std430, buffer_reference_align=4, scalar) buffer Positions   { vec3 v[]; };
layout(buffer_reference, std430, buffer_reference_align=4, scalar) buffer Normals     { vec3 n[]; };
layout(buffer_reference, std430, buffer_reference_align=4, scalar) buffer TexCoords   { vec2 t[]; };
layout(shaderRecordEXT) buffer InstanceData
{
    Indices indices;
    Positions positions;
    Normals normals;
    TexCoords texcoords;
} instance;

```

**Comment by tangent-vector** [comment]
Support for `buffer_reference` would be a nice feature to have.

That said, the way that `buffer_reference` works in GLSL is kind of a semantic nightmare (IMHO), insofar as a normal `buffer` declaration does not define a new type name, but now with a suitable `layout` modifier attached it *becomes* a type name.

A more logical way to support this in Slang would be to have something like a `BufferRef<T>` type, so that your second example might be written as:

```
struct InstanceData
{
    BufferRef<uint[]> indices;
    BufferRef<vec3[]> positions;
    BufferRef<vec3[]> normals;
    BufferRef<vec2[]> texcoords;
}

[[vk_shader_record]]
ConstantBuffer<InstanceData> instance;
```

Ideally the above would map to the same basic GLSL output.

While I'd like to see this feature happen, I don't know of any current Slang contributors who are free to work on it at the moment. We would welcome external contributions toward this goal, though.

**Comment by csyonghe** [comment]
This is currently implemented as `ConstBufferPointer` but the implementation is subject to change.
