### ISSUE TITLE
Is there any intent to support WGSL for WebGPU?

### ISSUE THREAD

**Issue by Atrix256** [shader-slang/slang#2454]
A challenge with WebGPU and WGSL is that if you have several target platforms, you can't cross compile other things as WGSL.
Tint and Naga can take WGSL and make other things out of it, and they seem to have some support for turning other things into WGSL but that isn't their main task so it's disabled by default in tint, and the author of naga mentioned there were complications, so their functionality is questionable.
We could write shaders in WGSL and then go to spirv, hlsl, etc but that is undesirable and feels like the cart leading the horse.
If slang was able to target WGSL, that would be a nice solution, as slang is a far, far better and more familiar language than WGSL and it wouldn't be painful to adopt as the singular shader language in projects.
Thanks for any info you are able to provide!

**Comment by tangent-vector** [comment]
A WGSL back-end would be desirable and should be something Slang can support. The main limitation there is that none of the current Slang contributors have the time/opportunity to work on such a back-end. This is a prime "pull requests welcome" kind of scenario.

My understanding had been that WGSL/tint intended to support bi-directional translation to/from SPIR-V, so the easiest path to supporting WGSL via Slang might look like Slang->SPIR-V->WGSL. However, if the SPIR-V->WGSL path is disabled by default, that might be a sign that the goals for the language have changed since when I last checked in.

**Comment by Atrix256** [comment]
Thanks, that makes sense :)
(and nice to chat again Theresa, hope all is going well! I'm at SEED now btw, having a blast!)
