### ISSUE TITLE
Use of overloaded operator in a generic function yields ambiguity error

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#246]
The following test case failed:
```
//TEST(smoke, compute):COMPARE_COMPUTE:-xslang -use-ir
//TEST_INPUT:ubuffer(data=[0 0 0 0], stride=4):dxbinding(0),glbinding(0),out

RWStructuredBuffer<float> outputBuffer;

__generic<T:__BuiltinArithmeticType>
T test(T v0, T v1)
{
    return v0 + v1;
}

[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    float outVal = test<float>(1.0, 2.0);
	outputBuffer[dispatchThreadID.x] = outVal;
}
```

The compiler is reporting error on the `return v0 + v1;` line, complaining the `operator +` is ambiguous.

**Comment by tfoleyNV** [comment]
Did the compiler report a list of candidate overloads?

I would actually expect that example to fail with a “no applicable overload” error, because the `__Builtin*` interfaces aren’t actually full-featured the way you seem to expect (they aren’t meant for users right now; they just exist to help define some of the builtin functions and types). There is no generic overload `operator+ <T:__BuiltinArithmeticType>` defined.

To make this kind of test work we either need to really flesh out the generics and interfaces in the stdlib, or define your own interfaces and types in the test cases to cover the same behavior.

Does this same issue arise if we try to replicate the scenario with user-defined types and interfaces?

**Comment by tfoleyNV** [comment]
Note: certainly if the reported error is that the call is ambiguous, as opposed to invalid, then there is a compiler bug underneath the other issues.

**Comment by csyonghe** [comment]
Yes it does report a list of candidates.

**Comment by tfoleyNV** [comment]
Here is the error message I get when I repro this:

```
tests/bugs/gh-246.slang(9): error 39999: no overload applicable to arguments of type (T, T)
slang-stdlib.cpp(1074): note 39999: candidate: +(uint64_t, uint64_t)[this:07F626D8, primary:00000000, next:00000000]
slang-stdlib.cpp(1067): note 39999: candidate: +(uint, uint)[this:05F13B00, primary:00000000, next:00000000]
slang-stdlib.cpp(1060): note 39999: candidate: +(, )[this:05F14408, primary:00000000, next:00000000]
slang-stdlib.cpp(1053): note 39999: candidate: +(float, float)[this:05F12C20, primary:00000000, next:00000000]
slang-stdlib.cpp(1046): note 39999: candidate: +(, )[this:05F11B20, primary:00000000, next:00000000]
slang-stdlib.cpp(1039): note 39999: candidate: +(int, int)[this:05F11E50, primary:00000000, next:00000000]
```

Note that the error message says `no overload applicable`, which is what I'd expect given the current implementation status. I don't think there is a bug here, although:

- The error message could be improved
- Some candidates are not being printed properly
- There is a lot of debugging cruft being printed out as part of the candidate list
- We eventual can and should support overloads of the standard math operators for these interfaces

We can either close this bug, or turn it into a feature request for some improvements that would avoid the problem where this looked like an ambiguity error when you encountered it.

**Comment by csyonghe** [comment]
Ah, OK, I misinterpreted this as an ambiguity error when I saw that list of candidates. We can close this now.

**Comment by tfoleyNV** [comment]
I tried out adding the following (bad) overload for `operator+` to the test code:

```
__generic<T:__BuiltinArithmeticType>
T operator+(T left, T right) { return left; }
```

This leads to a crash in the front-end when we need to construct a "transitive" type-conformance witness (because `float` is not directly a `__BuiltinArithmeticType`, but instead through inheritance) That may be another manifestation of the crashing bug you also reported.
