### ISSUE TITLE
Cannot use template parameter name as constructor 

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#248]
The following case would not compile:
```
//TEST(smoke, compute):COMPARE_COMPUTE:-xslang -use-ir
//TEST_INPUT:ubuffer(data=[0 0 0 0], stride=4):dxbinding(0),glbinding(0),out

RWStructuredBuffer<float> outputBuffer;

__generic<T:__BuiltinFloatingPointType>
T test(T v0, T v1)
{
    return T(3.0);
}

[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{ 
    float outVal = test<float>(1.0, 2.0);
	outputBuffer[dispatchThreadID.x] = outVal;
}
```

**Comment by tfoleyNV** [comment]
Hm. I would have expected that to work, since the stdlib does almost the exact same thing in its definition for `saturate`.

I’ll look into this, but *please* try to avoid using the `__Builtin*` interfaces to define all your test cases. They are supposed to be an implementation detail and subject to change, so we don’t want a lot of tests to be relying on their current implementations.

**Comment by tfoleyNV** [comment]
This ends up crashing because we try to emit IR for the `__BuiltinFloatingPointType.init` member, and codegen for constructors hasn't actually been implemented correctly. I'm honestly not clear on why this code triggers an issue when the `saturate()` implementation gets away with it.
