### ISSUE TITLE
Add support for generic interface methods

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#250]
We need to allow defining generic methods in an interface signature.

```
//TEST(compute):COMPARE_COMPUTE:-xslang -use-ir
//TEST_INPUT:ubuffer(data=[0 0 0 0], stride=4):dxbinding(0),glbinding(0),out

RWStructuredBuffer<float> outputBuffer;

interface IVertexInterpolant
{
    float2 getUV();
}

interface IBRDFPattern
{
    __generic<TVertexInterpolant:IVertexInterpolant>
    float evalPattern(TVertexInterpolant interpolants);
}

struct StandardVertexInterpolant : IVertexInterpolant
{
    float2 getUV() { return float2(0.5); }
};

struct MaterialPattern1 : IBRDFPattern
{
    float base;
    __generic<TVertexInterpolant:IVertexInterpolant>
    float evalPattern(TVertexInterpolant interpolants)
    {
        float rs = base + interpolants.getUV().x;
        return rs;
    }
};

__generic<TPattern : IBRDFPattern, TInterpolant: IBRDFPattern>
float test(TPattern pattern, TInterpolant vertInterps)
{
    float rs = pattern.evalPattern<TInterpolant>(vertInterps);    
    return rs;
}

[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    StandardVertexInterpolant vertInterp;
    MaterialPattern1 mp1;
    mp1.base = 0.5;
    float outVal = test<MaterialPattern1, StandardVertexInterpolant>(mp1, vertInterp);
    outputBuffer[dispatchThreadID.x] = outVal;
}
```

Currently, the compiler complains that `MaterialPattern1` does not implement `evalPattern`.

**Comment by tfoleyNV** [comment]
Just to go through the motions and make sure we actually need this feature:

- You don't necessarily have to support generic methods in interfaces for this example to work. You could instead have the `IBRDFPattern` interface either be generic in the vertex-attribute type, or use an associated type to export it

- Thinking about the actual scenario you are modeling, it seems weird to have the `IVertexInterpolant` interface that only exposes a single texture coordinate, since pattern generation in a real engine would probably want to have access to whatever attributes are defined on the mesh that the material is being applied to, right? So if we tried to solve that more real problem, it seems like we almost want a material pattern to have an associated type that is an conjunction/intersection of interfaces, and then constrain the actual vertex type to supporting that composite interface...

**Comment by tfoleyNV** [comment]
If you decide to enable this, I suspect the front-end work won't be too bad (mostly just adding another case for interface requirement satisfaction checks). Note that there is already a bit of machinery in `check.cpp` related to checking if two functions have the same signature (for detecting redeclarations and target-specific overloads), and that logic includes support for generic methods. Ideally we should find a way for the code that checks for interface requirement satisfaction to use that same logic.

The one big gotcha I can see is that we probably need to make the requirement-satisfaction checks do a pass that checks for associated types *first*, and then checks other kinds of requirements next, so that those checks can be done using substitutions that will be able to map the associated types in the requirement to their concrete realizations.

**Comment by csyonghe** [comment]
If we support a generic interface then we don't need generic methods. I think it would be easier to add generic method than to add generic interface.

Yes I have already modified conformance satisifaction check for generic decl members. Now I am running into an issue where ResolveOverload() fails to find an appropriate candidate for the evalPattern() call.

**Comment by tfoleyNV** [comment]
I agree that generic interface methods should be easier than generic interfaces, at least for the back-end. My expectation is that we can construct a witness table that just references the generic IR function, and then the code sequences will involve a `lookup_interface_method` that gets fed into a `specialize`, and the specialization of the lookup step will enable specialization of the method.

Generic interfaces might not actually be that bad either; hopefully it just means having a witness table where the "keys" are specialized decl-refs to the interface requirements.

The hard part as I understand it will be generic types that conform to interfaces, because at that point we need generic witness tables, and we'll have to support specialization of witness tables...

**Comment by csyonghe** [comment]
Support is added in PR #251
