### ISSUE TITLE
Need documentation

### ISSUE THREAD

**Issue by nbentyNV** [shader-slang/slang#258]
Doxygen style comments would help, especially for the reflection API

**Comment by tfoleyNV** [comment]
@nbenty Just to double-check, have you seen that we have *some* API documentation at:

<https://github.com/shader-slang/slang/blob/master/docs/api-users-guide.md>

I concede your point that doxygen-style comments would be nice. The main reason I've been avoiding those is because (1) I'm not clear on which kinds of documentation comments Visual Studio is able to scrape and surface in autocompletion tooltips, and (2) I'm worried that the answer will be something extremely verbose and annoying when I'd rather write documentation comments in markdown.
