### ISSUE TITLE
name mangling in getSpecializedFunc is wrong

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#260]
The `getSpecializedFunc` function first generates a mangled name for the specialized function. However, it is generating the mangled name directly from `specDeclRef`, which is wrong.

Suppose we have the following code

```
interface IBase
{
     __generic<T> float doIt(T obj);
     float doIt
}
struct Impl
{
    __generic<T> float doIt(T obj) 
   { ... }
};
__generic<G: IBase, T>
void test(G b, T obj)
{
     b.doIt(obj)    
}

void main()
{
   Impl g;
   g.doIt<float>(0.0);
}
```

When unspecialized `test` function will have the following IR:
```
f = lookup_interface_method(G, "doIt")
f_s = specialize(f, DeclRef(IBase::doIt, T=>float);
call f_s ...
```

When specializing `test` function, we will first replace f with the actual generic method:
```
f = Impl::doIt
f_s = specialize(f, DeclRef(IBase::doIt, T=>float)
```

Then, when we process the `specialize` instruction, we will first generate a mangled name based on the declRef:
```
mangledName = getMangledName(DeclRef(IBase:doIt, T=>float));
```

And this name is wrong, because `mangledName` will be something like `IBase_doIt`, but we need `Impl_doIt`.

**Comment by tfoleyNV** [comment]
I see. This is the one case where the `decl` part of the `DeclRef` passed to `specialize` actually matters, and it seems like it is not helpful in this case.

A brute-force solution here would be for IR functions to just hang onto a full `DeclRef` to the AST-level function they were created from, and to propagate that through specialization. Then generic specialization could easily use the existing `DeclRef` attached to the function as the base for a new specialized `DeclRef` to use for subsitution. This isn't that bad when we consider that generic functions already reference the AST-level `GenericDecl` around them, so there isn't much harm in just straight-up referencing the full AST decl.

The second solution I can see is to drop the idea that the mangled name for a specialization is derived by doing a from-scratch mangling of the original decl. Instead, we should say that a specialized function's mangled name is the original mangled name (for the unspecialized func) + a suffix that is based on the manglings of the values used for specialization. That seems like it might be easier to manage, and it opens the door for adding other suffixes to represent the outputs of other optimization/transformation passes.

I'm fine with either option, really; we won't know what works well until we try something. The one big gotcha I want us to keep in mind here is what would happen if `Impl` was itself generic, in case that might affect our choices.

**Comment by csyonghe** [comment]
I am not sure I understand your first approach well enough to see how it is capable of handling the `Impl` being a generic case.

For your second approach, I am concerning whether we  could end up generating duplicate specializations because we reach that specialization from different paths.

**Comment by tfoleyNV** [comment]
Just to follow up for documentary purposes. The PR that implemented a fix for this used the second option I talked about: it adds a suffix to a generic based on how it was specialized. It does, however, retain the original approach as well, for the case where the decls match between the `DeclRef` used for substitution, and the `GenericDecl` attached to the `IRFunc`. I belive that *does* create a risk that we might encounter the same specialization via different paths, if we call `SomeType.someMethod` both directly and indirectly via an interface.

Eventually we could switch to treating the suffix-based approach as the only one, so that we always add `_G<stuff goes here>` to the end for each "level" of generic specialization. This would potentially allow for partial specialization, so that if you have `SomeType<T>.someMethod<U>` you could specialize for `T -> float`, but leave `U` generic.

To clarify what I meant with my first approach, I meant that currently `IRFunc` has an optional `GenericDecl*` that points to the first generic ancestor of the actual `CallableDecl` that was lowered (if things are unspecialized). Realistically, it would be a small change to have an `IRFunc` instead store a `DeclRef` to the callable decl itself (initially with `nullptr` for the substitutions).

Then, when it comes time to specialize an `IRFunc` it would be *really* easy to just take the `DeclRef` from the `IRFunc`, and attach the `Substitutions` from the decl-ref passed to `specialize`, and you'd get something you can mangle. We already have a step where we clone the `Substitutions` to make them apply to the "correct" declaration, so a lot of the work already happens - we just use the parent `GenericDecl` instead of the `CallableDecl` itself.

The specialized function that results would then store the new (specialized) `DeclRef` instead of the unspecialized one. I believe that would actually be something we can make work for multiple rounds of specialization for things like `SomeType<T>.someMethod<U>`, so long as the IR guarantees that specialization always proceed from the outer-most to the inner-most generic.

Which approach we take relies a lot on whether we want to let the IR be tangled up with the AST or not. I'm inclined to let things stay entangled for now, because we already leverage the AST side of things so much. We can revisit that decision down the road if we decide it is creating problems.

(Just to make one bit of philosophy clear: I don't see our IR as being a general-purpose IR meant to solve the "N times M" problem between source languages and target languages. It is a high-level IR for a specific language, designed for that language's feature set, so it is really "one to M." As a result, the only argument against letting the AST bleed into the IR is if it starts making it hard to implement the features we want at either level.)
