### ISSUE TITLE
Support `static` methods

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#270]
To express entry point functions in a entry-point-set struct, we need to be able to define the entry point functions as static methods of a struct type.

For example, we should be able to compile:
```
struct EPS
{
      static VSOut vsMain(VSIn vsIn) {}
      static FSOut fsMain(VSOut vsOut) {}
};
```

**Comment by tfoleyNV** [comment]
I don't disagree that we should support `static` methods, but I'm not sure I agree on your motivating example. My assumption had been that when writing an "entry point set" type, the fields of the type would correspond to uniform shader parameters:

```
struct EPS
{
    Texture2D diffuseTex;
    ParameterBlock<Light> lightSource;

    VSOut vsMain(VSin vsInt) {
        /* need to be able to access `diffuseTex` here */
    }
}
```

How were you planning to represent uniform parameters in the case where the kernels are `static` methods?

**Comment by csyonghe** [comment]
The way I think of it, is that an entrypoint set is a static struct, where all its members are static.
That way we get rid of the issue that vsMain function will have an implicit this parameter, which does not make too much sense.

**Comment by tfoleyNV** [comment]
We clearly see this very differently, because I'd say that the `vsMain()` function having an implicit `this` parameter that brings along all the uniform shader parameters makes *perfect* sense. The `EPS` type is basically its own record type for the `@Uniform` rate.

Making all that data be `static` doesn't really seem to *mean* anything from a modelling perspective, and it immediately invites questions from users about why they have to redundantly type `static` on every single shader parameter, every single per-stage kernel, and (I just realized this) every single other method they might call (any code that wants to access the parameters will need to be defined as a method, and they'll all need to be `static`).

The other big argument for non-`static` members in an entry point set type is the example we discussed earlier of writing an EPS for a tessellation effect, and then running that EPS on something like Metal just by passing it through to another EPS:

```
struct MyTessellationEPS : ITessellationPipeline { StructureBuffer<float4> whatever; ...  }

struct MetalComputeTess<P : ITessellationPipeline>
{
    P tessImpl;

    void computeMain()
    {
        P.PatchData patch = tessImpl.hullMain( ... );
        // etc.
    }
}
```

I guess you could write something like that with purely static methods in the interfaces (but at the cost of a lot of ugliness), but it just seems like it makes things more confusing, right?

**Comment by csyonghe** [comment]
I am not sure how you implement that 'this' parameter. If entry-points are not static members, that means conceptually I can invoke an entry-point function with a different `this` argument. And it seems that invites a lot of possibilities when the code type checks but the compiler cannot work out statically how to access those resource parameters?

I always feel that should just be static from the type system's point of view. And it is not going to be messy if you allow `static` keyword on `struct`. In your example, this can be
```
static struct MyTessellationEPS : ITessellationPipeline { StructureBuffer<float4> whatever; ...  }

static struct MetalComputeTess<P : ITessellationPipeline>
{
    P tessImpl;

    void computeMain()
    {
        P.PatchData patch = tessImpl.hullMain( ... );
        // etc.
    }
}
```

**Comment by csyonghe** [comment]
I may be confusing myself by thinking multiple problems at once here.  I agree that the "access resource types from a struct variable" problem can be solved at the IR level. I don't know why I am still feeling this way, but but I am somehow more comfortable with some more syntax cues to remove that concern (so that we don't always rely on the IR optimization pass to resolve resource parameter accesses if we are not actively using that feature).

**Comment by tfoleyNV** [comment]
Long story short, I don't see any reason for imposing `static` that we can justify to users. It makes more work for them, and we both agree that our compiler already *has* to do the optimizations necessary to handle functions that take `struct`s full of resources as parameters.

Adding `static struct` a la C# would be a hard sell for me. That "feature," together with `import static`, is an obvious band-aid they put on to try to make up for the Java-inspired idea of banning ordinary functions so that users had to write `Math.sin(...)` all over the place. If we aren't copying the original mistake, then I don't see why we'd copy the band-aid.

There's also the point that adding yet another meaning to `static` (which is already really overloaded) is a bad idea, and having *this* notion of "`static` types" would make trying to explain "virtual types" down the road even harder (since the starting point for explaining virtual types is to point out "did you ever think about how type members are all implicitly `static` members in most languages?").

**Comment by csyonghe** [comment]
Agreed. My intention for introducing `static` is just to remove the need for wraping everything into an extra layer of struct argument. If that is not big concern then we shouldn't be worrying about it.

Yes, `static` classes in C# is a band-aid for not having ordinary functions. But if you need a construct that encapsulates multiple ordinary functions without introducing a this parameter, that's exactly what a `static` class is for.

Anyway, I don't have a strong argument for `static` members either except for avoid introducing the `this` parameter. Forcing `ParameterBlock<T>` being a member of a `struct` and allowing assignments of `ParameterBlock<T>` values seemed a big complexity to me. Are we capable of analyzing such uses of parameter blocks as of now?

**Comment by tangent-vector** [comment]
Closing. We support `static` methods now (including `static` methods in `interface`s).
We don't support having `static` member functions as shader entry points, but that seems like a secondary concern.
