### ISSUE TITLE
API for compiling entry point sets

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#271]
Proposing the following API:

```
struct Value
{
    int valueType;
    char * stringValue;
    int intValue;
    float floatValue;
};
struct EntryPointSet
{
     const char * name;
     SlangProfileID vsProfile, psProfile, hsProfile, gsProfile, dsProfile;
     int specializationArgumentCount;
     Value ** arguments;
};
int spAddEntryPointSet(compileRequest, EntryPointSet entryPointSet);

SLANG_API char const* spGetEntryPointSetSource(
        SlangCompileRequest*    request,
        int                     entryPointSetIndex,
        SlangStage       stage);

SLANG_API char const* spGetEntryPointSetCode(
        SlangCompileRequest*    request,
        int                     entryPointSetIndex,
        SlangStage       stage);
```

When a compile request gets executed, it will compile the entry points defined in an entry point set using the corresponding profiles. The compiled code can be retrieved via `spGetEntryPointSetSource` and `spGetEntryPointSetCode` functions. `spGetEntryPointSetSource` returns null if the corresponding stage is not defined by the entry point set.

**Comment by tfoleyNV** [comment]
Hmm... I'm not sure about that proposal.

* Where is this notion of "specialization arguments" coming from? We haven't discussed adding them to Slang so far, so I'm surprised to see them here.

* The `EntryPointSet` type seems like it would be fragile, since it will break whenever if we ever needed to compile a platform with a different combination of stages.

* There's some redundancy in having `spGetEntryPointSetCode()` when we already have `spGetEntryPointCode()`.

My inclination might be something like:

```
int spAddEntryPointSet(compileRequest, translationUnitIndex, char const* name);
int spEntryPointSet_AddEntryPoint(compileRequest, entryPointSetIndex, profile);
```

The big differences:

* An entry point set is created with respect to some translation unit, so we know where to find it in teh source code

* I've dropped specialization arguments because I don't know why they are coming up here

* Adding entry points is done one at a time, so we can add whatever combination we want easily, and it more closely mirrors the existing API for defining entry points in a translation unit

* The result of `spEntryPointSet_AddEntryPoint` is an entry point index like any other (from the user's perspective), so any APIs for accessing generated code are the same as always.

A further refinement might be to not even need to specify the individual entry points for an entry-point set, and instead have them be specified on the shader side (for now, just by the presence or absence of the corresponding method). Then the user could just specify a general profile like `sm_5_0` for the whole entry point set.

Also, if the API were more in an object-oriented style, I'd almost wonder if "translation unit" and "entry point set" should share some sort of base class since they can both contain entry points... I don't think there is anything actionable there, but I'm just trying to understand the structure.

**Comment by tfoleyNV** [comment]
A further thought on this topic:

We shouldn't break the existing API, but it might be nice to start working toward a model where kernels are *always* grouped into "entry point sets," even if they weren't specified that way in the code.

To pseudo-code for a bit, the user would start with:

```
CompileRequest* compileRequest = spCreateCompileRequest();
TranslationUnit* tu = spAddTranslationUnit(compileRequest, SOURCE_LANGUAGE_SLANG);
// add source files/strings
```

Then the user can either create an entry point set by specifying one named in the code:

```
EntryPointSet* eps = spAddEntryPointSet(tu, "myCoolEntryPointSet", "sm_5_0");
```

or by creating an empty one and adding kernels declared at the global scope to it:

```
EntryPointSet* eps = spCreateEntryPointSet(compileRequest, /* shader model? */);
spAddEntryPoint(eps, tu, "vsMain", STAGE_VERTEX /* or profile, if no shader model above */); 
```

In terms of the implementation, this would help ensure that every entry point belongs to an entry point set (in case that helps simplify anything in the implementation), although some of those entry point sets won't have a concrete representation in the code.

Once you have this mental model, it is pretty easy to see that in "legacy" code that adds a "global" entry point without an entry point set, you just follow these rules:

* If the profile is a compute one, then add the kernel to its own fresh entry point set
* If the profile is a graphics one, then add the kernel to a unique "default" entry point set for the compile request (created on demand)

**Comment by csyonghe** [comment]
We need specialization argument is because our generic parameter can either be a type or a value. That translates to two corresponding types of specialization arguments.

**Comment by csyonghe** [comment]
Yeah, I like your API design better. It aligns with our intention to always have an internal entrypointset structure.

We can probably ignore generic arguments being normal values for entrypointsets for now.

**Comment by tfoleyNV** [comment]
Okay, I totally didn't realize that the `Value` stuff was for passing through the generic arguments.

> We can probably ignore generic arguments being normal values for entrypointsets for now.

I agree on that. For now we could even say that generic value arguments are not meant to be a user-accessible feature, and they only exist so that we can implement the stdlib.

Is your intention that for a generic entry point you'd use the `stringValue` case to pass in the name of a type to use for the generic type parameters? That's probably sufficient for now.

Long term (and maybe we should just plan to do this "right" the first time) the correct approach would seem to be that in a first step we use `spCompile` to compile a (generic) entry point set to IR. If we have an interface to represent the pipeline structure, then the actual IR representation of the entry point set is basically a (generic) witness table. The user should be able to serialize that IR, do reflection on parameter binding information, etc.

Later on, when they've picked type arguments (ideally represented as `SlangReflectionType*`, if we can pull it off), they should be able to call a new API (probably not the current `spCompile`) to take their entry point set and specialize it for those arguments (and possibly a concrete code generation target). This step should then extract the entry point methods from the witness table, specialize them, and generate final code.

This design would let us achieve something that Spire never quite got to, which is amortizing away all the front-end compiler work across multiple specialized variants.

One thing that is missing in the above is that we really ought to have a notion of a "linkage" which retains the relevant information from multiple compile requests (even after the request object gets deleted), so that you can specialize an entry point set from one compile request using a type from another compile request.

I don't know how much of this we are likely to get to in our current push, but it probably helps if we can work together on a shared vision for what the ideal API would look like down the road.

**Comment by csyonghe** [comment]
OK, it seems the API you are proposing would be something like this:
```
CompiledModule * spCompile(compileRequest);
CompiledModule * spLoadModule(fileName);
void spModuleSaveToFile(CompiledModule*, fileName);
CompiledObject* spFindCodeObject(CompiledModule*, objectName);
TargetProgram* spLinkProgram(CompiledObject* entryPoint, CompiledObject* arguments[]);
const char* spProgramGetCode(TargetProgram*, stage);
```

**Comment by tfoleyNV** [comment]
Yeah, that looks pretty much right.

Probably the biggest design question I can see is how the `CompiledObject` there relates to our reflection API. It might be nice if the `CompiledObject` there is just our already-existing `SlangReflectionType`, but that might also constrain how things are implemented.

**Comment by csyonghe** [comment]
Hmm, I am not sure about this either. I am kind of lean towards adding
```
SlangReflectionType* spCompiledObjectGetReflection(CompiledObject*)
```
Just to decouple existing reflection API from compilation API?
Otherwise we could be introducing breaking changes to existing reflection API...

**Comment by tangent-vector** [comment]
The `IComponentType` APIs cover almost everything that this discussion related to.
Closing.
