### ISSUE TITLE
Today's installment of weird loops and autodiff

### ISSUE THREAD

**Issue by expipiplus1** [shader-slang/slang#2914]
If we replace the for loop in `outerF` in `tests/autodiff/high-order-backward-diff-3.slang` with the equivalent do/while loop then we get bogus results from the backward diff pass:

before

```hlsl
    for (int i = 0; i < 2; ++i)
    {
        nx.x = nx.x * x.x;
    }
```

after

```
    int i = 0;
    [MaxIters(2)]
    do
    {
        nx.x = nx.x * x.x;
        i++;
    } while (i < 2);
```

The first thing I notice when looking at the diff in generated sources is the additional array `int[4]` in `s_bwd_outerF_Intermediates_0`. 

Adding `[ForceUnroll]` to the loop allows getting the correct result.

**Comment by csyonghe** [comment]
The additional `int[4]` is due to the ad-hoc implementation of induction variable detection in `AutodiffCheckpointPolicyBase::collectInductionValues`. It is currently hard coded to only recognize the usage pattern introduced by a `for` statement and probably failed to recognize the `i` as an induction variable that can be replaced by a loop counter here.

**Comment by csyonghe** [comment]
If we plan to run the loop inversion pass universally, then we need to make sure this induction value optimization in the autodiff pass can remove the unnecessary storage of these induction variables in an inverted loop. We should replace `collectInductionValues` with a more systematic implementation before enabling loop inversion, because extra storage in `intermediates` types can lead to severe performance degradation.

**Comment by expipiplus1** [comment]
> If we plan to run the loop inversion pass universally, then we need to make sure this induction value optimization in the autodiff pass can remove the unnecessary storage of these induction variables in an inverted loop. We should replace `collectInductionValues` with a more systematic implementation before enabling loop inversion, because extra storage in `intermediates` types can lead to severe performance degradation.

I wouldn't suggest running it universally, only in cases where we think the loop has a minbound of 1. Running it universally is what I'm doing for testing
