### ISSUE TITLE
GLSL varying parameter reflection is not part of the entry point reflection

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#301]
Slang reflects varying parameters as globals instead of entry-point attributes.
I understand that the GLSL syntax is weird, but in/out parameters are entry-point attributes, not globals. I believe Slang should report them as such.

**Comment by tfoleyNV** [comment]
There would be some annoying (and error-prone) implementation complexity in giving you what you are asking for here. More importantly, the philosophy of the Slang reflection API is to reflect the program “as written” and not some transformation of it that tries to paper over language or API differences.

Is there something specific you are trying to do where the current approach makes things hard? Thinking about the API, it seems like I’m missing a query that would let you ask a varying input/output what stage it belongs to. If I add that, would you be able to extract what you need by just walking all global-scope parameters (which you already need to do) and recognizing some of them as varying input/output?

(Aside: the reflection API calls the parameter category vertex/fragment input/output, but it is really used for all varyings. The name needs to change, but I can’t risk breaking compatibility.)

**Comment by tfoleyNV** [comment]
Nir and I followed up on this in more detail, and we agree that for now it is sufficient if Slang provides an API to determine the stage that a varying parameter belongs to. I'm working on that right now, with teh following signature:

```c++
/** Get the stage that a variable belongs to (if any).

A variable "belongs" to a specific stage when it is a varying input/output
parameter either defined as part of the parameter list for an entry
point *or* at the global scope of a stage-specific GLSL code file (e.g.,
an `in` parameter in a GLSL `.vs` file belongs to the vertex stage).
*/
SLANG_API SlangStage spReflectionVariableLayout_getStage(
    SlangReflectionVariableLayout* var);
```

This will return `SLANG_STAGE_NONE` for anything that is not a "direct" varying parameter. So if you have a global variable `in MyStruct s;` in your GLSL `myShader.vs`, then the variable layout for `s` will give you `SLANG_STAGE_VERTEX`, but if you make the query on `s.someField` you willd get `SLANG_STAGE_NONE` because the same `struct` type might be used for both varying input and output, so the struct fields don't belong to any one stage.

We also discussed starting to add support for a "stage mask" as used by the binding model for D3D12/Vulkan, but I'd like to approach that as a separate feature, and not cloud things around the varying input/output issue.

**Comment by tfoleyNV** [comment]
PR #302 should fix this for Falcor's purposes. I'll plan to create a new release that includes the fix once it goes through testing on our side.

As an internal comment for the "Slang team" I'll note that I'm not very happy with the current implementation of this feature, since it just further bloats the `VarLayout` type. It also doesn't deal with the possibility of a setup where a single varying parameter is used by multiple stages. E.g., one can imagine a language model where a single declaration could stand for both a vertex output and fragment input; the way Slang handles parameter *binding* would have no problems with this, but it would not work with this idea that a parameter can only have one stage.

A more efficient and general solution in the long term would be to have a `VarLayout` (and similarly for `TypeLayout`) store a single list of resource usage entries (similar to the current `ResourceInfo`) where each entry can have a primary and a secondary "tag," plus a single integer for the usage. These entries would be sorted by the primary/secondary tags, so that lookup can be efficient (logarithmic).

All of the standard resource-usage cases today would just use the primary tag. Rather than store a space for every entry (which is wasteful), non-zero spaces for a given resource kind would be stored as an entry with a primary tag that identifies it as a space, and a secondary tag that identifies the resource it is the space for (or `NONE` to indicate that it is a space that applies to everything in the parameter).

Varying input/output would be indicated by a primary tag, and then the particular stage or "boundary" that the parameter applies to would be the secondary tag. I say "boundary" because the reflection API eventually needs to tell per-control-point and per-patch varyings apart for tessellation.

The nice thing about a representation like that is that arbitrary additional data can be inserted into the list on an as-needed basis without bloating every layout object. This would also simplify unique-ing of layout objects so that we can cache and re-use them. In the limit, the list can be tail-allocated on the layout object itself, so that every layout is a single heap allocation.

Anyway, we can tuck that away in the endless list of micro-optimizations we can start doing if/when we have time to worry about efficiency.

**Comment by nbenty** [comment]
Just to confirm that I understand the new function correctly, the following should work:
```
        for (uint32_t i = 0; i < pSlangReflector->getParameterCount(); i++)
        {
            VariableLayoutReflection* pSlangLayout = pSlangReflector->getParameterByIndex(i);
            if(spReflectionVariableLayout_getStage(pSlangLayout) != SLANG_STAGE_NONE)
               // This is a varying parameter
            else
              // This is a uniform parameter
        }
```

**Comment by tfoleyNV** [comment]
@nbenty That code should work, yes (although I think you want `pSlangLayout->getStage()` since you are using the C++ wrappers).

I wouldn't encourage looking at it that way. I would rather say that you should be looking for `Slang::ParameterCategory::VaryingInput` and `VaryingOutput` to identify varyings. Still, the above should work for your purposes, and I don't plan to change the API in a way that breaks it without consulting you first.
