### ISSUE TITLE
specialize generic struct type 

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#318]
The following test case currently triggers compiler error:
```
//TEST(smoke,compute):COMPARE_COMPUTE:-xslang -use-ir
//TEST_INPUT:ubuffer(data=[0 0 0 0], stride=4):dxbinding(0),glbinding(0),out
// Confirm that generics syntax can be used in user
// code and generates valid output.

RWStructuredBuffer<float> outputBuffer;

__generic<T>
struct GenStruct
{
	T x;
};

__generic<T>
T test(T val)
{
	GenStruct<T> gs;
	gs.x = val;
	gs.y = val;
	return gs.x;
}


[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
	uint tid = dispatchThreadID.x;

	float inVal = float(tid);

	float outVal = test<float>(inVal);

	outputBuffer[tid] = outVal;
}
```

The compiler crashes at visitGenericDecl() in lower-to-ir.cpp, as the current implementation does not expect the generic decl to contain a struct decl. After making this function return LoweredValInfo() when genDecl->inner is a struct decl, the compiler no longer crashes, but is generating `GenStruct<float>` in the output HLSL.

The reason for this is that Slang currently does not specialize `GenStruct<Float>` into an actual struct  type in IR, e.g. `struct GenStruct_Float`, but instead keeps the DeclRefType with substitutions all the way until emit. However, it is too late to specialize the struct at emitting, because we won't have the opportunity to run all the type legalization logic.

It seems the right way is to add a struct type specialization pass to replace all references to generic struct types with actual struct types, and then we can make use of existing legalization logic to handle cases where some fields of the specialized struct is a resource type.

However since IR type is the same as AST type, this could mean that we need to construct new SyntaxNodes in the IR pass.

**Comment by tfoleyNV** [comment]
I think I have a simpler plan for making this work, so please don’t dive into any implementation work on this. I’ll try to write up my proposal later tonight.

**Comment by tfoleyNV** [comment]
Actually, maybe I have time now.

The emit logic already outputs `struct` types for IR code on demand, and maintains a set of the types it has already output. It should be enough if:

- We track what `struct` types have been output based on their `DeclRef` (or a mangled name for one) rather than just their `Decl`

- When outputting a `struct` for IR-based code we output it with the mangled name of the particular specialization (and all use sites should use this name too)

We have logic along those lines in place for detecting when things are “IR decls” that should have treatment like the above, but I think right now it only applies when other decls are being handled by the AST-to-AST rewriter.

Hopefully the fix for this issue is just to recognize that *all* `struct` decls need this treatment when we are in “full IR mode.”

**Comment by csyonghe** [comment]
I see. Will type legalization apply on that as well?

Yong

**Comment by tfoleyNV** [comment]
The legalization logic might still have issues, if it is maintaining a map with decls as keys (instead of decl refs). In principle, though, it should produce a different legalized decl for each original decl that requires splitting.

We could conceivably have it also decide that all generic `struct` types should be legalized away, and handle it that way.

I can try to push through a fix for this unless you really want to own it.

**Comment by csyonghe** [comment]
I see. Yeah may be it is faster for you to fix it.

Yong

**Comment by tfoleyNV** [comment]
I'm going to start working on this, using the test case in Yong's original message as a starting point.
