### ISSUE TITLE
Handling duplicate global/CB declarations in multi-file Slang code

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#323]
When the compiler gets multiple `.slang` files as input to a compile request, it groups them all into a single translation unit. In the simplest terms, you could think of this as being like concatenating the input files into one, and then feeding *that* to the compiler (but that isn't *quite* accurate).

Right now, a problem arises if you feed in both `MyVS.slang` and `MyFS.slang` where those files duplicate some shader parameter declarations (e.g., a `cbuffer` declaration in a file that both of them `#include`). Right now the front-end fails to diagnose the colliding declarations (even though they are in the same translation unit), and then parameter layout identifies them as the "same" shader parameter (any two globals with the same name are counted as the same parameter right now).

This means that there is only a single layout object created (based on whichever declaration gets seen first). Later, when legalizing IR-based code, we will end up trying to split the type of one `cbuffer` declaration using the type layout of the other, so that things break when looking up a field in a layout that knows nothing about that field.

This is a complex, messy situation.

The simplest fix (and seemingly the correct one) is to have the front-end reject code like I just described, by diagnosing the duplicate variable declarations. This would be a bit confusing in the above case, since the "duplicate" declarations both come from the same file.

It is possible that similar bugs could arise in the multiple-TU case, where different declarations that represent the same parameter *are* allowed. In those cases the likely fixes would be:

- Merge field information from all matching declarations of a parameter. We already have support for such things in `StructTypeLayout`, so it might be a simple fix.

- Have the lookup process for entries in a `StructTypeLayout` use indices instead of field decl-refs. That would require tuple elements to track a field index and not just a decl-ref, but it might be worth it.

**Comment by tfoleyNV** [comment]
Talking this over with Nir, it seems like the simplest solution from the perspective of Falcor would be if we just treated multiple `.slang` files passed to the API the same way we treat multiple `.hlsl` files. And honestly that seems like a reasonable request, and seems to be the intent what is being expressed by Falcor's use of the Slang API. I potentially got confused because when using the command-line interface there is no way to have multiple Slang translation units at once.

Okay, so if we need to support the use case of multiple `.slang` translation units, which could each declare matching `cbuffer`s, then this isn't a front-end issue (or at least isn't *just* a front-end issue), and we *do* need to find a way to make the type legalization able to handle `cbuffer`s that might be declared  in multiple TUs (or more generally, parameters using aggregate types declared in multiple TUs).

**Comment by tangent-vector** [comment]
Closing.
We have moved past this model. The need to handle overlapping `cbuffer`s and other global shader parameters across translation units was a huge pain for the code, and the actual intent can be achieved much more easily using proper Slang mechanisms.
