### ISSUE TITLE
Support `ParameterBlock` arrays

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#334]
In order to move the lighting system to `ParameterBlock` we need to be able to use the following syntax:
`ParameterBlock<LightData> gLights[16]`.
On top of that, the current way in which Slang handle arrays-of-structs that contain textures make is hard to use pre-built parameter blocks. This is because it will convert the texture in `LightData` to
`Texture2D some_slang_decore_gLights_texture[16]`.
For array of parameter blocks, we need each texture to use its own descriptor set.

**Comment by csyonghe** [comment]
Parameter blocks are not supposed to be used this way.
On Vulkan there is a limit on max parameter blocks you can use for a shader (it is 8), so an array of size 16 will likely not work.

It seems the right solution here is to either use ParameterBlock<LightDataArray> where LightDataArray is a struct of LightData[16], but as you have said it complicates working with textures.

The cleanest way to do so may be to use simulated bindless textures: instead of declaring Texture2D in LightData, we can simply define an `int textureId`. Then the engine passes all textures in a separate parameter block that is just an array of Texture2Ds. This requires the engine to manage such table of Texture2D resources but in general it makes handling texture resources much easier.

**Comment by nbenty** [comment]
I had a discussion with Tim regarding `ParameterBlock<LightDataArray>`.
The main issue with that is that it prevents us from using a block per light, which is useful in case we want to stream light-data into the shader based on location (i.e. local point lights, light-probes, etc.)

It also means that for dynamic light sources (i.e. intensity changes with time) we will need to update the entire CB, even if most of the lights are static.

All of the above are solvable. Just want to make sure we're not missing something

**Comment by csyonghe** [comment]
Yeah, arrays of parameter blocks may not be a viable solution here due to API limits.

For light data streaming I'd put all LightData into a StructuredBuffer, and use a level of direction (light ids) to specifies which lights to use for a draw.

It shouldn't hurt that much to update small portions of the global light buffer per frame, especially when the engine partitions light data into static and persistently mapped dynamic buffers and use double buffering for dynamic data.

**Comment by tfoleyNV** [comment]
@nbenty I thought we’d had a Slack conversation about this and came to the conclusion that arrays of parameter blocks just flat out couldn’t be supported because there was no way to deal with dynamic indexing into the array (and ruling it out statically would be a big task for Slang).

@csyonghe I think the relevant point here is that Falcor wants to be able to wrap up each CPU-side light as a “thing” and then have a way to efficiently bind an array of such things. This is really strongly related to all the discussion we’ve been having lately about “sub-components” kinds of things.

My first thought (hastily typed on my phone, so take it with a grain of salt) is that the ideal answer for an application is to give each “shader component” style object a host accessible descriptor table (one or more) where binding get stored when set. Then allow the host-accessible tables to either be “flushed” to fresh GPU-accessible tables when you need to treat the component as a single top-level parameter block, *or* do a copy from those host-accessible tables into the backing storage of a larger “macro” parameter block. Either way the operation is just a single API call to copy descriptors from one table to another (for a contiguous range). There is a bit more work if the object wants to hold a CPU-side copy of any uniforms in the block.

This requires Slang to provide the layout information for the `LightData` type, even if it isn’t used directly as a parameter block. It also requires Slang to provide useful information that the app can use when binding a light into a larger block (e.g., for an array).

**Comment by nbenty** [comment]
@tfoleyNV - correct, I'd like each C++ light object to hold a `LightData` parameter-block.
I don't mind copying the data. The problem is that Slang converts the array-of-structs (`ParameterBlock<LightData> gLights[16]`) into a struct-of-arrays (at least for the textures). This makes it hard to efficiently copy the descriptors for the block in the C++ object into the GPU descriptor table.

As a first (and potentially the only) solution, it would if all of the textures for a specific array-object will be contiguous.

**Comment by tfoleyNV** [comment]
Given that there is no (reasonable) way for us to support arrays of parameter blocks, I'm going to close this. The discussion was hopefully helpful in getting everybody on the same page.
