### ISSUE TITLE
Support SSBO syntax in GLSL compatibility mode.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#3348]
We should transform a GLSL SSBO into a `[RW]StructuredBuffer` if it does not end with an unsized array, or into a `[RW]ByteAddressBuffer` when it does.

**Comment by csyonghe** [comment]
With #3400 merged, we now support two cases: SSBO with a simple struct element, or SSBO with a single array element.

We need to support the remaining case where the SSBO is a struct with more than one fields, and the last field is an unsized array. As we have discussed, we don't need to implement the general lowering of that to a byteaddressbuffer for now, and just convert them directly into glsl ssbo or spirv storagebuffer pointer.

**Comment by natduca** [comment]
Great news! @expipiplus1  wdyt of us taking those two remaining tasks and filing one or two issues for fixing those defects? This bug basically covers support, so we could close it since now we support it but with a few bugs and we can get a new bug that we can then triage to track the remaining work.

Your call if one vs two issues --- not sure if the fix for both is one patch that fixes both bugs, or if its really two totally different types of work. If one, then I'd file one issue, if two, two. :)
