### ISSUE TITLE
Issue with `-emit-spirv-directly`, `GetDimensions` and `Sampler3D`

### ISSUE THREAD

**Issue by mklefrancois** [shader-slang/slang#3360]
When creating the shader module with the Spir-V generated using `-emit-spirv-directly`, an error is showing up:

```
vkCreateShaderModule(): pCreateInfo->pCode is not valid SPIR-V: Expected Image to be of type OpTypeImage
  %vecSize = OpImageQuerySizeLod %v3uint %354 %int_0
```

This error is not present when we are not using the `-emit-spirv-directly` option

Command line
```
slangc.exe -profile glsl_460 -target spirv -emit-spirv-directly -force-glsl-scalar-layout -fvk-use-entrypoint-name -D__slang -source-embed-style text -source-embed-name rasterSlang -o raster_slang.h raster.slang
```

[slang-3dtexture.zip](https://github.com/shader-slang/slang/files/13490405/slang-3dtexture.zip)

**Comment by csyonghe** [comment]
The related logic is defined in `writeGetDimensionFunctions()` which is called from hlsl.meta.slang:985.

The problem is that both `Sampler2D::GetDimension()` and `Texture2D::GetDimension()` is using the same definition, which is OK for other backends, but obviously wrong for spirv.

The fix is to change `writeGetDimensionFunctions` to emit something like:

```
void GetDimensions(..)
{
      __target_switch
     {
            //...
      case spirv:
             if (isCombined)
             {
                  spirv_asm {
                        %image:__imageType(this) = OpImage $this;
                        %size:$$uint = OpImageQueryXXX %image ...;
                        OpStore ...
                  };
             }
             else
             {
                  spirv_asm {
                        %size:$$uint = OpImageQueryXXX $this ...;
                        OpStore ...
                  }
             }
     }
}
```

where `isCombined` is defined in `hlsl.meta.slang:982`.

The current way `writeGetDimensionFunc` is implemented might need to be refactored a little bit to be able to generate that `if` in the `spirv` case.

This is a good opportunity to get familiar with our stdlib code gen mechanism.

**Comment by pmistryNV** [comment]
Looking into the bug
