### ISSUE TITLE
Bring intrinsic coverage in glsl.meta.slang to parity with hlsl intrinsics.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#3362]

**Comment by jkwak-work** [comment]
I found that some types are defined from an extension.
https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GL_EXT_shader_16bit_storage.txt
The 20 new types are:
 int8_t      i8vec2      i8vec3     i8vec4    uint8_t     u8vec2      u8vec3     u8vec4
 float16_t   f16vec2     f16vec3    f16vec4    int16_t     i16vec2     i16vec3    i16vec4    uint16_t    u16vec2     u16vec3    u16vec4

**Comment by jkwak-work** [comment]
Note for myself.
"The OpenGL® Shading Language, Version 4.60.8" can be found here:
https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.pdf

**Comment by jkwak-work** [comment]
I am trying to get a smaller set of GLSL functions that are more frequently used in OpenGL applications.
We will prioritize on the small set of functions first.

In order to get some data, I checked a few games that support Vulkan/OpenGL.
Games using Vulkan turned out to be storing the shader code in SPIRV format and I couldn't get any information of which GLSL functions are used.
Games using OpenGL turned out to rely on SDL; that is the case of "Portal RTX" and "Counter strike".
This approach gave me no useful data.

Yong on Slack suggested a different approach that we can bring the parity with our existing HLSL intrinsic.
When we generate GLSL target code from HLSL, Slang can convert HLSL functions GLSL functions.
But currently those GLSL functions are not recognized back when they are used as an input to Slang.
We can start from implementing those GLSL functions.

More specifically there are lines that generate GLSL target code.
One of the examples is following:
        __target_switch
        {
        case glsl: __intrinsic_asm "EmitVertex()";
        case hlsl: __intrinsic_asm ".Append";
        case spirv: spirv_asm { OpEmitVertex; };
        }
This is example, we need "EmitVertex()" function implemented in glsl.meta.slang.

Another case for the parity is on the lines with a keyword "__target_intrinsic(glsl,"
The snippet below shows a case where HLSL function "f16to32()" gets converted to "unpackHalf2x16()" when the target is GLSL.
__target_intrinsic(glsl, "unpackHalf2x16($0).x")
__target_intrinsic(cuda, "__half2float")
__target_intrinsic(spirv, "OpFConvert resultType resultId _0")
__glsl_version(420)
[__readNone]
float f16tof32(float16_t value);

**Comment by jkwak-work** [comment]
I got a list of function names based on the new approach.
"hlsl.meta.slang" uses following 185 GLSL function names:
EmitMeshTasksEXT
EmitVertex
EndPrimitive
SetMeshOutputsEXT
all
any
atan
atomicAdd
atomicAnd
atomicCompSwap
atomicExchange
atomicMax
atomicMin
atomicOr
atomicXor
barrier
beginInvocationInterlockARB
bitCount
bitfieldReverse
clockRealtime2x32EXT
controlBarrier
cos
dFdx
dFdxCoarse
dFdxFine
dFdy
dFdyCoarse
dFdyFine
debugPrintfEXT
dot
endInvocationInterlockARB
exp
findLSB
findMSB
float16_t
floatBitsToInt
floatBitsToUint
fma
fract
hitObjectExecuteShaderNV
hitObjectGetAttributesNV
hitObjectGetGeometryIndexNV
hitObjectGetHitKindNV
hitObjectGetInstanceCustomIndexNV
hitObjectGetInstanceIdNV
hitObjectGetObjectRayDirectionNV
hitObjectGetObjectToWorldNV
hitObjectGetPrimitiveIndexNV
hitObjectGetRayTMaxNV
hitObjectGetRayTMinNV
hitObjectGetShaderBindingTableRecordIndexNV
hitObjectGetWorldRayDirectionNV
hitObjectGetWorldRayOriginNV
hitObjectGetWorldToObjectNV
hitObjectIsEmptyNV
hitObjectIsHitNV
hitObjectIsMissNV
hitObjectRecordEmptyNV
hitObjectRecordHitMotionNV
hitObjectRecordHitNV
hitObjectRecordHitWithIndexMotionNV
hitObjectRecordHitWithIndexNV
hitObjectRecordMissMotionNV
hitObjectRecordMissNV
hitObjectTraceRayMotionNV
hitObjectTraceRayNV
imageStore
intBitsToFloat
interpolateAtCentroid
interpolateAtOffset
interpolateAtSample
inversesqrt
isinf
isnan
lessThan
log
memoryBarrier
mix
mod
nonuniformEXT
not
packDouble2x32
packHalf2x16
rayQueryConfirmIntersectionEXT
rayQueryGenerateIntersectionEXT
rayQueryGetIntersectionBarycentricsEXT
rayQueryGetIntersectionCandidateAABBOpaqueEXT
rayQueryGetIntersectionFrontFaceEXT
rayQueryGetIntersectionGeometryIndexEXT
rayQueryGetIntersectionInstanceCustomIndexEXT
rayQueryGetIntersectionInstanceIdEXT
rayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetEXT
rayQueryGetIntersectionObjectRayDirectionEXT
rayQueryGetIntersectionObjectRayOriginEXT
rayQueryGetIntersectionObjectToWorldEXT
rayQueryGetIntersectionPrimitiveIndexEXT
rayQueryGetIntersectionTEXT
rayQueryGetIntersectionTypeEXT
rayQueryGetIntersectionWorldToObjectEXT
rayQueryGetRayFlagsEXT
rayQueryGetRayTMinEXT
rayQueryGetWorldRayDirectionEXT
rayQueryGetWorldRayOriginEXT
rayQueryInitializeEXT
rayQueryProceedEXT
rayQueryTerminateEXT
reorderThreadNV
sampler
sign
sin
someGLSLThing
subgroupAdd
subgroupAll
subgroupAllEqual
subgroupAnd
subgroupAny
subgroupBallot
subgroupBallotBitCount
subgroupBallotBitExtract
subgroupBallotExclusiveBitCount
subgroupBallotFindLSB
subgroupBallotFindMSB
subgroupBallotInclusiveBitCount
subgroupBarrier
subgroupBroadcast
subgroupBroadcastFirst
subgroupClusteredAdd
subgroupClusteredAnd
subgroupClusteredMax
subgroupClusteredMin
subgroupClusteredMul
subgroupClusteredOr
subgroupClusteredXor
subgroupElect
subgroupExclusiveAdd
subgroupExclusiveAnd
subgroupExclusiveMax
subgroupExclusiveMin
subgroupExclusiveMul
subgroupExclusiveOr
subgroupExclusiveXor
subgroupInclusiveAdd
subgroupInclusiveAnd
subgroupInclusiveMax
subgroupInclusiveMin
subgroupInclusiveMul
subgroupInclusiveOr
subgroupInclusiveXor
subgroupInverseBallot
subgroupMax
subgroupMemoryBarrier
subgroupMemoryBarrierBuffer
subgroupMemoryBarrierImage
subgroupMemoryBarrierShared
subgroupMin
subgroupMul
subgroupOr
subgroupPartitionNV
subgroupQuadBroadcast
subgroupQuadSwapDiagonal
subgroupQuadSwapHorizontal
subgroupQuadSwapVertical
subgroupShuffle
subgroupShuffleDown
subgroupShuffleUp
subgroupShuffleXor
subgroupXor
texture
textureFootprintClampNV
textureFootprintGradClampNV
textureFootprintGradNV
textureFootprintLodNV
textureFootprintNV
textureGather
textureGatherOffset
textureGatherOffsets
textureLod
textureLodOffset
textureOffset
textureQueryLod
traceRayMotionNV
transpose
uintBitsToFloat
unpackDouble2x32
unpackHalf2x16

And it also uses following 13 built-in variables:
gl_CurrentRayTimeNV
gl_GeometryIndexEXT
gl_HitTriangleVertexPositionsEXT
gl_InstanceID
gl_PrimitiveID
gl_ScopeDevice
gl_ScopeWorkgroup
gl_SemanticsAcquireRelease
gl_StorageSemanticsBuffer
gl_StorageSemanticsImage
gl_StorageSemanticsShared
gl_SubgroupInvocationID
gl_SubgroupSize

**Comment by jkwak-work** [comment]
Note for myself.
It appears that hlsl.meta.slang is mostly written in Slang syntax but it has C++ code embedded with keywords, "${{{{" and "}}}}".
It reminds me of how PHP allows us to write a text file mostly in HTML and it can also have PHP syntax within the file with keywords "<?php" and "?>".

**Comment by jkwak-work** [comment]
I found that most of syntax in hlsl.meta.slang is well explained in a document.
https://github.com/shader-slang/slang/blob/master/docs/user-guide/a1-04-interop.md
