### ISSUE TITLE
Make OptionKind::EmitSpirvDirectly turn ON by default for target CodeGenTarget target SPIRV 

### ISSUE THREAD

**Issue by pmistryNV** [shader-slang/slang#3477]
Blocked by:
- #3547
- Fix the perf issue exposed by #3547.
- #3440
- #3438 
- #3437

**Comment by natevm** [comment]
+1, emitting SPIRV directly seems to be the more robust path from my experience. I think it makes sense that this becomes the default.

**Comment by csyonghe** [comment]
Made direct edits in the original post to track dependent issues.

**Comment by csyonghe** [comment]
Now that we understand what is causing NV driver to take so long to consume our SPIRV, we can implement a fix to avoid generating that pattern.

**Comment by natevm** [comment]
Somewhat related, but if we switched direct-to-spirv on by default, then I could submit reproducers of bugs more easily through shader playground. Currently, shader playground uses the default glslang backend path.

**Comment by swoods-nv** [comment]
Q2-- let's not rush this transition.

**Comment by natevm** [comment]
This should be a high priority. The current direct-to-SPIRV backend is (from my experience) much more stable than with the option off. 

Even the more basic features like multiple entrypoints do not work without this flag. 

Why should we not just make this the default today? Are there any blocking issues preventing us from just flipping the switch?

**Comment by csyonghe** [comment]
We have users relying on some internal intrinsics that are only available on the glsl path. Switching now could break their code. We will implement the switch in early Q2.

**Comment by natevm** [comment]
We should add a “—emit-spirv-indirectly” flag then. I don’t see why this should be a blocking issue.

For internal Nvidia users working on confidential Vulkan features, they should be the ones with the burden to add a flag to their build system, not the other way around. 

Slang is cross vendor language, and if we want developers to believe that, we probably shouldn’t hold back features because <confidential Nvidia reasons>. 

In any case, there will always be internal intrinsics in glslang/glslc/dxc that aren’t yet implemented in Slang, so we need a very clear line here on what’s “good enough” to flip the switch.

**Comment by csyonghe** [comment]
I agree that most of our users will find the spirv backend to be far superior. However to flip the switch, we need to do some work around our CI and regression tests to ensure we don’t lose coverage for the glsl path. This will take some time so we probably won’t make the March deadline. We put this to Q2 so we don’t rush too hard for it, but it will be the first thing we do in April.
________________________________

**Comment by swoods-nv** [comment]
(Just to emphasize here-- Q2 is only two weeks away, so this isn't being pushed to the far future.)

**Comment by natevm** [comment]
Ah, right. Time seems to have escaped me a bit. Yes, that’s not far out at all. Sometime mid April seems reasonable.
