### ISSUE TITLE
Floats Zeroed out with no warning

### ISSUE THREAD

**Issue by half-potato** [shader-slang/slang#3490]
The following code will zero out TINY_VAL to 0, resulting in broken code.
```
#define TINY_VAL 1.1754944e-37

[TorchEntryPoint]
[Differentiable]
float safe_div(in float a, in float b) {
  if (abs(b) < TINY_VAL) {
    return a / TINY_VAL;
  } else {
    return a / b;
  }
}
```
```
>>> safe_math = slangpy.loadModule("safe-math.slang")
>>> safe_math.safe_div(5,1)
5.0
>>> safe_math.safe_div(5,0)
inf
>>> safe_math.safe_div(5,1e-37)
4.999999840142846e+37
>>> safe_math.safe_div(5,1.175e-37)
4.255319002099013e+37
```
Here is the generated code:
```
SLANG_PRELUDE_EXPORT
float safe_div(float a_0, float b_0)
{
    if((F32_abs((b_0))) < 0.0f)
    {
        return a_0 / 0.0f;
    }
    else
    {
        return a_0 / b_0;
    }
}
```

**Comment by jkwak-work** [comment]
I think there are two problems related to this issue.
First is on the fact that "precision" setting for the ostringstream is set too high.
It is currently set to 20 and I believe it should be set to 16 like following.
std::cout.precision(std::numeric_limits<double>::max_digits10 - 1); // 17 -1

Second problem is that there is a precision lose when a value is read as a "float" type.
I found this little surprising but the following codes returns different values.
```
std::cout.precision(std::numeric_limits<double>::max_digits10 - 1);

double d = 1.7e-37; // without "f" postfix
std::cout << d << '\n'; // 1.7e-37

double f = 1.7e-37f; // with "f" postfix.
std::cout << f << '\n'; // 1.700000029707435e-37
```

The binary representation of 1.7e-37 stored in double type is "0x384cec8b57852073"
The binary representation of 1.7e-37f stored in double type is "0x384cec8b60000000".

Since our Slang assumes all floating point values in the source file as a single precision float, I think there is a lose of the precision while reading it.

**Comment by jkwak-work** [comment]
I guess a simplest solution is to lower the number of digits down to how much float can store.
`std::cout.precision(std::numeric_limits<float>::max_digits10 - 1);`

**Comment by swoods-nv** [comment]
Moving this from Jay's plate to Kai's, since Jai has a couple of large Q1 things on his plate. Kai, can you take this one over when you are back?

**Comment by kaizhangNV** [comment]
Close the issue.
