### ISSUE TITLE
[Slang VK CTS] Integrate VK CTS with current Slang CICD infra and enable nightly testing

### ISSUE THREAD

**Issue by akolheNV** [shader-slang/slang#3512]

**Comment by akolheNV** [comment]
@pmistryNV will soon finish integration of SLANGC with VK CTS, followed by a sample run of the CTS to get baseline numbers. We expect it to be done by 2/9
 @ychenNV could you please assign this to someone. If this could be done by 2/9, then we can take the base pass list and enable it in nightly testing.

**Comment by dzysk** [comment]
Workflow action is ready to go with all expected passing tests passing. Before committing the change I'm looking into whether or not we can speed up the testing by running in parallel.

**Comment by dzysk** [comment]
The new workflow has been committed and is running nightly. We were unable to run in parallel currently because when using slang we see random failures. I created an issue for tracking: [https://github.com/shader-slang/slang/issues/3739](url) Once that is resolved we can update the workflow to add parallel processing.
