### ISSUE TITLE
Add support for bitfields

### ISSUE THREAD

**Issue by savage309** [shader-slang/slang#3559]
Using bit operations is a work around, but having bit fields will make it easier to pack data.

**Comment by natevm** [comment]
For what it's worth, HLSL describes their 2021 bitfields at the bottom of dev blog here: 

https://devblogs.microsoft.com/directx/announcing-hlsl-2021/

One application where I'd really like to have bitfields for is to directly support constructing certain Vulkan structures on the device like `VkAccelerationStructureInstanceKHR`, since then I can fill out my top level acceleration structures much faster. 

![image](https://github.com/shader-slang/slang/assets/13104331/ee2058b1-d8be-4b93-80d4-d69dffed477f)

Thanks for looking into this!
