### ISSUE TITLE
Using associatedtypes from global generic type parameter does not work

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#357]
```
//TEST(compute):COMPARE_COMPUTE:-xslang -use-ir
//TEST_INPUT:ubuffer(data=[0 0 0 0], stride=4):dxbinding(0),glbinding(0),out
//TEST_INPUT:type AssocImpl


RWStructuredBuffer<float> outputBuffer;

interface IBase
{
    float getVal();
};

interface IAssoc
{
    associatedtype TBase : IBase;
};

struct BaseImpl : IBase
{
    float getVal() { return 1.0; }
};

struct AssocImpl : IAssoc
{
    typedef BaseImpl TBase;
};

__generic_param T : IAssoc;


[numthreads(4, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    uint tid = dispatchThreadID.x;
    T.TBase base;
    float rs = base.getVal();
    outputBuffer[tid] = rs;
}
```
Output HLSL contains `FuncType = /*unhandled case*/`

**Comment by csyonghe** [comment]
Our current compiler is not working currently for this case, because we cannot currently substitute the witness table argument of the lookup_interface_method instruction for the `base.getVal()` call.

`base.getVal` currently translates to `lookup-interface-method(GenericTypeConstraintDecl{IAssoc::TBase::IBase}, "getVal")`.

After global generic type argument substitution, this first argument to `lookup-interface-method` should translate to the `IRWitnessTable` for `BaseImpl`, but unfortunately the ir translation pass has no sufficient info in order to get there.

Ideally, the IR for this call should be something like
```
w0 = lookup-interface-witness(witness_table(T:IAssoc), "TBase:IBase")
f = lookup-interface-method(w0, "getVal")
call(f, ...)
```
That is, we should treat the constraint of `associatedtype TBase:IBase` as an interface requirement of IAssoc. Then when we build the witness table for AssocImpl, the table will contain an entry that maps from `"TBase:IBase"` to `witness_table(BaseImpl:IBase)`. 

I think an easy way to think about this is that we should have an IR level operation called `ToType cast<FromType, ToType>(FromType val)`. Then when we compile `base.getVal()`, we would have
```
b1 = cast<T.TBase, IBase>(base)
f = lookup_interface_method(b1, "getVal")
call(f, ...)
```
When we specialize the code with T = AssocImpl, we get
```
b1 = cast<AssocImpl.TBase, IBase>(base)
f = lookup_interface_method(b1, "getVal")
call(f, ...)
```
which simplifies to 
```
b1 = cast<BaseImpl, IBase>(base)
f = lookup_interface_method(b1, "getVal")
call(f, ...)
```
At IR generation time, we also generate "evaluated" `cast` operation results for all known `struct` types, so somewhere in the dictionary we will have the mapping
"cast<BaseImpl, IBase>` ---> `witness_table(BaseImpl, IBase)`
Then we can just use this mapping to get the witness table we needed.

@tangent-vector I'd like to know your thoughts so we can agree on a solution here.

**Comment by csyonghe** [comment]
Thinking a bit on transitive subtypes, let's say we have
```
interface I2{ void method2(); }
interface I1 : I2 { void method1(); }
struct A : I1;
```
then `A.method2` should translate into
```
w1 = lookup_witness(A, I1);
w2 = lookup_witness(w1, I2);
f = lookup_interface_method(w2, "method2");
```
If we support a witness table entrie whose value is a witness table, this should just work.

My argument here is that we should have IR operations that returns witness tables, and it is not sufficient to only baking actual witness table values as immediate instruction arguments.

**Comment by tangent-vector** [comment]
> My argument here is that we should have IR operations that returns witness tables, and it is not sufficient to only baking actual witness table values as immediate instruction arguments.

I think I agree with you that we need an IR operation that looks up a witness table in another witness table (your `lookup_witness(w1, I2)` line). In fact, I'd claim that we should just generalize `lookup_interface_method` to `lookup(witnessTable, requirementDeclRef)`.

Where I'm less convinced is your first line: `lookup_witness(A, I1)`. I don't see why the IR needs to represent that as any kind of "lookup" process. The front end will have already filled in the `InheritanceDecl` for `{A : I1}`, and that declaration will lower directly to a concrete witness table, so let's just use that.

Similarly, in the case of `lookup_witness(w1, I2)`, I don't think it is correct to have the second operand there be the *interface* for which we are trying to look up conformance. The front-end will have already don the work of finding the `InheritanceDecl` that represents `{I1 : I2}`, so the second argument to the lookup operation should be a `DeclRef` to that conformance.

(Note that in that case, we have an `InheritanceDecl` that does *not* immediately translate into a witness table. The inheritance decls of an interface represent requirements (keys in a witness table) and not conformances.)

So my proposed IR for your example would look more like:

```
witness_table A_conforms_to_I2 {
    I2::method2 -> A::method2 // map required method decl ref to implementation IR func
}
witness_table A_conforms_to_I1 {
    I1::method1 -> A::method1,
    {I1 : I2} ->A_conforms_to_I2 // map required conformance to implementation IR witness table
}
...
w1 = lookup(A_conforms_to_I1, {I1 : I2})
f = lookup(w1, I2::method2)
```

This version of things keeps stuff simple: a witness table entry always maps a `DeclRef` for a requirement over to an `IRValue*` that satisfies the requirement (`InheritanceDecl` requirements are no different than methods). Similarly, a `lookup` operation always takes a witness table (or a value that will eventually specialize to a witness table) and a `DeclRef` for the requirement to look up. Specializing a `lookup` is always easy: if the first operand is a witness table, then it has better have a key for the second operand, and we can replace the `lookup` with the corresponding value.

This all comes down to how we lower a `SubtypeWitness` to an `IRValue`. In the case of a `DeclaredSubtypeWitness` this is easy: it is either a concrete witness table (in the concrete case) or a `DeclRefVal` for the underlying conformance/constraint.

In the case of a `TransitiveSubtypeWitness(A,B)` we basically want to lower `A` recursively, and then use `B` as a key to look up the final witness table in `A`. The way I've described this assumes that `B` must be a `DeclaredSubtypeWitness`, so it doesn't cover the general case, but conceptually it is clear that any `TransitiveSubtypeWitness` hierarchy is equivalent to a sequence of `DeclaredSubtypeWitness`.

I *think* the front-end is producing all the data you need here. The only key point I'm trying to hammer on here is that the front end is going to the trouble of constructing values that represent the conformance of a type to an interface for you, so I'd rather that the IR level doesn't throw that information away and construct anything like `lookup_witness(A, SomeInterface)`. If `A` conforms to `SomeInterface` then the front-end will have prooved it, so the IR should need to do any kind of "search" to re-discover that fact.

**Comment by csyonghe** [comment]
> Similarly, in the case of lookup_witness(w1, I2), I don't think it is correct to have the second operand there be the interface for which we are trying to look up conformance. The front-end will have already don the work of finding the InheritanceDecl that represents {I1 : I2}, so the second argument to the lookup operation should be a DeclRef to that conformance.

Well, in the case of an associated type, the decl for the second argument would be a `GenericTypeConstraintDecl` that belong to some `AssociatedTypeDecl` rather than an `InheritanceDecl`. So if you are using that decl to lookup in the witness table, you won't be able to find a matching entry. (In my `AssocImpl` example, `((T.TBase)base).getVal()`, the witness lookup in your proposal would be `lookup_witness(w0, DeclRef(IAssoc::TBase:IBase))`, where `w0` will eventually be `witness_table(BaseImpl:IBase), which will not contain an entry with the key `IAssoc::TBase:IBase`. That's why I think the key should be the interface type and not the decl representing conformance, because it is not unique.

**Comment by csyonghe** [comment]
As for my first point, since you won't be able to find the concrete witness table in a generic function, I think it is easier to think it as that an implicit cast to interface (or membering the constraint breadcrumb) always maps to `lookup_witness` instruction. If both sides of the lookup_witness are known, we then constant fold it into the concrete witness table. This is the same operation that we will apply when we specialize the code - filling the first parameter of `lookup_witness` to some concrete type, then we can replace the whole instruction with a conrete witness table. By doing this the front end (and IR gen) does not need to have different behaviors for accessing through a concrete type or generic type. We will resolve witness tables as an IR transform process as the code is being specialized.

**Comment by csyonghe** [comment]
I am trying to think through a more contrived case, let's say we have
```
interface IBase
{
    float getVal();
};

interface IAssoc
{
    associatedtype TBase : IBase;
};

struct BaseImpl : IBase
{
    float getVal() { return 1.0; }
};

struct AssocImpl<B:IBase> : IAssoc
{
    typedef B TBase;
};

void doSomething<T:IAssoc>()
{
    T.TBase b;
    b.getVal();
}

void main()
{
    doSomething<AssocImpl<BaseImpl> >();
}
```
What does `doSomething` translate into?
If we have `lookup_witness` instruction, the body of the generic `doSomething` function is still
```
w0 = lookup_witness(T, IAssoc);
w1 = lookup_witness(w0, IBase);
getVal = lookup_interface_method(w1, ")
call(getVal, ...)
```
When we specialize this function with `T=AssocImpl<BaseImpl>`, we will get
```
w0 = lookup_witness(AssocImpl<BaseImpl>, IAssoc);
1 = lookup_witness(w0, IBase);
getVal = lookup_interface_method(w1, ")
call(getVal, ...)
```
Now I am confused here how to jump from `AssocImpl<BaseImpl>` to the witness table for this specialized `struct`.
(This is a big hole in my understanding of how the compiler handles type specialization.)
But once we've done that, we should be able to fold `w0` into `witness_table(BaseImpl:IBase)`, and everything from there should
just work as I previously described.

Perhaps I didn't get your idea very correctly, so it would be great if you can show me in this example what the second argument to 
`lookup_witness` should be and how everything transforms in each step.

**Comment by tangent-vector** [comment]
Your response definitely made me realize I'd been missing some details around associated types. I still think the mental model I have works fine, but there is some implementation work to be done for associated types.

We currently have two declaration types to represent subtyping relationships (`InheritanceDecl` and `GenericTypeConstraintDecl`). In general, I write references to these kinds of declarations in the form `{A : B}` where `A` is the sub type and `B` is the super-type, because otherwise it is hard to precisely identify them. While there are two types of declarations, there are actually several different cases that arise from how they are used in practice:

1. An `InheritanceDecl` on a concrete type, like `struct C : IFoo`. This is the way the programmer *asserts* that their type conforms to the interface, and the compiler front-end responds by checking that `C` provides everything `IFoo` requires. These declarations translate to witness tables in the IR (using the declarations the front-end found to satsify requirements).

2. A `GenericTypeConstraintDecl` on a type/function/whatever. This effectively represents a witness-table-typed *parameter* to the construct in question. In the IR, there will be references to these (as `IRDeclRef` values), to serve as placeholders for where a concrete witness-table value will appear later. These had better all go away by the time specialization is done.

3. An `InheritanceDecl` on an interface type, like `interface IDerived : IBase`. Just like any other member declaration in an `interface`, this represents a *requirement* that types conforming to the interface must satisfy. Because these declarations are interface requirements, that means that they are used as *keys* to look up entries in witness tables.

4. An `InheritanceDecl` on an associated type declaration, like `associatedtype Product : IFoo` is another case of an interface requirement (it is a requirement of the interface that contains the associated type declaration).

There are several big things there that our current implementation doesn't handle, so of course some of this stuff doesn't work.

### Transitive Inheritance

Starting with the easiest (since we've already talked about it): case (3) above means that when any concrete type implements an interface, and that interface also inherits from another interface (so `struct C : IDerived` and `interface IDerived : IBase`) then:

- When the front-end checks that `C : IDerived` it needs to find a suitable declaration to satisfy each requirement in `IDerived`. One of these requirements is `IDerived : IBase`. If `C` doesn't already have an inheritance decl `{C: IBase}`, then the front-end should construct one, add it to `C`, and then use that declaration to satisfy the requirement. (It should also go on to validate the inheritance decl it just added, of course). We don't do this step today!

- Once the front-end has done the work above, it is clear that the IR generation will generate two witness tables: one for `{C : IDerived}` and one for `{C : IBase}`. The `{C:IDerived}` witness table will have one entry for each requirement in `IDerived`. One of those requirements is `{IDerived:IBase}` (which was satisfied by `{C:IBase}`, so we will have a witness-table entry where `{IDerived:IBase}` is the key, and the witness table for `{C:IBase}` is the value.

- There is no risk of the keys into such a witness table being wrong (if we implement the above correctly). Given an arbitrary type `Foo` that is known to implement `IDerived`, if you hand me the witness table that represents the conformance of `Foo` to `IDerived`, then I know there will be an entry with the key `{IDerived:IBase}` (note that there is no reference to `Foo` in the key), and the value for that key will be a witness table for the conformance of `Foo` to `IBase`.

### Associated Types with Constraints

Item (4) on my list is actually really similar to (3). Suppose I have:

```
interface ISidekick {}
interface IHero { associatedtype S : ISidekick; }

struct Robin : ISidekick {}
struct Batman : IHero { typedef Robin Sidekick; }
```

The `IHero` interface has two requirements: the associated type `S` and the inheritance requirement `{S : ISidekick}`. Associated type requirements don't currently show up in IR-level witness tables, but inheritance requirements need to.

That means that for the `Batman` type, we need to construct a witness table for `Batman : IHero` and that witness table needs to have an entry with the key `{S : ISidekick}` (one of the requirements in `IHero`). The value for that key should be the witness table corresponding to `Robin : ISidekick`.

This means that when the front-end is doing interface conformance checks, when checking conformance of `Batman` to `IHero` it needs to not only find a declaration to satisfy the `associatedtype S` requirement, but also one for the `{S : ISidekick}` requirement (that needs to be a reference to the `Robin : ISidekick` declaration). The front-end currently doesn't do this.

One other weird bit there: right now the front-end logic assumes that interface conformance checks (and the data structure it builds) is about mapping from a `DeclRef` for the interface requirement to a plain old `Decl*` representing the member that satisfies the requirement. That is because so far requirements have always been satisfied using members directly nested in the type itself, so there was never a case where they needed to be qualified/specialized. A type constrain on an associated type adds a new wrinkle, in that the declaration satisfying a requirement might belong to a different parent declaration, so we probably want a full `DeclRef` (at the very least - more on that in a second).

What this means at the IR generation level is that at the point where we are about to make use of the fact that some associated type (`S`) implements an interface (`ISidekick`), we'll need to `lookup` its witness table in witness table for the outer type that contains the associated type (`H : IHero`).

As above, though, the key for that lookup is consistent. The key is *always* `{S : ISidekick}` in my example. There is never a chance of getting the wrong table there.

(To dig in a bit in case things aren't clear: substitution is only ever going to replace references to a `GenericTypeConstraintDecl`, because it only replaces generic *parameters* with their *arguments*. The declarations I'm talking about as keys here are all `InheritanceDecl`s, and they will never get substituted away. That is a feature, not a bug, in this case.)

### Generics That Implement Interfaces

Now the rubber hits the road. As soon as we have generic types implementing interfaces (and your example does just that), we need to start dealing with *generic witness tables*.

The first step is obviously to allow an IR witness table to have generic parameters in the same way an IR function can. In fact, I'd say this is a good time to go ahead and allow every `IRGlobalValue` to have a `DeclRef` to the declaration it represents (this might be null for any values that are created by optimization/transformation). In the case where we specialize an IR decl, we should also specialize the corresponding `DeclRef`.

Once we have generic witness tables, we also need a way to specialize them. I suspect that these will need to be specialized on demand (and cached/reused based on their mangled names) rather than with explicit `specialize` instructions, but we will probably discover the right answer during implementation.

Importantly, when we go to specialize a generic (whether a generic function or a generic witness table), the generic *arguments* being used for specialization should only contain fully-specialized witness tables (because we don't support higher-order generics).

In your `struct AssocImpl<B:IBase> : IAssoc` example, the inheritance decl `{AssocImpl<...> : IAssoc}` would need to lower to an IR witness table, and that IR witness table would need to have generic parameters corresponding to the generic type parameter `B` and the generic type constraint parameter `{B : IBase}` (just like the IR function for a method in `AssocImpl` would have these parameters).

### The Example Program

Looking at your example program, I'd imagine a transformation into IR something like:

```
// concrete implementation of `BaseImpl.getVal`
func @BaseImpl_getVal { ... }

// witness table for `{BaseImpl : IBase}`
witness_table @BaseImpl_is_IBase 
{
    DeclRef(IBase.getVal) -> @BaseImpl_getVal
}

// witness table for `{AssocImpl<...> : IAssoc}`
// note the generic parameters!
witness_table @AssocImpl_is_IAssoc<B, {B:IBase}>
{
    // We need a witness table entry for the `TBase : IBase` requirement (that is the key)
    // In this case, the value for the key needs to be `B : IBase` (the generic type parameter constraint)
    DeclRef(TBase : IBase) -> DeclRef(B : IBase)
}

// the generic `doSomething` function
func doSomething<T, {T:IAssoc}>
{
    T.TBase b;

    // In order to call `b.getVal` we first need to get the witness
    // table that shows that `T.TBase : IBase`. Luckily, we know that
    // there will be an entry that satisfies that requirement in any
    // witness table for a type implementing `IAssoc`.
    w = lookup( {T:IAssoc}, {TBase:IBase} )

    // Now we have the witness table we need as `w`, and we can
    // look up the function we want like normal and call it.
    f = lookup( w, {IBase.getVal} )
    f(b);
}
```

The call to `doSomething<AssocImpl<BaseImpl>>` is going to trigger some specialization.

First, when we encounter the concrete type `AssocImpl<BaseImpl>`, we'll want to specialize any generic witness tables for `AssocImpl<...>`.

As a reminder, `AssocImpl<BaseImpl>` is expanded by the front-end into `AssocImpl<BaseImpl,
 {BaseImpl : IBase}>` and the IR can turn that into the arguments `<BaseImpl, @BaseImpl_is_IBase>`

So we are going to take the parameters `<B, {B:IBase}>` of our generic witness table, and map `B` to `BaseImpl` and `{B:IBase}` to `@BaseImpl_is_IBase`:

```
witness_table @AssocImpl_is_IAssoc_SPECIALIZED
{
    DeclRef(TBase : IBase) -> @BaseImpl_is_IBase
}
```

What do you know? Applying substitutions to the witness table above gave us an entry with exactly the witness table we wanted for our concrete associated type. Again, note that the *key* here didn't change, because it didn't reference our generic parameters.

Now that we've done that step, we can see that our call to `doSomething<AssocImpl<BaseImpl>>` is actually expanded by the front-end into `doSomething<AssocImpl<BaseImpl>, {AssocImpl<BaseImpl> : IAssoc}>`, and again we can map the specialized `InheritanceDecl` from the front end over to the specialized witness table in the IR to get `<AssocImpl<BaseImpl>, @AssocImpl_is_IAssoc_SPECIALIZED>`.

Now we specialize `doSomething` with `T` mapping to `AssocImpl<BaseImpl>` and `{T : IAssoc}` mapping to `@AssocImpl_is_IAssoc_SPECIALIZED`, and we get:

```
func doSomething_SPECIALIZED
{
    BaseImpl b; // I'm not dealing with how to specialize this bit right...

    w = lookup( @AssocImpl_is_IAssoc_SPECIALIZED, {TBase:IBase} )
    f = lookup( w, {IBase.getVal} )
    f(b);
}
```

The `lookup( @AssocImpl_is_IAssoc_SPECIALIZED, {TBase:IBase} )` operation has a concrete witness table as the first argument now, so we will go look in that table for an entry matching the key `{TBase : IBase}` and it turns out to have one, with the value `@BaseImpl_is_IBase`. Great! We will use that to replace `w`.

After that step, we the `lookup(w, {IBase.getVal})` becomes `lookup(@BaseImpl_is_IBase, {IBase.getVal})`, and we've got another concrete witness table. That table has an entry for `{IBase.getVal}` just like we want, and the value for that key is `@BaseImpl_getVal`, which is the concrete IR function we wanted to call all along.

It all seems to work to me, even if there is a fair bit of work we have to do to get there.

**Comment by tangent-vector** [comment]
To follow up on one detail that I neglected to come back to, even after saying "more on that in a second":

Thinking about it, I can imagine cases where when the front-end goes to check interface conformance, that the only way it can satisfy a constraint on an associated type is using a `TransitiveSubtypeWitness`:

```
interface IBase { ... }
interface IDerived : IBase { ... }
interface IOuter { associatedtype A : IBase }

struct Tricky<T : IDerived> { typedef T A; }
```

In this case, we know that `T` can be used for `A` because `T : IDerived` and `IDerived : IBase`. That means the front end can find a value to satisfy the `A : IBase` requirement, but that value would be a `TransitiveSubtypeWitness`. That seesm to imply that the representation of witness tables in the front end needs to be more complex (right now it just maps from requirement `DeclRef`s to satifying `Decl`s).

An even more complex example would be:

```
interface IProduct { ... }
interface IFactory { associatedtype Makes : IProduct; }
interface IStore { associatedtype Sells : IProduct; }

// Define a store that sells whatever a particular factory makes
struct OutletStore<F:IFactory> : IStore { typedef F.Makes Sells; }
```

In this example we don't have any inheritance, but it is still a bit tricky for the front-end to construct the proof that `OutletStore<F>.Sells` implements `IProduct`. If we think of this as a lookup process, we start with the concrete declaration `{F:IFactory}`, and then we look up its `{Makes : IProduct}` member.

Note that we can't just use the `{Makes : IProduct}` declaration to satisfy the interface requirement directly, because there is no way for subsequent specialization to replace it. That is, when we specialize the witness table for `OutputStore<F, {F:IFactory}>` we are going to have some concrete type `C`, and a witness table for `{C:IFactory}` that we'll plug in. We'll replace any references to `{F:IFactory}`, so *that* needs to be the start of the chain.

What we want is a subtype witness that represents the process: "start with {F:IFactory} and then look up its `{Makes : IProduct}` member, and that proves that `F.Makes` is a subtype of `IProduct`. If you then substitute in `C` for `F` and `{C:IFactory}` for `{F:IFactory}` that seems to work.

That isn't quite a `TransitiveSubtypeWitness` but it is similar in spirit.

The `TransitiveSubtypeWitness` case says that given `{A : B}` and `{B : C}` we can prove that `A` is a subtype of `B`.

This new case says that given `{A : B}` and `{B.C : D}` we can conclude that `A.C` is a subtype of `D`.

In either case, I have to conclude that the front-end should probably be finding `SubtypeWitness` values to satisfy interface requirements (rather than just `Decl`s or `DeclRef`s), if it will need to handle these more complex cases down the line.

Aside: just to be clear, the transitive case at the start of the message is intentionally written to use a generic type parameter `T : IDerived` rather than working with a concrete type, because it is easy for us to claim that a concrete type `struct C : IDerived` should be expanded to also have a `{C : IBase}` member by the front-end, but the equivalent transformation for generic parameters/arguments seems harder to justify (because it bloats the parameter/argument lists). We might have to consider it if the alternatives don't work, though.
