### ISSUE TITLE
Implement miscellaneous GLSL functions to match to how much HLSL side works

### ISSUE THREAD

**Issue by jkwak-work** [shader-slang/slang#3692]
There are GLSL functions described in [OpenGL Spec](https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.pdf) from a section 8.14 to 8.19.
Some of them may not have a HLSL counter part but we will need to implement as many as we can.

This is also a part of [the other umbrella task](https://github.com/shader-slang/slang/issues/3362).

Following functions are in those sections:

Section 8.14. Fragment Processing Functions
genFType dFdx(genFType p)
genFType dFdy(genFType p)
genFType dFdxFine(genFType p)
genFType dFdyFine(genFType p)
genFType dFdxCoarse(genFType p)
genFType dFdyCoarse(genFType p)
genFType fwidth(genFType p)
genFType fwidthFine(genFType p)
genFType fwidthCoarse(genFType p)
float interpolateAtCentroid(float interpolant)
vec2 interpolateAtCentroid(vec2 interpolant)
vec3 interpolateAtCentroid(vec3 interpolant)
vec4 interpolateAtCentroid(vec4 interpolant)
float interpolateAtSample(float interpolant, int sample)
vec2 interpolateAtSample(vec2 interpolant, int sample)
vec3 interpolateAtSample(vec3 interpolant, int sample)
vec4 interpolateAtSample(vec4 interpolant, int sample)
float interpolateAtOffset(float interpolant, vec2 offset)
vec2 interpolateAtOffset(vec2 interpolant, vec2 offset)
vec3 interpolateAtOffset(vec3 interpolant, vec2 offset)
vec4 interpolateAtOffset(vec4 interpolant, vec2 offset)

Section 8.15. Noise Functions
float noise1(genFType x) 
vec2 noise2(genFType x)
vec3 noise3(genFType x)
vec4 noise4(genFType x)

Section 8.16. Shader Invocation Control Functions
void barrier()

Section 8.17. Shader Memory Control Functions
void memoryBarrier()
void memoryBarrierAtomicCounter()
void memoryBarrierBuffer()
void memoryBarrierShared()
void memoryBarrierImage()
void groupMemoryBarrier()

Section 8.18. Subpass-Input Functions
gvec4 subpassLoad(gsubpassInput subpass)
gvec4 subpassLoad(gsubpassInputMS subpass, int sample)

Section 8.19. Shader Invocation Group Functions
bool anyInvocation(bool value)
bool allInvocations(bool value)
bool allInvocationsEqual(bool value)

**Comment by ArielG-NV** [comment]
update to issue:

Many functions invocation-group & invocation-control functions are partially removed from vulkan or deprecated (for a number of years). These functions use alternative methods of implementation to ensure they function at a minimum level of standard of 'working as expected'

 noise functions are fully deprecated.
 
 subpass images are missing an implementation in Slang, these were added
 
shader-memory-control functions are mostly working from GLSL->Vulkan, `memoryBarrierAtomicCounter()` is 'removed', although  due to including atomic_counter (GL_EXT_vulkan_glsl_relaxed compiler extension), the function is kept and wrapped as a `memoryBarrierBuffer()` to exhibit equivalent functionality

Fragment Processing should be fully working.

Geometry shader functionality as a whole is unimplemented and will need to be added (this is part of the todo list of this issue)

**Comment by ArielG-NV** [comment]
geometry shader related content will be moved to #3363
