### ISSUE TITLE
Type legalization not implemented for non-trivial this/inout parameters and return types

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#374]
This is currently preventing area light shader from being compiled.

**Comment by tfoleyNV** [comment]
From your email I gather that the problem here is cases where we might have an `inout` parameter (or return) that includes resources:

```hlsl
struct A { Texture2D f; };
void foo(inout A p);
```

I had thought that type legalization was handling cases like this, because the `inout A` effectively because a pointer type `InOut<A>`, and type legalization on a pointer type will legalize the pointed-to type (in this case it will become a tuple) and then wraps each "leaf" element in a pointer as well, so that we get a tuple like `(InOut<Texture2D>)`. I'd need to jump into the debugger to confirm whether any of that is working correctly right now.

The bigger problem, though, is that I'm not sure we want to support resource types as `out` or `inout` parameters any time soon. I'm also not clear on why we'd need this support. The same argument applies to return types that include resources. These can *possibly* be compiled to HLSL (assuming the HLSL compiler inlines things and solves the dataflow), but they certainly can't be made to work for Vulkan until we start implementing some serious dataflow optimizations ourselves.

**Comment by csyonghe** [comment]
This means that I can’t put any methods in a struct that has textures? Because once I do that, the type for this parameter would need to be lowered.
Anyway, that is not the most urgent thing right now, because I can workaround it by defining global parameters.

The reason I was using this feature is that I put 
```
struct AreaLightGlobalParams
{
    Texture2D ltc_mag, ltc_mat;
    SamplerState sampler;
};
``` 
As an additional field in `LightEnv`. 
But since the global parameter block for `LightEnv` is defined in `ShaderCommon.slang`, the rest of shading logic expects that user shader code pass in an instance of AreaLightGlobalParams via a function parameter. However doing that would require me adding an additional AreaLightGlobalParams parameter all over the place, so I decided to make AreaLightGlobalParams also a field of `LightAttribs` and write to it in `prepareLightAttribs`. That means the function is returning a new `LightAttribs` that is no longer trivial.

I also seem to have legalization problems when I define any methods in the `AreaLightGlobalParams` struct, I guess that is because `this` is lowered as an `inout` parameter?

**Comment by csyonghe** [comment]
I tried to create a separate case for `this` parameter being a mixed type and it seemed to work just fine. So maybe `this` is not the issue here.

**Comment by tfoleyNV** [comment]
I'm surprised that we had to special-case a `this` parameter at all, since at the IR level it is like any other parameter.

Oh wait, do we currently make the `this` parameter implicitly be `inout`? if we do, then we should probably change that so that the default is to make a `this` parameter always be `in`, since that is the 99% case for what we want in shader code. If we need to support `inout this` we can add that with a distinct modifier (e.g., the equivalent of the `mutating` modifier in Swift).

**Comment by csyonghe** [comment]
Fixed.
