### ISSUE TITLE
Code generation is incorrect with impure functions due to optimization pass

### ISSUE THREAD

**Issue by ArielG-NV** [shader-slang/slang#3746]
The first call to `simplifyIR` (after `lowerLValueCast` in `linkAndOptimizeIR`) simplifies functions which are impure and have side effects in the body (and not the arguments). It is likely all `simplifyIR` calls exhibit this behavior.

edit:
This issue is due to incorrect checking in `isPureFunctionalCall` 

example case:
```glsl
//TEST(compute, vulkan):COMPARE_COMPUTE(filecheck-buffer=BUF):-vk -compute -entry computeMain -allow-glsl
//TEST(compute, vulkan):COMPARE_COMPUTE(filecheck-buffer=BUF):-vk -compute -entry computeMain -allow-glsl -emit-spirv-directly
#version 430
precision highp float;
precision highp int;

//TEST_INPUT:ubuffer(data=[0], stride=4):out,name=outputBuffer
buffer MyBlockName2
{
    uint data[1];
} outputBuffer;

layout(local_size_x = 4) in;

void sideEffectInit(int val)
{
    outputBuffer.data[0] = val;
}
void computeMain()
{
    outputBuffer.data[0] = 1000;
    sideEffectInit(4);
    // BUF: 4
}
```

this compiles `computeMain` currently into:
```
void computeMain()
{
    outputBuffer.data[0] = 1000;
}
```

computeMain should instead compile effectively into:
```
void computeMain()
{
    outputBuffer.data[0] = 1000;
    sideEffectInit(4);
}
```

**Comment by csyonghe** [comment]
`isPureFunctionCall` looks for the `IRReadNoneDecoration` on the callee, which is propagated during `propagateFuncProperties`.

`propagateFuncProperties` does check for the body of the function for any side effects.

In this case I suspect the root cause is that the stores into a GLSL storage buffer isn't counted as having global side effect for some reason. Need to debug into `propagateFuncPropertiesImpl` to see why it decides the function has no side effect.
