### ISSUE TITLE
Register re-use between shader stages with different layouts.

### ISSUE THREAD

**Issue by ashwinNV** [shader-slang/slang#38]
I'm reusing a register between two shader stages, with different layouts and names, 
Is this supposed to be an error? 

[VS.vs.txt](https://github.com/shader-slang/slang/files/1089719/VS.vs.txt)
[PS.ps.txt](https://github.com/shader-slang/slang/files/1089718/PS.ps.txt)

**Comment by tfoleyNV** [comment]
Assuming the two files are being passed together in the same "compile request" the intended behavior (not yet implemented) is:

- Two parameters with different names, but the same register is allowed (even in the same file) but should probably warn. It is up to the user to do something sensible with the result, because my reflection data will expose both parameters.

- Two parameters with the *same* name, but in different "translation units" (files), and with different layout and/or register assignment will generate an error.

Note that this kind of issue is only likely to come up when compiling from multiple files (one file per entry point) instead of a single file with multiple entry points. The latter is the preferred style for Slang, and is probably the most familiar to HLSL users.

**Comment by tfoleyNV** [comment]
The basic behavior that was requested was implemented in #93, just with a warning instead of an error in the first of the two cases:

- If two parameters have different names, but use the same register, we report an error

- If two declarations of the "same" parameter (same name for now) try to bind to different registers, then we report an error

There's still some work to be done here:

1. I probably need a test case for this
2. I probably need to make the first case a warning
