### ISSUE TITLE
add & as an alias for inout in function signatures

### ISSUE THREAD

**Issue by fknfilewalker** [shader-slang/slang#3823]
Allow to write `inout float x` as `float& x` in function signatures. This would make it easier to share code between c++ and slang.
Additionally `const inout float x` could also be written as `const float& x`

Example: instead of writing
```c++ 
void foo(inout float x);
void bar(const inout float x);
```
one could also write
```c++ 
void foo(float& x);
void bar(const float& x);
```

**Comment by csyonghe** [comment]
Please note that C++ & has a different semantics to inout, and represents a direction that we do not want to pursue in Slang.

The C++ reference is a true pointer or address. HLSL inout means copy in, copy out, or at least the user shouldn't be relying on any differences between pointer reference or the value copying semantics. Because Slang needs to target platforms that does not support pointers and because many language features rely on pointer-less code to work, we have decided to intentionally not allow reference types in user code.

While we try to not diverge from c++ syntax if we can, this is one of the cases that we believe the c++ equivalent idea being at odds with high performance, cross platform shader programming.
