### ISSUE TITLE
CUDA kernel vs compute shader approach

### ISSUE THREAD

**Issue by aroidzap** [shader-slang/slang#3853]
Hello, I would like to know, which approach should I use. There is a) `[shader("compute")]` b) `[CudaKernel]`. Both have a bit different API, `[CudaKernel]` can be used with `TensorView` and `[shader("compute")]` can be probably used only with a global context and `StructuredBuffer`. Are both of these approaches going to be supported in a long-term? If not, which is the right one to choose? 
Also, is there a possibility to generage header files for C++/CUDA when using `slangc` only? Without headers, it becomes a bit messy - but i suppose original idea was to use it with Slang runtime. If there is a PR for header files targets support (i.e. `-target cpp-header`, `-target cuda-header`, `-target torch-binding-header`), could this be supported in a long-term, or this is not aligned with the Slang's vision? 
If this is not the way to go, what would be the future of torch-binding target? _I also see, that slang-python is no longer updated._

**Comment by csyonghe** [comment]
If you write code that intend to target cuda only, then `[CudaKernel]` is the more direct and easier approach without the kludge of wrapping compute shaders as a cuda kernel.
We intend to support both techniques.

Our team had discussions about producing headers as targets, and I agree with you that it is needed for easier code interop. This will be supported in our long term roadmap, but we haven't planned any short term work on this yet.

We weren't updating `slangpy` as frequently as we do for slang releases because most of the release here doesn't affect the autodiff behavior. We intend to continue supporting slangpy.
