### ISSUE TITLE
Handling "non-first-class" types

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#397]
As I'm working on making the IR the only codegen path, I'm running into cases that generate texture-type local variables in output code. This is the byproduct of a few rules:

- The way we handle GLSL output is by allowing the stdlib functions to have full definitions for a chosen target, so the `Texture2D<T>.Sample(...)` operation will have a full body that calls the GLSL `texture(...)` function.
- Our codegen for parameters needs to deal with the possibility that they will be written to like local variables, so we always copy them into temporaries at the start of every function

As a result, the generated IR for the `Texture2D<T>.Sample(...)` function starts out by declaring a variable of type `texture2d` and then assigning to it.

There are a few ways we could handle this:

1. Change the way that we deal with cross-compilation so that we don't rely on actual definitions of operations like `Texture2D<T>.Sample(...)`. E.g., we could special-case this as an IR instruction.

    * This isn't really appealing because it requires hard-coded C++ logic for a bunch of different operations, and thus can't be easily extended to new operations down the road. Given who our users are, we want to make it easy for them to define new operations with new mappings to different targets (GLSL, SPIR-V, etc.)

2. Change the way that we generate the initial IR to avoid these local variables. In principle we could just declare the function parameters as `const` and then special-case the codegen for `const` variables.

    * This is annoying because we'd have to audit all these stdlib definition to make sure they use `const` as needed, and it doesn't relaly solve the general case of HLSL that uses `Texture2D` temporaries.

3. Implement enough optimization steps in the IR that we can elminate these temporaries, and also have a roadmap for how to issue error messages in the cases where we *can't* eliminate them.

    * I'm obviously setting this one up to be the Right Way of handling things, but I hadn't really anticipated that it might be required so soon.

**Comment by tfoleyNV** [comment]
I’ve been thinking about the work involved in adding an SSA-generation pass. There are two main approaches that I’m aware of:

1. The traditional approach from Cytron et al. involves first generating code with temporaries (“allocas” for an LLVM-minded folks), then generating a dominator tree and computing dominance frontiers to figure out where phi nodes need to be placed.

2. The Braun et al. approach avoids the need for dominator information by working through the program in order, and defining a recursive (but memorized) operation for looking up the value of a variable in the context of a given block. This algorithm may temporarily insert phis that later get removed because they are trivial, but it is simpler to code because it doesn’t rely on other data structures. It is also amenable to being run during code generation from an AST.

I’m leaning toward approach (2) right now for the simplicity, although I think we’d still generate code with local variables first, and then optimize, since we’ll need to re-run this kind of optimization after specialization and type legalization anyway.

One question to answer is whether the current “blocks with parameters” approach will be viable or if we’ll need to switch to traditional phi nodes. An important point is that the “block with parameters” thing pretty much assumes there are no critical edges, so that any block that might need phis (and thus has multiple predecessors) would always be branched to with unconditional branches (so that tacking on an argument list is easy). Breaking critical edges should be easy enough, so long as it doesn’t mess up our structured control flow representation.

An even more annoying big-picture issue is what to do when a generic function uses a value of generic type in a way that is okay for simple types, but would lead to errors with resource types. Should that be a front-end error somehow? Is it okay if they get a compilation error after specialization? For now I might say we treat it as a target-specific limitation that certain types aren’t first-class, but that is unsatisfying.

**Comment by tfoleyNV** [comment]
As expected, #399 avoids this problem for our builtin functions, and #400 adding a proper SSA pass also eliminates some cases where we would otherwise have a texture-type local.

We still need to issue errors when things don’t follow the rules, and also re-run optimizations after specialization and type legalization. I don’t think it is time to close this just yet.

**Comment by tfoleyNV** [comment]
I'm changing the title of this issue to reflect the fact that there is something more fundamental here than just texture-type locals.

Basically, shading language users have gotten used to the fact that certain built-in types in these languages are not first class. There are two main categories of non-first-class-ness that I know of, and which one (if any) applies to a type is sometimes target-dependent:

* In the extreme case, it might be required that for any call site to a builtin operation taking a texture, the texture to be used can be identified (by the compiler) exactly. E.g., we know the user wants `gMaterial.layers[1].diffuseMap`.

* The the slightly more general case, we might require that the compiler can identify which texture or texture *array* the value comes from, but the array indices can be dynamic (although there might be constraints that require indices to be `uniform`). E.g., we know the user wants `gMaterialLayers[someIndex].diffuseMap`, but we don't care what `someIndex` is, statically.

So that gives us at least three levels of first-class-ness (including "actually first-class"). Most builtin types (scalars, vectors, matrices, etc.) will be "actually first-class," while resource types will have a less-than-first-class level for most targets.

Aggregate types probably need to have a first-class-ness level that is based on their worst-case field. Either that or any analysis we do would be required to scalarize such types just to be safe.

In the context of a single function, the front-end would need to ensure that there are no local variables of non-first-class type (after the "mandatory" SSA optimizations). In the fully restricted case, we'd also need to rule out any phi operations on non-first-class types, while in the case that allows indexing we'd need to detect that all of the values flowing into a phi represent the same base array, just with different indices. (And then we'd have to go and rewrite the code so that we have a phi over the indices instead of over the array elements, and move the indexing into each consumer block)

A few of the challenges I can see here are:

* How should we deal with the target-dependence of the restrictions? It seems like the ideal answer would be to compute the level of first-class-ness that a function requires, and then restrict it to targets that support that level of first-class-ness. This could lead to a warning if the user hasn't applied such a restriction manually, and an error if they have specified a target that doesn't provide the required level of first-class-ness.

* What do we do about generic type parameters? When compiling a generic function, should we be free to assume that the type parameters all represent true first-class types? Should the compiler assume they *might* be non-first-class, and apply the appropriate restrictions?

    * Note: the Rust compiler (and eventually Swift once it adds ownership) have a notion that generic type parameters are copyable and sized by default, and require users to add additional syntax for cases where they don't want to apply these default assumptions. We could conceivably do the same, just with a question of what the right default should be.

* Do we need to be more aggressive about handling aggregates with resources in them, by scalarizing them sooner and applying these optimizations to the result? The main challenge there is that legalization has so far been assumed to be a target-specific (or at least *potentially* target-specific) step, so we can't go and split up types in the front-end IR passes. We could conceivably scalarize aggregate types within each function, but still pass them as aggregates between functions, but that gets messy around things like arrays.

**Comment by tfoleyNV** [comment]
I just now realized that if/when we start adding in support for existential types, they'd be another example of a "non-first-class" type, in the more restricted case (e.g., an array of existentials can really only support compile-time-constant indexing).

Handling return values (and `out` parameters) of these types is another sticking point, and seems like it would share a lot of logic with the handling of constant parameters (we'd need to specialize the code and discover what it *actually* returns at all return sites).
