### ISSUE TITLE
Accessing pointer of structs containing large arrays leads to long compilation times

### ISSUE THREAD

**Issue by dubiousconst282** [shader-slang/slang#4038]
Compiling the following snippet takes around 15 seconds and the process allocates over 2GB of memory, growing proportionally to the array sizes. This seems to be specific to the SPIRV target and does not happen with HLSL (although I'm aware it doesn't support pointers).

```hlsl
// slangc -target spirv -emit-spirv-directly -profile glsl_460 -lang slang -O3 test2.slang
struct WorkData {
    float A[2048 * 2048];
    float B[2048 * 2048];
};
struct PushData {
    WorkData* Input;
    float* Dest;
};

[vk::push_constant] ConstantBuffer<PushData> cb;

[numthreads(64, 1, 1)]
void ComputeMain(uint tid: SV_DispatchThreadID)
{
    cb.Dest[tid] = cb.Input->A[tid] * cb.Input->B[tid];
}
```

**Comment by csyonghe** [comment]
I suspect the problem here is that spirv tools isn't designed to work with large arrays as SSA values.

To fix the problem, we need to not generate spirv code that is heavy on SSA registers for composite values.

We can have two separate passes to transform our IR where struct and arrays are passed via ssa values into pass by pointers to struct or arrays, and rewrite all ElementExtract into GetElementPointers.

Next, we need a pass to specialize all function calls by the address space of the arguments.

With these two transformations, we can generate spirv code that is free of ssa array and struct, which seems to be what spirv tools is designed to work with.

**Comment by csyonghe** [comment]
In general, using large arrays anywhere in the shader code is likely going to cause both/either compiler and runtime performance issues. Consider using `StructuredBuffer<T>` or just `T*` instead of large arrays.

When the following code with DXC, I noticed similar behavior of long compile times and large memory usage:
```
struct WorkData
{
    float A[2048* 2048];
    float B[2048* 2048];
    
    float Foo(uint i) { return A[i] * B[i]; }
};

ConstantBuffer<WorkData> input;

RWStructuredBuffer<float> resultBuffer;

[numthreads(2, 1, 1)]
void computeMain(uint tid: SV_DispatchThreadID)
{
    resultBuffer[tid] = input.Foo( tid);
}
```

Consider the following instead:
```
struct WorkData {
    float*A;
    float*B.
};
struct PushData {
    WorkData* Input;
    float* Dest;
};

[vk::push_constant] ConstantBuffer<PushData> cb;

[numthreads(64, 1, 1)]
void ComputeMain(uint tid: SV_DispatchThreadID)
{
    cb.Dest[tid] = cb.Input->A[tid] * cb.Input->B[tid];
}
```

**Comment by csyonghe** [comment]
I am able to fix the performance/memory consumption issue in the slang compiler for the given code snippets. However, using large arrays may still cause problems in the driver / downstream compiler and should be avoided if possible.
