### ISSUE TITLE
GatherCmp does not appear to be supported

### ISSUE THREAD

**Issue by zbethel** [shader-slang/slang#418]
I get the following error:

error 30027: 'GatherCmp' is not a member of 'Texture2DArray'.

Is there somewhere I can easily add this semantic (or others that are missing)? Or is that an involved process?

EDIT: Looking through the slang-meta file, I found this comment:

            static const struct {
                char const* genericPrefix;
                char const* elementType;
            } kGatherExtensionCases[] = {
                { "__generic<T, let N : int>", "vector<T,N>" },

                // TODO: need a case here for scalars `T`, but also
                // need to ensure that case doesn't accidentally match
                // for `T = vector<...>`, which requires actual checking
                // of constraints on generic parameters.
            };

**Comment by tfoleyNV** [comment]
A few notes:

* I believe you have found the right place for adding new methods on the builtin texture types. If you end up adding `GatherCmp`, I'd welcome a pull request. Otherwise, I'll probably get to it later this week.

* The comment you see there means that something like `GatherRed` will only be supported by `Texture2D<float4>` but not `Texture2D<float>`, due to a compiler limitation at the time I wrote the code. I believe I could now lift that limitation, but it would require testing.

**Comment by zbethel** [comment]
Yeah, I was able to verify that Texture2DArray<vector<float, 1> > does have the GatherCmp method after I added it, but the non-vector type doesn't.

**Comment by csyonghe** [comment]
This is now supported.
