### ISSUE TITLE
Slangc crashes when using  `[AutoPyBindCUDA]` and `[shader("compute")]` in the same file

### ISSUE THREAD

**Issue by eliemichel** [shader-slang/slang#4289]
Using slangtorch's loadModule on a slang file that defines both an `[AutoPyBindCUDA]` entry point and and a `[shader("compute")]`  entry point (different functions) causes `slangc` to crash ("*Compilation failed with error 3221225477*" in Python traceback, no stderr from slangc).

Example:

```csharp
[AutoPyBindCUDA]
[CUDAKernel]
void square(TensorView<float> input, TensorView<float> output)
{}

[shader("compute")]
[numthreads(1,1,1)]
void computeMain(uint3 threadId: SV_DispatchThreadID)
{}
```

**Comment by ArielG-NV** [comment]
Background on what seems to be wrong: 
1. `[AutoPyBindCUDA]` and `[CUDAKernel]` adds `HLSLExportDecoration`. This means we won't discard the unused function.
2. `square` which uses `TensorView` (and is not used by an EntryPoint meaning `require` will not send an error) then attempts to be emitted by GLSL/HLSL/etc at the very end of the compile since the function is not discarded. This causes an assert since not all targets support 'TensorView'.

**Comment by eliemichel** [comment]
Thanks for the insights! Note that `slangc` crash also occurs within the call to slangtorch's `loadModule`, so when targetting CUDA with `TensorView` capability.

My current workaround is to play with defines, which is fine although I end up with boilerplate code that I could not find a way to abstract away/automate. Something like:

```csharp
// pseudo-code
interface ITensor { /* [...] */ }
// [...]

void squareImpl(ITensor input, ITensor output) {
    // Here is the actual implementation of my kernel
    // [...]
}

// How to "automate" the generation of what's below?
#ifdef USE_PYTORCH
[AutoPyBindCUDA]
[CUDAKernel]
void square(TensorView<float> input, TensorView<float> output)
{
    squareImpl(/* [...] */);
}
#endif

#ifdef USE_COMPUTE
[shader("compute")]
[numthreads(1,1,1)]
void computeMain(uint3 threadId: SV_DispatchThreadID, StructuredBuffer<float> inputData, /* [...] */)
{
    squareImpl(/* [...] */);
}
#endif
```
