### ISSUE TITLE
Compiler crashes when using the type_param itself as type argument

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#434]
Slang should check the case where the `type_param` itself is being used as the global generic type argument when compiling an entry point. Currently if this happens the compiler crashes at `creatingGlobalGenericTypeSubstitution()` when trying to find and specialize a witness table that does not exist.

Specifically, we should not allow `TMaterial` being used as type argument when compiling this code:
```
type_param TMaterial : IMaterial;
void main() { ... }
```

**Comment by tfoleyNV** [comment]
Thinking about this, there is a subtle issue here where just banning use of the type parameter itself isn't enough, because the user could specify a type that *depends* on the type parameter, e.g.:

```hlsl
type_param TMaterial : IMaterial;

struct FakeMaterial : IMaterial {
    TMaterial data;
    float3 someMaterialMethod() { return data.someMaterialMethod(); }
    // etc.
}
```

In this case, allowing the user to specify that `TMaterial` should be filled in with `FakeMaterial` would cause the same basic problem as trying to fill in `TMaterial` with itself (although the crash might be different).

The essence of a correct check would seem to be making sure that the type specified as an argument has no dependencies (even indirectly) on the parameter. This sounds tricky to make precise, although we could probably rule out a lot of simple cases easily.

A stringent rule would be to say that if module M declares a `type_param`, then any argument for that type parameter cannot come from a module N that imports M (direclty or indirectly). That would be simple(-ish) to enforce, but might be hard for users to work with.

**Comment by csyonghe** [comment]
Closing this issue since we decided to drop support for `type_param`.
