### ISSUE TITLE
SPIRV: Unable to decorate vertex/pixel entry points with `[[vk::location()]]`

### ISSUE THREAD

**Issue by chaoticbob** [shader-slang/slang#4393]
`[[vk::location()]` doesn't work for vertex and pixel entry points, is this intentional?

The shader below results in the follow error message:
```C:\code\hai\test-shaders\ps_location_attr.slang(3): error 31002: attribute 'vk_location' is not valid here
[[vk::location(0)]]
      ^~~~~~~~
C:\code\hai\test-shaders\ps_location_attr.slang(10): error 31002: attribute 'vk_location' is not valid here
[[vk::location(0)]]
```

CMDs:
```
slangc.exe -target spirv -lang slang -D__spirv__ -emit-spirv-directly -profile vs_6_0 -entry vsmain C:\code\hai\test-shaders\entry_point_location_attr.slang

slangc.exe -target spirv -lang slang -D__spirv__ -emit-spirv-directly -profile ps_6_0 -entry psmain C:\code\hai\test-shaders\entry_point_location_attr.slang
```

Shader
```
[[vk::location(0)]]
[shader("vertex")]
float4 vsmain(): SV_POSITION 
{
    return float4(0, 0, 0, 0);
}

[[vk::location(0)]]
[shader("pixel")]
float4 psmain(float4 P : SV_POSITION) : SV_Target0 
{
    return float4(0, 0, 0, 0);
}
```

**Comment by chaoticbob** [comment]
I would say that it's more common for pixel shaders since that's how you can specify a target in a multiple render target setup:

```
// Hypothetical: Vulkan version of render will use MRT2 instead 0 
[[vk::location(2)]]
[shader("pixel")]
float4 psmain(float4 P : SV_POSITION) : SV_Target0 
{
    return float4(0, 0, 0, 0);
}
```

For vertex, there could be a case like this:
```
// Set SV_POSITION to write to location 1
[[vk::location(1)]]
[shader("vertex")]
float4 vsmain(): SV_POSITION 
{
    return float4(0, 0, 0, 0);
}

[shader("pixel")]
float4 psmain(
    float3 color : COLOR,  // implicit location 0
    float4 P : SV_POSITION // implicit location 1
) : SV_Target0 
{
    return float4(color);
}
```

**Comment by csyonghe** [comment]
This feels a rare and niche use case, and the user can always wrap things in an explicit struct and specify that on the struct fields if it is needed.

I would be leaning towards not supporting this, because explicit binding isn't something we like in shader programming and we would rather just do minimum work here to allow most code to compile. There can be several other corner cases like this, but I don't feel like they are worth our time going in great lengths for 100% consistency with dxc. 

That said, if you feel this is an important case to support, we can still plan it. We will also welcome patches for this feature.

**Comment by chaoticbob** [comment]
Yeah, no real way of knowing the usage frequency of these things. 

Lets close it for now and if enough people come looking for it, we can revisit. This issue can just be paper trail.
