### ISSUE TITLE
Crash when passing undefined identifier GS [instance(...)] attribute

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#463]
I moved all the CSM depth-pass shaders to a single file. 
If only the VS and PS are in the file, and the GS is in a separate file, it works. Once I move the GS into the same file, Slang crashes.

To reproduce: Falcor, branch `single-shader-file-csm`, run the Shadows sample.

**Comment by tfoleyNV** [comment]
Looking into it now.

Note that Conor Lavelle contacted me about a similar issue where he got crashes in Slang because the file contained a line like `[instance(CASCADE_COUNT)]` on the GS entry point, but `CASCADE_COUNT` was only being defined for some program compiles and not others. A simple workaround was to conditionally define `CASCADE_COUNT` to one if it wasn't already defined.

Of course, Slang shouldn't be crashing in cases like that anyway, and we may need to place some more serious restrictions where entry-point attributes don't get validated unless the given entry point has actually been requested for compilation.

**Comment by tfoleyNV** [comment]
I've confirmed that this is the same underlying issue that Connor ran into.

I'm working for a fix for the crash in Slang, after which you get an "undefined identifier" error for the name you are passing to the `[instance(...)]` attribute on the GS. This behavior matches fxc and dxc in teh same case.

The right answer is to use the preprocessor to define the instance count macro inside the shader, if it hasn't been passed in from outside.

**Comment by tfoleyNV** [comment]
I will of course fix the Slang crash.
