### ISSUE TITLE
Matrix layouts are incorrectly assigned during a compile

### ISSUE THREAD

**Issue by ArielG-NV** [shader-slang/slang#4634]
Problem:
```
    column_major float3x3 MC2;
    MC2 = float3x3(
            1.0, 0.0, 10.0, 
            0.0, 1.0, 20.0,
            0.0, 0.0, 1.0,
        );
```
has the following types:
`MC2` is `matrix<T,3,3,column_major>`
`float3x3()` is `matrix<T,3,3,unknown_layout>`

Once SSA runs, `MC2` uses are removed in-favor of `float3x3()`. This means the matrix type is now incorrect all-throughout slang's compile since `matrix<T,3,3,unknown_layout>` is never casted into `matrix<T,3,3,column_major>`.

Expected:
`float3x3()` is casted into `matrix<T,3,3,column_major>` (or some-form of casting takes-place to not lose type information)

**Comment by csyonghe** [comment]
Note that matrix layout only matter in two places: loading from a memory location, or storing into a memory location. Therefore, the only place where we need to keep the layout info correctly is in struct field types or global parameter types.

For temporary SSA values, matrix layout doesn't matter.

This means that the current behavior is fine. Because after a matrix is loaded into an SSA register, the values at each semantic row/col is already determined and matrix layout no longer matter.
For the `float3x3()` constructor call, since it explicitly specifies the value at each col and row, the layout shouldn't matter.

**Comment by ArielG-NV** [comment]
What likely needs to-be-done is an insert of
```
__generic<T,N,M,layout1, layout2>
Matrix<T,N,M,row_major> MatrixToMatrixCast (Matrix<T,N,M,unknown_layout> val)
{
    return val;
}

__generic<T,N,M,layout1, layout2>
Matrix<T,M,N,column_major> MatrixToMatrixCast (Matrix<T,N,M,unknown_layout> val)
{
    return transpose(val);
}
```

**Comment by csyonghe** [comment]
Conceptually, casting a matrix from row_major to column_major shouldn't be a `transpose`. It should just be a type modification.

**Comment by csyonghe** [comment]
The place where we want to implement the tranposition is right before a `store` or right after a `load`.
