### ISSUE TITLE
Module reload with same session.

### ISSUE THREAD

**Issue by Lumengine** [shader-slang/slang#4645]
Hi,
I have a question regarding shader reload with the same session. I have a filewatcher on a shader to be able to do shader hot-reloading and I should keep the same slang session as I have a lot of compiled modules inside this session for type conformances (and I don't want to recompile all the type conformance module). But when reloading the shader (with different code), I think there is a cache of imported module inside the session and it won't recompile with the new shader code. Is there a  way to do that ?

Thanks,
Baptiste

**Comment by csyonghe** [comment]
Module unloading is complicated since there can be many dependent objects on a loaded module, so it can't simply be removed from the session. Currently we don't plan to support direct removal of a loaded modlue, and creating a new sesion with precompiled modules is the cleanest way forward. Closing as won't fix.

**Comment by Lumengine** [comment]
Ok, 
Thank you for the answer ! 
Best,

Baptiste
