### ISSUE TITLE
Report actual usage of UAVs in the shader

### ISSUE THREAD

**Issue by nbentyNV** [shader-slang/slang#465]
D3D12 forces us to insert a UAV barrier whenever there's a RAW, WAR or WAW UAV hazard.
Falcor doesn't do that currently. The assumption is that if a user binds a UAV, he is going to write to it.

However, some users might choose to bind a UAV and only read from it, in which case a barrier is required.
There's a performance cost when inserting redundant barriers. It would help if Slang could report for each resource what the actual access is (in addition to what was declared).

**Comment by tfoleyNV** [comment]
So the situation here is that the user binds, e.g., a `RWStructuredBuffer<Foo>` but then only reads from it? And they couldn't just use `StructuredBuffer<Foo>` because either creating an SRV would be tricky, or because they want to re-use descriptor tables between passes that use read-write and read-only access.

The way that Slang is structured, this kind of analysis would properly only be available together with final compiled code. We couldn't reasonably provide it through the existing reflection API (even the "is sample rate" check in the current reflection API is a bit of a kludge in this regard).

This is something we *can* do, but it would take a lot of work to implement. I suppose that as an initial hack, we could have Slang use the DXIL reflection interfaces to read back information that dxc computes, but even that would require some careful juggling.

**Comment by nbenty** [comment]
It's not urgent, not for 3.0. I'll just add barriers whenever a UAV is used and live with the perf-hit (which I'm not sure how big that is)

**Comment by tangent-vector** [comment]
Closing. This is an old issue, and Slang is somewhat philosophically opposed to these kinds of reflection queries that relate to the behavior of code post-optimization.
