### ISSUE TITLE
Create feature & target stability tables

### ISSUE THREAD

**Issue by swoods-nv** [shader-slang/slang#4840]
Slang should document clearly in a table (or two tables) the maturity/stability level of:
- Each target language 
- Each major feature (e.g. ray tracing, mesh shaders, autodiff) -- and if the feature is only available on some targets, which ones.

**Comment by bmillsNV** [comment]
main landing page for target specific documentation. hub for all the behaviors that are target specific.

**Comment by jkwak-work** [comment]
I am not sure how to get a list of "features".
There isn't a clear way to define what are the "feature"-s.

Once we have a list, we can have a table like the following.
| Feature | DX11 | DX12 | Vulkan | OpenGL | Metal | WGSL |
|--|--|--|--|--|--|--|
| Ray-Tracing | N/A | Supported | Supported | Supported | Planned | N/A |
| Mesh shader | N/A | Supported | Supported | Supported | Planned | N/A |
| ... more features |

I am not sure if we want to include CUDA and OptiX on the table.

I think this table can go to this [page](https://shader-slang.com/slang/user-guide/a2-target-specific-features.html).

**Comment by jkwak-work** [comment]
I am little unclear on how to define "stable" or "mature".
Each cell in the table can be one of the followings
- Supported: when the feature is expected to work with no problem, although the user may or may not encounter edge case bugs.
- Planned: when the feature is not expected to work fully and we know that the implementation is incomplete.
- N/A: when the target doesn't support the feature and Slang has no way to support it for the target.

The description of this issue implies that we should say "stable" or "unstable" rather than "Supported".
But I am not sure how to define "stable".
