### ISSUE TITLE
log2(uint) doesn't work

### ISSUE THREAD

**Issue by pclarberg** [shader-slang/slang#487]

**Comment by tfoleyNV** [comment]
The underlying issue here is that our stdlib declaration of `log2` (and many other functions) is generic:

```
T log2<T: __BuiltinFloatingPointType>(T val);
```

`__BuiltinFloatingPointType` is an implementation-detail `interface` that all of the floating-point types (`half`, `float`, and `double`) conform to. This lets us write a single generic that works for all these types rather than expanding out a ton of distinct declarations (once you consider vector and matrix versions...).

The problem is that when the front-end sees a call like `log2(someUInt)` it infers that `T = uint` and then checks whether `uint : __BuiltinFloatingPointType` and finds that the conformance doesn't hold. This means it can't find generic arguments to use in specializing the function, and thus doesn't consider it as an overload candidate.

A solution to this problem would require us to infer that `T = float` in this case. The right way to handle this would be to allow constraints on generic type arguments to be used to "promote" a provided type to one where an implicit conversion is possible, and the interface constraint holds. We could probably do this in a completely ad-hoc fashion by just walking through base types in a fixed promotion order and take the first that meets the constraint.

Doing something more general here would seem to take a lot more work.
