### ISSUE TITLE
Flag to control emission of line directives

### ISSUE THREAD

**Issue by tfoleyNV** [shader-slang/slang#49]
Emitting line directives is probably the right default in "rewriter" mode (since we need to see error messages from the downstream compiler), and it is arguably the right default when you want debug output. It isn't the right thing when people want to look at the output and know what is going on.

Realistically, we probably want:

- A direct flag (e.g., `-no-line-directives` and `-line-directives`) to control whether we output line directives at all

- Make line directives the default for "rewriter" files and when debugging is desired (e.g., when a `-g` flag is specified), but otherwise skip it

**Comment by tangent-vector** [comment]
One more detail here is that we might want to either:

- switch to always using proper C-style line directives, even for GLSL output, or
- give the user a way to control the directive style

This is because glslang at least supports better line directives, so we might as well take advantage of it to produce better error messages in rewriter mode

**Comment by tfoleyNV** [comment]
Pull request #132 added a reasonable level of control for `#line` directives through the API interface, and I'd like to call that good enough for now. If users want to resurrect this issue, they can.
