### ISSUE TITLE
WGSL compilation: no conformances for interface

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#4938]
The following tests fail to produce valid WGSL

- compute\dynamic-dispatch-18
- compute\dynamic-dispatch-19
- compute\extension-on-interface
- compute\interface-assoc-type-param
- compute\interface-shader-param
- compute\interface-shader-param-in-struct
- compute\interface-shader-param2
- compute\interface-shader-param3
- compute\interface-shader-param4

**Comment by aleino-nv** [comment]
@csyonghe what do the "no conformances for interface" messages mean?

I'm expecting that the work of resolving these errors should fall under some other already existing issue for WGSL milestone 1, but I'm not sure where this belongs.

**Comment by csyonghe** [comment]
This is to be expected. For these specific files, you need additional compiler arguments. For example, in `dynamic-dispatch-18`, there is this line:
```
//TEST_INPUT: type_conformance Impl:IInterface = 3
```
which means you will need to link the type conformance `Impl:IInterface` to the compilation. Currently this isn't specifiable via slangc commandline so we have to defer this test until slang-rhi is ready.

Closing since this is expected if the file is compiled with slangc.
