### ISSUE TITLE
Add spirv-link to slang package

### ISSUE THREAD

**Issue by cheneym2** [shader-slang/slang#4991]
In order to utilize precompiled SPIR-V modules, they need to be linkable, which requires the "spirv-link" tool.  Currently slang only provides spirv-dis and spirv-val.

**Comment by cheneym2** [comment]
https://github.com/shader-slang/slang-binaries/pull/56

**Comment by jkwak-work** [comment]
It seems like you decided to add new executable binary to slang-binaries.
But please check out this issue first.
https://github.com/shader-slang/slang/issues/4610

The reason why we stopped using spirv-val.exe and started calling API is because depending on PATH setting on the system, an unexpected spirv-XX.exe can be called, which may not match to the SPIR-V version that slang.dll is using.

**Comment by cheneym2** [comment]
To be clear, I'm not suggesting that we use spirv-link.exe in slang.dll.  Rather, the consideration is whether CI tests may still benefit from it.  Using spirv-link.exe is how I validated precompiled target module support worked.

I'm not sure that it's necessary
, and I'm fine not merging it.  I just wanted to attach the PR to the Issue, regardless.

**Comment by cheneym2** [comment]
Assuming that we don't need this for now, closing.
