### ISSUE TITLE
WGSL: Varyings

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5067]
Support varying inputs/outputs

**Comment by aleino-nv** [comment]
@csyonghe Do we have plenty of tests that would ensure varyings work well if they pass? If so this task should be covered already.

**Comment by csyonghe** [comment]
@jkwak-work can you comment if varying input/output between vertex/fragment stages is already working and we can close this issue?

**Comment by jkwak-work** [comment]
Basic support for Varying input/output is implemented with the following PR, but those PRs cover only a few basic semantics.
- https://github.com/shader-slang/slang/pull/5498
- https://github.com/shader-slang/slang/pull/5506

The remaining task for this issue is to make sure all of semantics for varying inputs and outputs work properly.

**Comment by aleino-nv** [comment]
Not sure but the PRs here https://github.com/shader-slang/slang/pull/5670 may also be needed in some cases.

**Comment by aleino-nv** [comment]
...and this PR as well: https://github.com/shader-slang/slang/pull/5641
