### ISSUE TITLE
#version of GLSL in older platform

### ISSUE THREAD

**Issue by GraphZou** [shader-slang/slang#5103]
I am trying to ensure compatibility with older machines.
When using slang::IGlobalSession->findProfile("glsl_330"), it returns a non-zero value.
However, we receive a GLSL code that starts with "#version 450".
Even "slangc.exe" has the same problem.
Is there any way to set a lower version of GLSL?

**Comment by GraphZou** [comment]
Another related question is, is there any way to obtain the code for the GLES version "#version XX es"?

**Comment by csyonghe** [comment]
GLES isn't an officially supported target at the moment. The current GLSL backend is for Vulkan flavored GLSL only.

I don't think we have profiled defined for anything older than glsl_430, so frontend capability checks for gles platforms isn't possible right now.

**Comment by GraphZou** [comment]
A confusing issue is that when we use findProfile() with "glsl_430" or "glsl_440", we always get "#version 450", but versions 450 and 460 seem to work well.

**Comment by csyonghe** [comment]
The `-profile` option to the compiler mostly specifies what intrinsics the code is allowed to use, and does not necessarily translate to the output glsl version. Because our GLSL backend only support the Vulkan flavored GLSL output, we have not implemented anything specific for generate outputs on older GLSL versions.

This isn't a supported feature and we are unlikely to have resource allocated on the GLSL backend as our focus is to get as many users move on to the direct-spirv backend. However we will welcome contributions for a fix to get GLSL backend working in more situations.

**Comment by csyonghe** [comment]
Closing as won't fix now.

**Comment by GraphZou** [comment]
Thank you for the explanation, after some trial and error, I seem to have found a viable solution.
First, use Slang to generate SPIR-V, then use spirv-cross to generate a lower version of GL or GLES code.
