### ISSUE TITLE
Parser confused at generic types

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#514]
```
//TEST(compute):COMPARE_COMPUTE:
//TEST_INPUT:ubuffer(data=[0 0 0 0], stride=4):dxbinding(0),glbinding(0),out
// Confirm that generics syntax can be used in user
// code and generates valid output.

RWStructuredBuffer<float4> outputBuffer;

interface IBxDF
{
    float getVal();
};

struct ShadingPoint<TBxDF : IBxDF>
{
    TBxDF bxdf;
};

[numthreads(1, 1, 1)]
void computeMain(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    typedef ShadingPoint<BxDF<5> > BXDFType;
    BXDFType b;
    outputBuffer[0] = b.bxdf.getVal();
}

struct BxDF<let x: int>
{
    float getVal() {return x;}
};
```

**Comment by tfoleyNV** [comment]
Context: In this case the `ShadingPoint<BxDF<5> >` fails to parse because the `BxDF` type is not yet defined. Slang is supposed to have context-free parsing, though, because we also don't see `impor`ed type names when parsing.

The right fix here is to change the type parsing logic to not rely on looking up names in the current environment, but that can create some subtle challenges.

(An alternative fix in this case would be to delay function bodies until very late in semantic checking, but that doesn't resolve similar cases that might occur with types used in function parameter lists)
