### ISSUE TITLE
Implement "ThisType"

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#523]
It would be good to allow `interface`s to have `static` requirements, as well as initializer requirements (once those become a user-exposed feature), which are effectively `static`.

One sticking point for both is that we often want to be able to name the type that is conforming to the interface within its body (e.g., for a "factory" sort of method).

We already have the notion of a "this type substitution" in the compiler, so the main thing needed is a concrete representation of the "this type" itself. Syntax could be either `ThisType` or `This` - the latter is a nice mirror or `this` at the type level.

We should allow `This` inside any aggregate type or `extension` declaration. In contexts where the exact type is known, it should resolve to that type, while in contexts where the exact type is *not* known (e.g., inside an `interface`) it should turn into a custom type node that is suitable to substitute into something more specific later.

**Comment by tfoleyNV** [comment]
I don't expect a `This` type to have any impact at the IR level, since in all contexts where the concrete type wouldn't be known, there should be a generic parameter to stand in for the type (so that `This` would lower as a reference to that parameter). E.g., for an extension of an interface, any method would have a generic parameter for the concrete type the extension is being applied to.
