### ISSUE TITLE
Slang-RHI: Intel driver crashes in vkCreateDevice during DeviceImpl::initVulkanInstanceAndDevice

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5275]
Note again that this is for the **intel** driver, `igvk64.dll`.
Edit: However, there are issues even when running on discrete GPU: https://github.com/shader-slang/slang/issues/5275#issuecomment-2410225134

I ran `slang-test -bindir %BINDIR% -category full -api wgpu tests/bugs/atomic-coerce.slang`.
I don't understand why slang-test is creating a Vulkan device.

Affected tests:

- tests/bugs/atomic-coerce.slang
- tests/bugs/frexp-double.slang
- tests/bugs/frexp.slang
- tests/bugs/generic-type-duplication.slang

**Comment by csyonghe** [comment]
slang-test will attempt to create a device at start with all possible APIs to determine which APIs are available on the system.

**Comment by aleino-nv** [comment]
> slang-test will attempt to create a device at start with all possible APIs to determine which APIs are available on the system.

Ok I see.

    in slang-test.exe: Microsoft C++ exception: VK::Exception at memory location 0x000000AEAD598A58


Should we wrap this in a catch and just conclude that VK is not available in this case? Currently it seems to tear down the whole test.

**Comment by aleino-nv** [comment]
For the moment I'll set slang-test to use the discrete GPU on my machine.

**Comment by aleino-nv** [comment]
> For the moment I'll set slang-test to use the discrete GPU on my machine.

That didn't help much. Still crashing but now instead on WGPU device/instance destructors. Need to investigate this case as well.

**Comment by cheneym2** [comment]
There is already try, catch guards in render-test's innerMain() function around _innerMain(), which should catch crashes, such as from vkCreateDevice.  I find that it doesn't work though.  The exception is still thrown and uncaught.  I am able to force a crash by providing bad input to vkCreateDevice, such as by nulling out pQueueCreateInfos:

```
        deviceCreateInfo.pQueueCreateInfos = nullptr;        //&queueCreateInfo;
        deviceCreateInfo.enabledExtensionCount = uint32_t(deviceExtensions.size());
        deviceCreateInfo.ppEnabledExtensionNames = deviceExtensions.data();
        if (m_api.vkCreateDevice(m_api.m_physicalDevice, &deviceCreateInfo, nullptr, &m_device) != VK_SUCCESS)
```

That causes an uncaught exception.  What I learned is that the VS projects can be configured so that try/catch blocks will either catch "structured asynchronous" exceptions, and/or "standard C++ synchronous" exceptions.

Setting the compile flag in render-test to "/EHa" instead of the current "/EHsc" allows the try/catch block to catch all exceptions.

**Comment by cheneym2** [comment]
https://learn.microsoft.com/en-us/cpp/build/reference/eh-exception-handling-model?view=msvc-170

**Comment by cheneym2** [comment]
https://github.com/shader-slang/slang/pull/5495 seems to work, though it might need to be guarded by "if MSVC".
