### ISSUE TITLE
slang-test assert on usePassthru

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5276]
This assert triggers

        case RenderApiType::WebGPU:
            target = SLANG_WGSL;
            SLANG_ASSERT(!usePassthru);
            break;

Affected test:

- tests/bugs/texture2d-gather.hlsl (**NOTE**: .hlsl extension)

I think the reason `usePassthru` is true is due to this special case logic above, for this particular test, due to file extension of `.hlsl`:

                if (languageRenderType != RenderApiType::Unknown)
                {
                    foundLanguageRenderType = languageRenderType;

                    // Use the pass thru compiler if these are the sources
                    usePassthru |= (argName == "hlsl" || argName == "glsl");

                    continue;
                }

**Comment by jkwak-work** [comment]
This assertion is a blocker for a PR
- #5315 

I am going to comment out the assert for now.

**Comment by aleino-nv** [comment]
> This assertion is a blocker for a PR
> 
> * [Fix D3D12Core.dll loading problem for debug build #5315](https://github.com/shader-slang/slang/pull/5315)
> 
> I am going to comment out the assert for now.

If it's a single test triggering this due to some file-extension issue, then I think the test should just be disabled for now, rather than commenting out the assert.

**Comment by jkwak-work** [comment]
It appears that the assertion is incorrect and it should be removed.

The issue turned out to be related to the use of `COMPARE_HLSL_RENDER` keyword in the file, `tests/bugs/texture2d-gather.hlsl`.
The fact that the file has an extension, ".hlsl", was unrelated to the issue.

The [document](https://github.com/shader-slang/slang/blob/master/tools/slang-test/README.md#test-types) describes what `COMPARE_HLSL_RENDER` does as following,
> Runs 'render-test' rendering two images - one for hlsl (expected), and one for slang saving to .png files. The images must match for the test to pass.

Basically, it compiles the given shader with DXC compiler and generate an output image.
And then it compiles with each and every render API and generate an output image and compare it to the output from DXC.

The problem is on how the input arguments are generated when rendering for metal and wgpu.
The command-line argument for rendering with DXC is, as an example,
```
-wgpu -hlsl -o .expected.png
```
And the command-line argument for rendering with WGPU API is,
```
-wgpu -slang -o .actual.png
```

The first set of arguments conflict in a way that "-wgpu" instructs to use Tint as the renderer at the same time, it tells to use DXC compile with the next argument, "-hlsl". In this case, "-wgpu" should be ignored.

The second set is kind of O.K, because "-slang" and "-wgpu" don't conflict. "-slang" instructs to treat the input as slang shader and "-wgpu" instructs to use WGPU as the output render API.

**Comment by jkwak-work** [comment]
To be clear, the proper fix was to remove the assertion and replace it with the following lines, which is in a same pattern as other targets in the same switch-statement.
```
        case RenderApiType::CUDA:
            target = SLANG_PTX;
            nativeLanguage = SLANG_SOURCE_LANGUAGE_CUDA;
            passThru = SLANG_PASS_THROUGH_NVRTC;
            break;
        case RenderApiType::WebGPU:
            target = SLANG_WGSL;
            // SLANG_ASSERT(!usePassthru); // <==== THIS IS REMOVED
            nativeLanguage = SLANG_SOURCE_LANGUAGE_WGSL; // <=== THIS IS ADDED
            passThru = SLANG_PASS_THROUGH_TINT; // <=== THIS IS ADDED
            break;
        }

    SlangSourceLanguage sourceLanguage = nativeLanguage;
    if (!usePassthru)
    {
        sourceLanguage = SLANG_SOURCE_LANGUAGE_SLANG;
        passThru = SLANG_PASS_THROUGH_NONE;
    }
```
As explained on my [previous comment](https://github.com/shader-slang/slang/issues/5276#issuecomment-2418036928), a right behavior is to ignore `passThru` and `nativeLanague` values when `-hlsl` command-line argument is given.
