### ISSUE TITLE
WGSL: Missing return statement

### ISSUE THREAD

**Issue by aleino-nv** [shader-slang/slang#5282]
Affected tests:
- tests/hlsl-intrinsic/scalar-float.slang
- tests/hlsl-intrinsic/vector-float.slang

WGPU eror:

    WGPU error: Error while parsing WGSL: :29:1 error: missing return at end of function

**Comment by kaizhangNV** [comment]
The actual problem is we emit
```
log10()
```

to an empty function in wgsl

```
fn log10_0( x_0 : f32) -> f32
{
}
```


this can be easily reproduced here: 

https://shader-slang.com/slang-playground/?target=SPIRV&code=eJxNkEEKwjAQRfc5xUcQEis2AXVTPIInUBfFkBKonVJjUUrv7iRW2kAmYebNz5_4R0tdQFuXn6qjV2MLIXryFm3nm3AufSOVGIQAL07A2zdO8Sa1KlI2BVdTGeBiiYENpNlphxxyz6dickkFxjTnF_15DvcgO2EB2Ql3ekr37xxSnDX6y41FBpgtjI77FzTGYiaTTLRaU2W07C_s7aaQ8eMHN7kfZw9xPHqFaTzu3sAc_wbSd8jV2l6b1TZiXBi_HYpNqw
