### ISSUE TITLE
Support installing from vcpkg

### ISSUE THREAD

**Issue by jesta88** [shader-slang/slang#531]
vcpkg is getting a lot of traction and all the popular libs are already there. Having slang available would be extremely helpful.

**Comment by jesta88** [comment]
I'll submit the 0.10.12 package, but in the future it would help having a direct link the latest release sources, without having to go on the release page.

**Comment by tfoleyNV** [comment]
We can look into officially supporting vcpkg, depending on how it would work into our release process. Please let me know if you run into any problems with the source packages, since they are not something that our current Slang customers rely on today.

Can you share any information on how you are considering using Slang? Things are still a little rough around the edges, so if we get a sense of your requirements I may be able to help you know what to watch out for as far as implementation status.

**Comment by jesta88** [comment]
I'm using slang in a CMake-based project on Linux and MinGW for Windows. Having CMake in slang would help a lot since I could simply use the repo as a submodule and everything would compile automatically. 

Also, right now it's very hard to configure slang for vcpkg since it has a dependency in glslang, which built using CMake. vcpkg relies heavily on CMake.

I don't mind creating PR to add CMake functionality if that's something you'd approve.

**Comment by tfoleyNV** [comment]
### On CMake

The way we handle the glslang dependency today is specifically done to *work around* their use of CMake, since otherwise their choice of build tool would infect our project (which would then infect the project's of our users). We instead take the approach of crafting our own build for their code.

Adding a CMake build to our tree creates the challenge that we would either have to make it our One True Build (and thus make integration harder for projects not using CMake), or we'd have to make it strictly optional, which adds complexity to our CI process (we'd have to test both CMake and the existing builds). Right now I wouldn't be inclined to accept a PR to add CMake to the Slang source tree.

### On Vcpkg

I've done a tiny bit of reading on vcpkg, and I wouldn't be against supporting it officially if the overhead for the Slang build/CI process is small (and it doesn't force vcpkg on every Slang developer/user). It looks like they don't actually *require* CMake, and could work with our existing `.vcxproj` files through `msbuild`.

**Comment by csyonghe** [comment]
Closing the issue for now as we can no longer assess the priority given the amount of time passed since the initial opening of the issue. If there is a strong request, please open another issue.
