### ISSUE TITLE
"illegal character" error when compiling to SPIR-V

### ISSUE THREAD

**Issue by snowfoxer** [shader-slang/slang#536]
The lexer get a unexpected/invalid character.
First I thought maybe I entered some invalid character when using input method.
But the lexer give a correct return when I set the target generation to GLSL.
When I compressed the source file to only one line and delete the useless space, the lexer output a less error list.
(1): error 10000: illegal character (0xAB)
(1): error 10000: illegal character (0xAB)
(1): error 10000: illegal character (0xAB)
(1): error 10000: illegal character (0xAB)
(1): error 10000: illegal character (0xAB)
(1): error 10000: illegal character (0xAB)
(1): error 10000: illegal character (0xAB)
(1): error 10000: illegal character (0xAB)
(1): error 10000: illegal character (0xAB)
(1): error 10000: illegal character (0xAB)
(1): error 10000: illegal character (0xAB)
(1): error 10000: illegal character (0xAB)
(1): error 10000: illegal character (0xAB)
(1): error 10000: illegal character (0xAB)
(1): error 10000: illegal character (0xAB)
(1): error 10000: illegal character (0xFE)

The source HLSL file is:

```
struct AppData
{
    float3 position : POSITION;
    float2 texCoord : TEXCOORD0;
};

struct VertexShaderOutput
{
    float2 texCoord : TEXCOORD0;
    float4 position : SV_POSITION;
};

cbuffer PerObject : register( b0 )
{
    float4x4 ModelViewProjection;
};

Texture2D DiffuseTexture : register( t2 );

SamplerState DiffuseSampler : register( s0 );

VertexShaderOutput VS_main( AppData IN )
{
    VertexShaderOutput OUT;

    OUT.position = mul( ModelViewProjection, float4( IN.position, 1.0f ) );
    OUT.texCoord = IN.texCoord;

    return OUT;
}

float4 PS_main( VertexShaderOutput IN ) : SV_TARGET
{
    return DiffuseTexture.Sample(DiffuseSampler, IN.texCoord);
}
```

**Comment by snowfoxer** [comment]
When I use the static string in c instead using the file input, the illegal error disappeared. But I still get a  Segmentation fault.
Suggest to check the size when input a source string.

**Comment by tfoleyNV** [comment]
I tried copy-pasting the code block from the earlier comment into a file and ran it through `slangc` and couldn't repro the issue. Is it possible that the original file included some non-ASCII characters? We haven't yet fleshed out Slang's support for non-ASCII input.

If possible, could you attach the original file to this issue, so that I can hopefully download it with the original bytes intact?

> When I use the static string in c instead using the file input, the illegal error disappeared. But I still get a Segmentation fault.
> Suggest to check the size when input a source string.

I'm not sure I follow this. If you are saying that `spAddTranslationUnitSourceString` should probably take both the string and the size of the string, I agree (the main reason we haven't changed the API is to avoid breaking existing code that uses it).

As for the segmentation fault, is there any way you can share the application code that segfaults so that I can try to repro the crash?

**Comment by snowfoxer** [comment]
@tfoleyNV I found that when I use the op "r" to read the file, some strange '\0' was found. (Using HexEdit they aren't appear. ) With a "rb" op, it disappeared. Sorry to disturb you. And if you know why it happened, Please enlighten me with your instructions.
As for the segmentation fault,  you can try to use the code.
[drip.zip](https://github.com/shader-slang/slang/files/1961412/drip.zip)
Just run the all.bat to compile it. (need clang)
The executable file is in the Disp folder, with the name "case".
The Slang about file which I try to use is in GraphicProgram folder.
The Shader file is in the folder DIsp/data
Thanks a lot.

**Comment by tfoleyNV** [comment]
You can definitely run into problems if you open a file in text mode (`"r"`) but still use `fseek`/`ftell` to find the size of the file, because conversion of line endings may mean that the number of bytes of text you read from the file is different from the amount you computed/expected. I'm not entirely sure why you'd see the exact byte values you did, or why the error messages appear on the first line of the file.

I will try to look at your repro for the segfault when I get a chance, but I will caution you that the turnaround may not be very fast because we only have a few contributors and most of us are busy on other issues. Sorry.
