### ISSUE TITLE
GLSL constant-buffer reflection alignment issue

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#55]
Slang reports the wrong offset for `scale` in the following CB:

layout(set = 0, binding = 0) uniform PerFrameCB
{
    vec2 offset;  // This is reported as 0, which is correct
    vec2 scale;   // This one is reported as 16, but it should be 8 since it can be packed together with offset into a single vec4
};

**Comment by tangent-vector** [comment]
Browsing the code on my phone, I think I see the root cause. In `type-layout.cpp` `Std140LayoutRulesImpl::GetVectorLayout`, the alignment is computed as:

    RoundUpToPowerOfTwo(elementInfo.size * elementInfo.alignment)

But it seems like it should be:

   RoundUpToPowerOfTwo(elementInfo.size * elementCount)

I'll put together a fix soon, but you could try to patch this yourself if you want to test the fix ASAP.

**Comment by tfoleyNV** [comment]
I am working on a PR that should fix this issue, but in looking at the code I can see that my implementation of `std430` is also wrong, and I'll need to construct some test cases for that too.
