### ISSUE TITLE
Generate  language bindings for the compiler from Slang source

### ISSUE THREAD

**Issue by laurooyen** [shader-slang/slang#5646]
For my own personal project I created [Rust bindings]( https://github.com/FloatyMonkey/slang-rs) for the Slang compiler. Currently this involves some manual work which I’d like to automate. Generating C bindings from the C++ COM API by parsing the `slang.h` header has been suggested multiple times e.g. in #3617 and #5565. However, recently I stumbled upon the `gfx/slang.slang` file which contains some compiler COM interfaces defined in Slang itself. This made me wonder whether we could generate bindings from Slang source code itself.

After some discussion with @csyonghe on Discord, the idea is as follows:

Redefine `slang.h` in Slang syntax. Since there’s already a parser for this we can use that to extract the COM interface and emit bindings for a number of languages. This shouldn’t go through the regular compilation/target processing steps since we want to generate bindings to languages that Slang might not support as compilation target.

To avoid cyclic dependencies, especially since the generated C++ header needs to exist prior to compiling `slangc` the binding generator should link against a static Slang library and only rely on internal Slang classes.

Some open questions:
-	Should language bindings be generated from AST or IR? Enums for example need the correct numerical value for each entry, which can be implicitly incrementing. I’m not sure if this info is available in the AST.
-	How does the reflection API fit into this story? Currently it has no COM interface.

Happy to receive feedback and work on this. Would like to upstream my Rust bindings once their generation isn’t as manual anymore.

**Comment by csyonghe** [comment]
As discussed on discord, I like the idea of using a slang.slang file as the single source of truth for the slang API, and use the slang compiler itself to generate language bindings.

On your questions: I think the language bindings should be emitted from AST and not IR, because at IR level, some of the type info are lost or translated into a different form. API interface rewrites like this is best done directly at AST level. Enum values are assgined during type checking so after semantic visitor processing, these are available in the AST node of the enum type.

The reflection API is the tricky one, I suggest we defer this part of work until a later time. We want to COM-ify the reflection API and also clean up the messes there at some point.
For the initial attempt, we can just focus on the compilation API, perhaps include a standalone function to get the json of the reflection for now in the .slang interface.
