### ISSUE TITLE
Provide SlangConfig.cmake in releases

### ISSUE THREAD

**Issue by eliemichel** [shader-slang/slang#5649]
This is more of a nice-to-have than a must-have, but it would be really helpful that releases provide such a file (generated by CMake's install process) to ease the import of precompiled binaries in CMake setups!

**Comment by ov-l** [comment]
I can make a pull-request for this since I already have this setup in my local branch.

**Comment by bmillsNV** [comment]
Thanks! ov-l. Assigned the issue to you :)

**Comment by ov-l** [comment]
I added slang as the only target because I just needed that for my use case. If you intend to link with slang, that should work out of the box. slangc on the other hand would be a different target which I have not included in the export target list, and the executable is already installed by default by the existing cmake script (if you build the executable).
With modern CMake, if you just link with slang::slang, it should be all good on all platforms normally, unless something is wrong in the original CMake script with target setup. I personally tested on linux and windows, both work fine.

**Comment by jkwak-work** [comment]
I am having a hard time figuring out what is requested initially.
It says "import of precompiled binaries", and I am not sure where it is supposed to be imported to.
And what is the use case for this.

@eliemichel , can you clarify my questions so that we can provide a proper support?

**Comment by eliemichel** [comment]
> @eliemichel , can you clarify my questions so that we can provide a proper support?

Sure, I meant "import" as in CMake's vocable of ["imported targets"](https://cmake.org/cmake/help/latest/guide/importing-exporting/index.html). This is the typical way to equip a binary release of a library (be it static or shared) so that it can be properly imported by CMake's [`find_package`](https://cmake.org/cmake/help/latest/command/find_package.html) mechanism (in so-called "Config" mode).

In our case, that would mean if download and unzip a binary release to `/path/to/slang`, then configure a project with `cmake -DSlang_DIR=/path/to/slang` (or add this path to `CMAKE_PREFIX_PATH`): after that simply calling `find_package(Slang REQUIRED)` in my `CMakeLists.txt` would make available the Slang targets (static, shared, executable targets -- whether the release provides).

Aside from manual download, this is also very compatible with FetchContent-based approaches to fetch the precompiled binaries and internally (i.e., inside some `FetchSlang.cmake`'s dynamics) automatically set `Slang_DIR` to the place where it did download the release.

I believe the approach proposed in #5674 is sound, although I wouldn't consider myself an expert in CMake's import/export mechanism.
