### ISSUE TITLE
Slang Submodule (better for offine support)

### ISSUE THREAD

**Issue by TheforgottenDreamer** [shader-slang/slang#5727]
So the project needs get built version of the slang fork of googles dawn project for webgpu and slang-tint downloaded from githubs downloads. I feel like these can remain submodules instead of downloaded zips

**Comment by TheforgottenDreamer** [comment]
I do get where the idea of downloading comes from dawns submodules too

**Comment by csyonghe** [comment]
These google projects have complex setup requirements that we do not wish to bypass to most Slang developers. After all 99% of Slang development is not directly related to WebGPU and it would be easier if most developers don't have to worry about building these google code themselves.

Using submodules would mean everyone need to have bazel + many google dependencies configured on their machine in order to start developing Slang code, which is a big downside. Slang does not really depend on these libraries, and we only use them for testing webgpu shaders, so they are not technically required to exist locally.

**Comment by bmillsNV** [comment]
Thank you for the suggestion. We don’t think that this is the right solution for Slang; going to close as won’t-fix for now.
