### ISSUE TITLE
vector constructor

### ISSUE THREAD

**Issue by pclarberg** [shader-slang/slang#578]
uint triangleIndex = PrimitiveIndex();
    uint4 hitData = uint4(gHitGroupIndex, triangleIndex, asuint(attribs.baryCrd.xy));

This last line fails with message: 
error 30019: expected an expression of type 'uint', got 'vector<uint,2>'

This reproducer compiles with fxc.exe:

    float2 p = float2(0,1);
    uint4 x = uint4(0, 1, asuint(p));

**Comment by tfoleyNV** [comment]
Thanks for filing this. I think I'd consciously left all but the simplest cases out, because I didn't remember if GLSL supported all the flexibility that HLSL has in this regard.

We can probably add these easily for Slang->HLSL compilation, but will need to take some time to make sure things will compile fine for GLSL.

I assume this isn't pressing, insofar as the workaround is pretty clear?

**Comment by csyonghe** [comment]
Closing the issue for now as we can no longer assess the priority given the amount of time passed since the initial opening of the issue.
