### ISSUE TITLE
 Issue with Generated GLSL Shader Parameter Naming and Scoping

### ISSUE THREAD

**Issue by Opaatia** [shader-slang/slang#5862]
## Description:
It appears there is an issue with the handling of GLSL shader code generation, specifically in the naming and scoping of uniform parameters. Utilities like [glslViewer](https://github.com/patriciogonzalezvivo/glslViewer/) typically parse GLSL shader code and assign values to uniform input parameters before execution. However, the generated shader code demonstrates a mismatch in parameter naming conventions and scoping, which causes it to fail.

## Steps to Reproduce:

1. Consider the following example code:

    **Slang Shader:**
```slang
uniform Sampler2D   u_tex0;
uniform float2      u_mouse;
uniform float       u_time;
uniform float2      u_tex0Resolution;
```
2. **The generated GLSL shader:**
```glsl
    #version 450
    layout(row_major) uniform;
    layout(row_major) buffer;
    layout(binding = 1)
    uniform sampler2D u_tex0;

    struct GlobalParams_std140_0
    {
        vec2 u_mouse;
        float u_time;
        vec2 u_tex0Resolution;
    };

    layout(binding = 0)
    layout(std140) uniform block_GlobalParams_std140_0
    {
        vec2 u_mouse;
        float u_time;
        vec2 u_tex0Resolution;
    } globalParams_0;

    layout(location = 0)
    out vec4 entryPointParam_frag_0;
```
3. The generated GLSL shader after many different options/flags would not work due to:
       - The mismatch in parameter names (e.g., numeral suffixes added during generation).
       - Scoping issues related to the uniform block/struct.
       - The inability to explicitly bind or point to buffers/layouts to obtain values, as these may be omitted by the utility.

Another example if I were to put uniform variables inside function declaration instead:

**Slang Shader Code:**
```slang
[shader("fragment")]
[numthreads(1, 1, 1)]
float4 frag(
	uniform float2 u_mouse,
	uniform float u_time,
	uniform float2 u_tex0Resolution,
	float4 sv_position : SV_Position)
{
...
}
```

**GLSL Shader Code Output:**
```glsl
struct EntryPointParams_std430_0
{
    vec2 u_mouse_0;
    float u_time_0;
    vec2 u_tex0Resolution_0;
};

layout(push_constant)
layout(std430) uniform block_EntryPointParams_std430_0
{
    vec2 u_mouse_0;
    float u_time_0;
    vec2 u_tex0Resolution_0;
}entryPointParams_0;
```

**Expected Behavior:**
The generated shader should maintain consistent naming conventions and properly scope uniform parameters to ensure compatibility and functionality.

Maybe add a compilation switch to simply copy verbatim for uniform declarations as is to GLSL output?

**Slang Shader Code:**
```slang
uniform Sampler2D   u_tex0;
uniform float2      u_mouse;
uniform float       u_time;
uniform float2      u_tex0Resolution;
```

**Expected GLSL Shader Output:**
```glsl
uniform Sampler2D   u_tex0;
uniform float2      u_mouse;
uniform float       u_time;
uniform float2      u_tex0Resolution;
```

## Question/Request for Clarification:
Is there existing documentation or guidance for managing uniform parameter naming and scoping in generated GLSL shaders? If not, would it be possible to address this mismatch in the shader generation process?

Thank you for your attention to this issue.

**Comment by csyonghe** [comment]
This is linked to how Slang works when translating an input shader to different targets.

After the shader is parsed and checked, we will represent all parameters in a canonicalized form that we know how to emit code for all the targets. In this canonicalized form, all global `uniform` parameters are grouped into a struct, and referred to via a compiler introduced `ConstantBuffer<GlobalParams> globalParams` constant buffer. This constant buffer is then assigned a layout, and emitted as a global buffer parameter when generating HLSL,SPIRV/GLSL/CUDA/Metal and WGSL.

Due to this architecture choice, it wouldn't not be possible for the slang backend to know the original form the parameter is defined and maintain that output structure, especially when we need to provide some consistency around how parameters are laid out across different platforms.

With that said, it would take a significant effort and add a lot of additional complexity to the compiler if we want to support this. It is technically possible to do, but I am not convinced this is going to bring sufficient value to worth the added complexity and expanded surface area of maintenance responsibility.

Slang provides a comprehensive reflection API for users to manage parameter binding. Please refer to our reflection API documentation for more details on how to work with parameter binding in Slang: https://shader-slang.com/slang/user-guide/reflection

**Comment by csyonghe** [comment]
I also recommend reading our technical article on how to build a [cross platform layer to do parameter binding with slang](https://shader-slang.com/docs/shader-cursors/).

**Comment by Opaatia** [comment]
Thanks for pointing those out! That makes sense—it's more of a limitation with GLSLViewer than Slang itself. I’ve realized I’ll probably need to write a new SPIR-V Viewer application at some point. I really appreciate the explanation about Slang's variable layout limitations!
