### ISSUE TITLE
Ensure consistent constant buffer layout across APIs

### ISSUE THREAD

**Issue by tangent-vector** [shader-slang/slang#588]
Issue #583 relates to how our default layout convention for matrices has so far differed between D3D and Vulkan targets, so that it is impossible for a user to, e.g., craft a C/C++ `struct` layout that will match their shader constant buffers across APIs (unless they carefully pad it to lay out the same for all targets).

The original decision to mirror the conventional layout rules of the target API was made back when Slang support GLSL input so that following the GL/VK layout conventions for those targets was a “principle of least surprise” thing.

Now that Slang is fundamentally a cross-compiler, it is more surprising go users that we don’t just impose the HLSL rules on our VK output.

There are some challenges to achieving consistency for all targets because, after all, the layout rules differ between the downstream compilers.

**Comment by tfoleyNV** [comment]
I've just confirmed what I was concerned about: the current Vulkan spec language makes it clear that a `float3` on Vulkan requires 16-byte alignment when used in a uniform buffer, so that the following HLSL declarations cannot be directly reproduced in SPIR-V:

```hlsl
float a;    // offset 0
float3 b; // offset 4
```

When compiling for Vulkan, the layout rules would assign `b` an offset of 16 instead of 4, to deal with alignment.

In order to work around this kind of limitation, slang would need to generate something like:

```hlsl
float4 u;
```

and then turn uses of `a` into `u.x` and uses of `b` into `u.yzw`. Of course, if `a` was an int instead of a `float`, then we'd need to insert some bitcasting operations as well.

In the limit, this feature will overlap with proposed support for `union`s, and require us to turn every type into some kind of unified "bag of bits" format and then implement our own indexing logic from scratch. E.g., we could reduce every type to a `uint4 u[N]` declaration, where `N` is the minimum number of `uint4`s needed to hold the value, and then we could extract whatever fields we need from this data by extracting and bitcasting array elements.

**Comment by csyonghe** [comment]
Closing this issue now. Users who wants this behavior can use `-force-glsl-scalar-layout`.
