### ISSUE TITLE
Better error checking for invalid syntax

### ISSUE THREAD

**Issue by pclarberg** [shader-slang/slang#611]
float4 texDerivs = float4(dUdx, dUdy);   // Correct syntax

float4 texDerivs(0);     // "Unexpected string literal" error
float4 texDerivs(dUdx, dUdy);     // Crash with null ptr exception from Slang

The last one should give an error message instead of crashing.

**Comment by tfoleyNV** [comment]
Thanks for filing this.

In both of those cases, I suspect that Slang is trying to parse the declaration as a local function declaration (which we don’t support), rather than a C++ style constructor invocation (which we don’t plan to *ever* support).

That’s no excuse for crashing, and the “string literal” error message makes no sense, so there is definitely room to improve.

**Comment by csyonghe** [comment]
We have much better parser robustness now due to recent effort to implement the language server.
