### ISSUE TITLE
Reflection around geometry, hull and domain shaders

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#613]
On looking at dxc and reflection for 

https://docs.microsoft.com/en-us/windows/desktop/api/d3d12shader/ns-d3d12shader-_d3d12_signature_parameter_desc

it has a 'Stream' element described as 'Indicates which stream the geometry shader is using for the signature parameter.'. It does not appear this value is available within slang reflection. 

Along a similar tack D3D12_SHADER_DESC has a member cControlPoints 

https://docs.microsoft.com/en-us/windows/desktop/api/d3d12shader/ns-d3d12shader-_d3d12_shader_desc

described as 'Number of control points in the hull shader and domain shader.'

Does not appear to available in slang reflection.

**Comment by tfoleyNV** [comment]
For the "stream" issue, I think the right answer is to define a new `LayoutResourceKind` (aka `SlangParameterCategory`) for GS output streams (maybe `SLANG_PARAMETER_CATEGORY_OUTPUT_STREAM`) and then have the logic in `parameter-binding.cpp` that walks an entry point's parameter list (`processEntryPointParameter`) make sure to have each parameter with an `HLSLStreamOutputType` consume one "unit" of that new resource type in its `TypeLayout`. At that point the layout logic *should* correctly assign each of those streams a unique stream "register." Then it would be easy to use the reflection API to read this information off of each GS output stream parameter.

Note: I would *not* advocate for having the stream number get attached to each "leaf" varying parameter that is output to such a stream, just like a field inside some `cbuffer` doesn't record the `register` of the whole buffer (just its own byte offset *within* the buffer). The big thing to work out there is whether each GS output stream should have its own numbering of output locations (which will probably be driven by what Vulkan/GLSL needs).

Determining the number of control points for an HS/DS should amount to either:

* Reading the data off the `[outputcontrolpoints(n)]` attribute for an HS, if we want the output control point count for that stage
* Reading the element count off of whatever parameter has the `HLSLPatchType` type in the parameter list (this is a base class used to represent both the HLSL `InputPatch` and `OutputPatch` types).

That should just be a matter of plumbing those pieces of data through the API so that the user can see them.

**Comment by natduca** [comment]
I can't decide whether to put this into q3 with language enhancements, or put it into bug bankrupcy. @jsmall-nvidia what would you recommen?

**Comment by jsmall-nvidia** [comment]
I don't have any particular insight around this - it's so long ago I don't even remember writing it. Support around tessellation in general is far from complete. If it was put in bug bankruptcy then that's probly fine.

**Comment by natduca** [comment]
Makes sense, yeah, seems like tesselation is a "when a customer needs it." Putting bankrupcy for now.
