### ISSUE TITLE
compile issue when reading one channel int texture:

### ISSUE THREAD

**Issue by kenchen3000** [shader-slang/slang#623]
There seems to be another compile issue with one channel texture:

Texture3D<int> gTexture;
int id = gTexture.SampleLevel(gTextureSampler, float3(texC,i/dimension), 0).x;

Program Linkage failed.

Program with Shaders:
Framework/Shaders/FullScreenPass.vs.slang/*main*/
VisualizePointCloud.ps.slang/*main*/

ERROR: Project/VisualizePointCloud.ps.slang:65: '=' :  cannot convert from ' global 4-component vector of uint' to ' temp highp uint'
ERROR: Project/VisualizePointCloud.ps.slang:65: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.

If I use a one channel float texture, and write as below:
Texture3D gTexture;
float id = gTexture.SampleLevel(gTextureSampler, float3(texC,i/dimension), 0).x;

It seems to be working. So It is not blocking us. Would be nice to have a fix. thanks.

**Comment by tfoleyNV** [comment]
Thanks for the update. I will look into the other issue. Please let me know if any further blocking issues come up.

**Comment by tfoleyNV** [comment]
One note: some of these issue reports are a bit hard to read because GitHub is swallowing the `<>` part of your code examples (I guess as part of it sanitizing HTML in messages).

It would help a bit if the code blocks were formatted using Markdown syntax. E.g., this raw text in the GitHub issue editor:

    ```hlsl
    Texture3D<int> gTexture;
    int id = gTexture.SampleLevel(gTextureSampler, float3(texC,i/dimension), 0).x;
    ```

will produce output like:

> ```hlsl
> Texture3D<int> gTexture;
> int id = gTexture.SampleLevel(gTextureSampler, float3(texC,i/dimension), 0).x;
> ```

I can of course still understand the issue as-is, so please don't worry about this formatting stuff if it would impede you from filing more issues. I'd rather know about what is broken than insist on beautiful looking issue reports.

**Comment by KaChen3000** [comment]
Yeah i just noticed that. thanks Tim.

**Comment by kenchen3000** [comment]
Hi,
We are not in the need of reading one channel texture because otherwise the memory usage would be too large. I know it is closing to Siggraph, Is it possible to have a quick look?

**Comment by tfoleyNV** [comment]
I'm not sure I follow your message. Do you mean you are *now* in need of support for reading from the one-channel texture?

I believe that it should be okay to declare a `Texture3D<int4>` in your shader code even when you are binding a one-channel texture image, because it just maps down to an `itexture3D` in GLSL anyway, which doesn't record the number of components.

Please let me know if you can work around the issue by declaring a `Texture3D<int4>` instead of a `Texture3D<int>`, while still allocating a one-channel texture on the application side. If not, I can try to put together a fix, but as you note it will be complicated by the fact that I'll be travelling soon.

**Comment by kenchen3000** [comment]
Yes we are creating a feature that would need to read from one channel texture. I will try the approach you suggested, thanks.
