### ISSUE TITLE
Slang crashes on empty structs

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#795]
The following code currently triggers a crash:
```
interface ISomething
{
    associatedtype T;
    T getT();
    [mutating]
    void setT(T val);
}

struct S : ISomething
{
     struct T{};
     T getT() {T t; return t;}
     [mutating]
     void setT(T val) { };
};
```

The crashes is in `legalizeFunc` on `S::getT`, as the return type legalizes to `none`, but this is not handled in `legalizeSimpleType`. We should not call `legalizeSimpleType` on return type, but should use `legalizeType` instead.

**Comment by tfoleyNV** [comment]
It seems like we should convert a `none` as a return type into a `void` return type.

I was thinking about a related issue recently: that we might want to go ahead and make `void` be a real type as far as the IR is concerned, with a single “`void` literal” value. Then we could have a single `return` instruction that always returns something (even if it is just a `void` value), and then have a late IR transformation pass that finds instructions of `void` type that have uses, and replaces those uses with the void literal. That would then enable removing any (now dead) `void`-type locals, etc.

The legalization pass could then treat `void` and `none` equivalently, and strip them out of struct types and parameter lists.

Anyway, I think the actual issue here can be fixed very simply, but I wanted to note how it could be related to better handling of `void` overall.

**Comment by tfoleyNV** [comment]
There also the issue that we need to start handling resources types in return positions.

A starting point out be to change the return type of a function to only include the “ordinary” data, and then turn any resources in the return type into `out` parameters.

Similarly, it would be good to turn any types as part of `in out` parameters into separate `in` and `out` parameters.

This would let us then have a later pass that can specialize away `out` resource parameters. We already have some logic in place to specialize away `in` resource parameters when required for a target.

**Comment by tfoleyNV** [comment]
Did #796 fix this?

**Comment by csyonghe** [comment]
Just submitted #805. This should completely fix all issues I have encountered with empty structs, including using empty structs in global ParameterBlock, and as a field of vertex input / output.
