### ISSUE TITLE
Include attributes in reflection data

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#809]
I find it useful if we can include user-defined attributes in `TypeReflection`. For example,
```
[BlendMode("Replace")]
struct MaterialParams
{
    [DefaultValue("(1.0, 1.0, 1.0, 1.0)"]
    float4 baseColor;
    [DefaultValue("1.0")]
    float opacity;
};
```

This allows the engine to properly setup buffers and pipeline states from the shader types in-use.

**Comment by tfoleyNV** [comment]
Your proposal for the user-mode code is *very* close to what C# has, so that I'm left wondering why you have `[Attribute(...)]` instead of `[AttributeUsage(...)]` as it in in C#. Was your intention to mirror the C# precedent exactly?

As for the duplication, it seems like the we'd eventually want to migrate everything to one option or the other. The C#-style option is nicer to look at, so we could try to migrate the existing declaration over to that. The main details I can see are:

* We need some kind of `__attributeClass(...)` modifier that we can attach to the declarations for compiler-internal attributes to specify the name of the C++ class that should be instantiated for them (this is what the `: Whatever` part of the current `attribute_syntax` is used to specify.

* There is a kind of circularity in the C# case where `AttributeUsageAttribute` has an `[AttributeUsage(...)]` attribute on it, and I'm not really clear on how the front-end is supposed to cope with that without a little bit of special-case hackery.

On that note, my mental model for this stuff (which differs from the C# mental model) is that an attribute is really a value at an earlier phase/stage of compilation, so that attribute classes should really be phased/staged before other code (it is meta-level code not runtime-level code). In that regard if `[Foo] struct A { ... }` is at phase 0, then `[AttributeUsage(...)] struct FooAttribute` is at phase -1, and then the `struct AttributeUsageAttribute` is at phase -2, and any `[AttributeUsage]` on it would have to refer to a declaration at phase -3, so that the "circularity" is really just that the stdlib declarations need to be parsed in the context of an instantiation of the stdlib at an earlier meta level... This is all do-able but not something our compiler is built to handle any time soon, so "special-case hackery" may be where we are stuck.

Still, I might want to insist that attribute types should be marked to show their meta-level-ness, so that I might argue they should use `$struct`, just because I've been assuming that in the long run `$` would be the general-purpose sigil for escaping to the meta-level (that is the same reason that `$for` is our current syntax for a compile-time `for` loop). I'm happy to hear arguments for why that is a bad idea, of course.

As a final point, and along the same lines, I really like the way the current `__attributeTarget(...)` works insofar as it refers directly to the name of a class of AST nodes, and thus clearly shows how attributes are attached to the meta-level of the compiler. The C#-ish approach with an `enum` of flags strikes me as less flexible, and more annoying to extend when we might have new kinds of declarations, etc. down the road (whereas `__attributeTarget` automatically works with any new AST node types).

My take on this is perhaps overly biased by wanting to leave the door open to extend Slang to support more flexible metaprogramming and DSL creation along the lines of Lua/Terra, so I can understand if some of this isn't especially appealing. All we really need to agree on for now is a general direction so that future evolution to how we handle attributes don't cause a backwards-compatibility break for user-space code you write.
