### ISSUE TITLE
Error when compiling compute shaders

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#82]
Slang strips all declarations from the GLSL before sending it to glslang.

I send
```C++
#extension GL_ARB_compute_shader : require

layout(set = 0, binding = 1, rgba32) uniform image2D gOutput;
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

void main()
{
    imageStore(gOutput, ivec2(0,0), float4(1,1,1,1));
}
```

slang sends
```C++
#version 420
#extension GL_ARB_compute_shader : require

#line 33 0
void main_(){
{
    imageStore(gOutput, ivec2(0,0), float4(1,1,1,1));}
}
void main(){
main_();
}
```

**Comment by tfoleyNV** [comment]
Closing. This turned out to be "user error" in a very technical sense:

- The file in question had a `.hlsl` extension, and Slang was being told it was HLSL code
- Because the file had no `__import`s, the compielr went in "full rewriter" mode and turne the body of `main()` into an `UnparsedStmt` (no semantic info)
- Because the target was GLSL (not the same as the source language) Slang tried to cross-compile, and when cross-compiling it only emits declarations that it seems get used
- Because the function body was unparsed, it appeared that *nothing* was used, so nothing got output (other than `main()`)

While this is technically a user error, there are two issues that should probably be fixed:
1. We should do a better job of error'ing out on obviously invalid code. The file obviously wasn't valid HLSL, but we parsed it anyway because our parser is so lenient
2. We shouldn't allow "rewriter" mode to be used together with whole-file cross-compilation (in fact, we should allow cross-compilation for source languages others than Slang...)

Those are separate issues, though, so I'm closing this one.
