### ISSUE TITLE
Intended usage pattern for cross compilation

### ISSUE THREAD

**Issue by tangmi** [shader-slang/slang#850]
Hi, I'm wondering if I can get some pointers on how I'm intended to use this library. I'd like to take some `*.slang` source file and compile it for both HLSL and SPIR-V targets.

To compile a single source file for a single target, it seems I should do:

1. Create a SlangSession `session`
2. Create a CompileRequest `request`
3. Add a TranslationUnit `translation_unit_index` to `request`
4. Add a source file/blob to `translation_unit_index`
5. Add an EntryPoint `entry_index` to `request` for a shader stage/entry point function name
6. Add a CodeGenTarget `code_gen_target_index` (e.g. for HLSL `sm_5_0`) to `request`
7. Compile the `request` and report any diagnostics or failures
8. Get the blob for `entry_index` from `request` and return

To get reflection data, I add a "Compile" and "GetReflection" between 4. and 5. and inspect.

Some questions I have to extend this usage:
1. If I want to add more targets, should I add additional CodeGenTargets to `request` or should I made additional requests?
2. Is it possible to specify a type layout ruleset such that all code gen targets layout in the same way (e.g. `std140`?)? Is the intended use case to always use the reflection data to figure out the layout of the structs (which can vary by target language)?
3. Is it valid to get the shader reflection data when there are multiple code gen targets attached to a single compile request? It seems when there are multiple code gen targets, duplicate entries appear in the shader reflection data.

Thanks for taking the time to read this!

**Comment by tfoleyNV** [comment]
Our current C API has grown as needed to satisfy the needs of current Slang users, so it doesn't always have full orthogonality for some operations. It might be that we can add additional functions to the API that better meet your needs.

On your concrete questions:

> 1. If I want to add more targets, should I add additional CodeGenTargets to `request` or should I made additional requests?

The API supports compiling for multiple targets in a single invocation of `spCompile`, but many of the functions for querying outputs from the compile currently only support target zero.

You can get per-target per-entry-point compiled kernel code with:

```c++
SlangResult spGetEntryPointCodeBlob(
        SlangCompileRequest*    request,
        int                     entryPointIndex,
        int                     targetIndex,
        ISlangBlob**            outBlob);
```

Unfortunately, the `spGetReflection` function only supports getting reflection data for target zero today.

We can add new functions to address these gaps if it would be useful. The underlying implementation supports multiple targets in a single compile request, so the work to expose it would not be major.

For now, though, you should probably use distinct compile requests per target.

You mention compiling to HLSL and SPIR-V, and I will note that while we support HLSL as a compilation target, you may find it easier to have the Slang library output DX bytecode or DXIL directly, since that will ensure that the compiler options passed to the downstream compiler are consistent with what Slang expects (e.g., matrix layout flags).

> Is it possible to specify a type layout ruleset such that all code gen targets layout in the same way (e.g. `std140`?)?

This is not possible today, but it is something that we would like to support in the long run. We would probably do this by implementing the D3D layout rules on GLSL-based targets.

For now, if you would like to ensure consistent type layout between D3D and Vulkan you would need to stick to type declarations that will lay out consistently between the two. That isn't ideal, but many shader developers already manually pack/pad their types so it hasn't become a priority to address just yet.

> Is the intended use case to always use the reflection data to figure out the layout of the structs (which can vary by target language)?

We do not require users to use the reflection data if they don't want to, but in cases where users don't use that information they would take on the burden of manually matching the API-specific layout rules.

Type layout within constant buffers isn't actually the most complicated part of this; assignment of `register`s and `binding`s is something where not only do D3D and Vulkan differ greatly in their rules, but it is in general impossible to have the "same" layout for both APIs.

That said, there are idiomatic ways that an application could handle the issue of packing descriptor tables/sets that should be able to paper over the API differences nicely, and Slang's deterministic layout rules should be compatible with such approaches.

> Is it valid to get the shader reflection data when there are multiple code gen targets attached to a single compile request? It seems when there are multiple code gen targets, duplicate entries appear in the shader reflection data.

As I mentioned above, the current `spGetReflection` function only gets reflection information for the first target.

If you are seeing duplicate data in the reflection information, that sounds like a bug. Do you have an example shader you can share where the duplication happens?

Thanks for your interest in Slang. I hope that my responses are helpful. Please let me know if there are API changes that could speed up your work, or if there are any other questions we can help with. The current state of the API reflects what our users have needed so far, and not any kind of definitive statement about what we plan to support when the project reaches 1.0.

**Comment by tangmi** [comment]
Hi, thanks for your response!

This is a lot to think about, but I will create compile requests per target, for now.

I will look into compiling directly to DXBC or DXIL--I was outputting HLSL to be able to inspect it, but I am now aware of `spSetDumpIntermediates`.

I mention `std140` (which I've noticed in `type-layout.h`, there's a `LayoutRule::Std140`, among others) because I am targeting GLSL 300es (indirectly, by compiling from slang to SPIR-V, then using [SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross) to compile the SPIR-V to GLSL 300es). It seems like I have some research to do regarding uniform layout rules, but it's my understanding that GLSL 300es's only "deterministic" layout rule for uniforms is `std140` (I would be delighted to be proven wrong about this!). It would be awfully nice to have a single layout for all platforms, although admittedly I'm unfamiliar with best practices regarding abstracting cross- graphics API buffer layout.

I am currently using slang for DirectX 11 and OpenGL ES 3.0 (and maybe WebGL?), so it seems I have more research to do to see how slang and SPIRV-Cross map binding locations to the various APIs...

As for the duplicate entries in the reflection data, it seems I was calling `spAddEntryPoint` multiple times for the same entry point (this is probably an incorrect usage on my part). I've created a minimal repro below:

```c++
auto session = spCreateSession(nullptr); // leak
auto request = spCreateCompileRequest(session); // leak

auto translation_unit_index = spAddTranslationUnit(request, SLANG_SOURCE_LANGUAGE_SLANG, nullptr);
spAddTranslationUnitSourceString(request, translation_unit_index, "simple3D.slang", R"(
cbuffer data
{
	float4x4 mvp;
};

struct VS_IN
{
	float3 position : POSITION;
	float4 color : COLOR;
};

struct PS_IN
{
	float4 position : SV_POSITION;
	float4 color : COLOR;
};

[shader("vertex")]
PS_IN vs_main(VS_IN input)
{
	PS_IN output;

	output.position = mul(float4(input.position, 1), mvp);
	output.color = input.color;

	return output;
}

[shader("pixel")]
float4 ps_main(PS_IN input) : SV_Target
{
	return input.color;
}
)");

auto target = spAddCodeGenTarget(request, SLANG_HLSL);
spSetTargetProfile(request, target, spFindProfile(session, "sm_5_0"));

// NOTE: these calls do not affect the reflection data--the data contains both `vs_main` and `ps_main` regardless of these calls, as expected
spAddEntryPoint(request, translation_unit_index, "vs_main", SLANG_STAGE_VERTEX);
spAddEntryPoint(request, translation_unit_index, "ps_main", SLANG_STAGE_PIXEL);

// NOTE: If one adds an entry point more than once, an duplicate entry appears in the reflection data, I'm unsure if this is expected
spAddEntryPoint(request, translation_unit_index, "vs_main", SLANG_STAGE_VERTEX);

auto compile_result = spCompile(request);
assert(SLANG_SUCCEEDED(compile_result));

// dump entry points
auto reflection = (slang::ShaderReflection *) spGetReflection(request);
std::cout << "Entry Points:" << std::endl;
for (auto i = 0; i < reflection->getEntryPointCount(); i++) {
    auto entryPoint = reflection->getEntryPointByIndex(i);
    std::cout << "  - " << entryPoint->getName() << " : " << entryPoint->getStage() << std::endl;
}
```

Again, thanks for your time!

**Comment by tfoleyNV** [comment]
> As for the duplicate entries in the reflection data, it seems I was calling `spAddEntryPoint` multiple times for the same entry point (this is probably an incorrect usage on my part).

I agree that the behavior might be surprising, but I think what the Slang API is doing is reasonable in this case. It is possible for a programmer to want the same entry point to be compiled multiple times in a single request (possibly plugging in different type arguments for generic parameters, so you have `vs<TypeA>` and `vs<TypeB>`). It might be good to at least have a warning for the case you ran into, though.

> I am currently using slang for DirectX 11 and OpenGL ES 3.0 (and maybe WebGL?), ...

I should note that while we run many of our automated tests on D3D11, and a small number on OpenGL, the only APIs that Slang tries to "officially" support are D3D12 and Vulkan.

Our layout behavior should be pretty reasonable for a D3D11 user, so long as you are okay with the fact that all stages (VS, PS, etc.) will use the exact same `register`s for all global shader parameters (the main consequence of this is that you are limited in the number of constant buffers, textures, samplers, etc. that you can use across all stages, rather than the amount you can use per-stage).

The Slang layout rules for GLSL output are appropriate to Vulkan, but probably wouldn't make sense for OpenGL by default. Whether you can get something sensible for your use case probably comes down to what SPIRV-Cross does.

We would like to support outputting GLSL that is appropriate for OpenGL, GL ES, or WebGL but the required work is unlikely to get prioritized over things for D3D12 and Vulkan users.

We always appreciate having more users interested in Slang, but depending on your development goals I would say that you might also want to look into options that use the "dxc" compiler from Microsoft, which can also generate SPIR-V (and there is even a [project](https://github.com/Microsoft/ShaderConductor) that uses that for cross compilation to other platforms using SPIRV-Cross).

> It seems like I have some research to do regarding uniform layout rules, but it's my understanding that GLSL 300es's only "deterministic" layout rule for uniforms is `std140` (I would be delighted to be proven wrong about this!).

I suspect you are right about what GL ES supports.
When I say that Slang might eventually emulate the D3D behavior on top of GLSL, I mean we would emit GLSL code that manually pads things to get the desired layout - not that we'd use any top-secret layout mode you hadn't heard of. :)

Slang will currently always output GLSL `uniform` blocks using `layout(std140)`, and will always output `buffer` blocks using `layout(std430)`, so the layout will always be deterministic even today.

Both the `std140` layout rules and the standard HLSL `cbuffer` layout algorithm are oriented around 16-byte granularities (e.g., all `struct`s and all arrays start on 16-byte-aligned offsets). The two main differences are:

* `std140` lays out vectors by giving them alignments (e.g., a `vec2` gets 8-byte alignement, while a `vec3` or `vec4` gets 16-byte alignment), while HLSL `cbuffer` rules just say that a single vector may not "straddle" a 16-byte boundary.

* `std140` rounds up the size of a `struct` or array type to its alignment, while HLSL `cbuffer` rules don't. That means a scalar value after a `struct` or array can be laid out in the "tail" space of the struct/array under the HLSL rules, while under `std140` it would start at the next 16-byte-aligned offset after the struct/array.

To make things lay out the same between the two, you can follow a few basic rules:

* Make sure that any 2-component vectors would fall on 8-byte aligned boundaries naturally, and any 3-component vectors on 16-byte aligned boundaries. In general, declarations like `float3 v; float s;` are okay, while declarations like `float s; float3 v;` would cause a mismatch.
* Make sure any `struct` type is manually padded out to be a multiple of 16 bytes in size
* Make sure any array uses an element type that is a multiple of 16 bytes in size

> ... so it seems I have more research to do to see how slang and SPIRV-Cross map binding locations to the various APIs...

I don't have any working experience with SPIRV-Cross, so I can't say what their rules are.

As for Slang, we try to document our [layout rules](https://github.com/shader-slang/slang/blob/master/docs/layout.md), which are deterministic but API-dependent. In simple cases the behavior is more or less what you'd expect: we start at the top of your shader and work our way down assigning each shader parameter the next available `register` or `binding` that is appropriate to its type and the target API (e.g., a `Texure2D` will get a `t` register when compiling to HLSL/DXBC/DXIL, or a `binding` when compiling to SPIR-V for Vulkan).

There are all kinds of details that arise in practice, mostly stemming from differences in how the target APIs handle shader parameter binding, but Slang's behavior tries to stick as much as possible to thinking of a single top-down sweep through the program to allocate locations/bindings/whatever to global parameters.

Anyway, sorry to write up such a long response. If you decide to keep using Slang for your project I have no doubt that you'll find bugs or missing features along the way, so feel free to post new issues for things you run into. If I've answered the current questions to your satisfaction, feel free to close this issue.

**Comment by tangmi** [comment]
Hi! I somehow missed thanking you for your answer--this was incredibly helpful! Thank you!
