### ISSUE TITLE
Reflection for RaytracingAccelerationStructureType should give unique opaque resource type for Vulkan

### ISSUE THREAD

**Issue by philcn** [shader-slang/slang#894]
I'm working on a VKRay implementation in Falcor and I'm creating descriptor set layout based on reflection data of slang shaders.

When I declare an HLSL RaytracingAccelerationStructure resource in shader, spReflectionType_GetResourceShape() returns SLANG_BYTE_ADDRESS_BUFFER, and Falcor will create a SRV descriptor slot in the descriptor set layout based on this resource type.

However, Vulkan has a dedicated VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV descriptor type, unlike in D3D12 acceleration structures use SRV descriptors. With the current IR defining the acceleration structure as ByteAddressBuffer (https://github.com/shader-slang/slang/blob/master/source/slang/ir-inst-defs.h#L116), there's no way I can add special handling in Vulkan descriptor set backend.

**Comment by tfoleyNV** [comment]
Yes, we should add an additional case for this and return it instead of `SLANG_BYTE_ADDRESS_BUFFER`.

For anybody who wants to look into implementing this (it should be a small feature), you'd need to add a case for the new buffer type to the `SlangResourceShape` `enum`, and then in `reflection.cpp` change `spReflectionType_GetResourceShape` to have an additional `CASE` before the one for `UntypedBufferResource` that handles acceleration structure types (handled as `RaytracingAccelerationStructureType` in the Slang C++ code).

The one gotcha is that this could be considered a backwards-incompatible change, since any existing applications that used reflection might have been used to the existing return value.
