### ISSUE TITLE
Generic parameter and groupshared

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#899]
I realized that we currently do not have a story of how to define a groupshared variable (that must be defined globally) whose type is dependent on a generic entry-point parameter.

For example, without the global `type_param` feature, the following code would not be possible:
```
type_param arraySize : int;
groupshared float4 sharedArray[arraySize];

[numthreads(128, 1, 1)]
void cs_Main(uint3 threadId: SV_DispatchThreadID)
{
    ...
}
```

**Comment by tfoleyNV** [comment]
First: you talk about global generic type parameters, but your example wants a global generic *value* parmeter, which we haven't even implemented. :)

The practical matter is that for now I expect we can get around this kind of problem for `groupshared` by making sure that we allow and implement `static groupshared` variables correctly (both at function scope and nested in types). That should allow users to work with a `groupshared` variable whose size (or element type, I guess) depends on a generic parameter without needing global generic parameters.

The secondary matter is that based on user experience so far, there might be a lot of argument in favor of something that behaves like global generic value parameters, even if we phase out global generic *type* parameters in favor of just supporting interface type parameters.

Whatever the syntax would be, it would be nice to have support for declaring something that looks like an ordinary `int` shader parameter, but that needs to have a value bound at specialization time. These should be allowed at global scope, entry-point scope, and as `struct` fields, to make the system nice and complete.

The thing is, that starts to drag us back toward having a notion of rates, since these parameters would expose a "specialization-time" rate/world, and functions that include specialization-time parameters would then be multi-rate functions.

I think there is a useful feature we still want here, but I desperately need to get basic interface-type parameters working first.

**Comment by csyonghe** [comment]
I brought up this issue just to keep an example of why we might need some level of "global specialization" support. 
Even a simple support of `int` specialization parameter will have a lot of value. There are a lot of places where a user may want to define a maximum array size, which is determined by the application at run time, that would benefit from this feature. Right now our answer is still "use `#define`s", which seemed less ideal.

**Comment by tfoleyNV** [comment]
I think we are on the same page that there is a useful feature here we need to provide. The real question is about how what we want the syntax and semantics to be, and that's where all the hard problems come from, as we've already experienced with global generic type parameters (and as I'm in the thick of with interface-type parameters).

> Right now our answer is still "use #defines", which seemed less ideal.

I guess that is the easier option for a user today, and we don't really have any examples that dissuade them from that way of doing things.

Looking at an example of the kind of thing somebody might want to write with global generic parameters:

```hlsl
// pseudo-syntax:
generic_type_param T : IWhatever;
generic_value_param N : int;

StructuredBuffer<T> stuff;
ConstantBuffer<float4[N]> things;
...
void main() { ... }
```

Today if you just have a compute kernel, you can write the same thing with an explicit generic entry poin and entry-point `uniform` parameters:

```hlsl
void main<
    T : IWhatever,
    N : int>(
    uniform StructuredBuffer<T> stuff,
    uniform ConstantBuffer<float4[N]> things,
    ...)
{ ... }
```

AFAICT that gets most of the same benefits as something `#define`-based, and inherits more or less the same weaknesses:

* You can't know the layout/offsets/registers for things for sure until you've plugged in the generic arguments (ditto if you use macros)
* Your exposure of shader parameters to application code needs to deal with two categories of parameters (generic vs. value, or macro vs. value)

The big win compared to `#define` is that it is explicit (and reflectable) what the shader depends on, and we can even enumerate the value parameters without having to plug in concrete values for the meta-parameters.

So generic entry points already seem like a big step in the right direction. The main weaknesses come up when you want to share the value of generic parameters across multiple subroutines/types/whatever. In my mind, that is exactly where we want to start allowing for entry points to be nested in (generic) `struct` types:

```hlsl
struct MyShader<
    T : IWhatever,
    N : int>
{
    struct MyStuff { T whatever; }
    StructuredBuffer<MyStuff> stuff;

    struct MyThings { float4 a[N]; uint b; }
    ConstantBuffer<MyThings> things;

    void someUtilityFunc() { ... stuff ... things ... N ... T ... }

    [shader("vertex")]
    void vertexMain() { ... }

    [shader("fragment")]
    void fragmentMain() { ... }
}
```

The benefits over just having a generic entry point are clear: we can freely use utility types/functions that depend on the generic parameters, and that also means we can have multiple entry points that share the same scoping for generic parameters.

I think we can and should implement support for entry points in `struct` types, including generic types, simply because this seems like a much cleaner way to write things. Doing so at least gives us a general-purpose answer for how people *can* write shaders that don't need `#define` for things like integer constants.

When I walk users through this kind of stuff, the main complaints are usually something like:

1. "I don't like having to think about setting that `T` parameter, and I just want to think in terms of binding an `IWhatever` to my shader."
2. "I don't want to have to wrap up my shader as a `struct` - I like using the global scope"
3. "I don't like how if I have a bunch of different integer/bool parameters for specialization you make me have this really long generic parameter list... I just want a 'specializable' `int`. How hard is that?"

Item (1) is what I'm trying to fix by just supporting interface-type shader parameters, but over the course of implementing it I have found that they have many/most of the same challenges that global generic type parameters create, especially around things like layout.

Item (2) is all well and good, and is the main reason we've had global generic parameters so far, but my take is that we want to make it easy for people to encapsulate shaders as `struct` types, and encourage them to do so. That doesn't mean we shouldn't support programmers who want to use the global scope, but I don't think we should make features specifically for the global scope: any shader parameter that the user can declare globally, we should let them declare as an entry-point parameter or a `struct` field.

So item (3) is really where this leads: is there a way to let them declare a specialization parameter without using the concepts/syntax of generics? To me the answer is "obviously yes" because RTSL and Spark already had this with the `constant`/`@Constant` rate.

We could easily introduce syntax for this concept and it could follow much of the same specialization approach as I'm using for interface types. Making such a parameter *feel* like "just another `int` shader parameter" while also making it clear the ways in which it is *not* seems important when it comes to syntax. I might be inclined to argue for something that is syntactically just an ordinary variable declaration:

```hlsl
@Constant int N; // use Spark/Spire-like rate syntax?
constexpr int N; // borrow C++-ish terminology?
```

We would then allow such variables at global scope, in entry-point parameter lists, and eventually as `struct` fields.

The tricky bit is dealing with the semantic fallout. Should we do anything special with types that depend on these parameters during layout, or always use the simple in-order enumeration of parameters we have today (and what should we report for parameters that come after something generic?)? What kinds of dependency between parameters should/shouldn't be allowed (this becomes really thorny if we allow these to be used as `struct` fields)?

**Comment by csyonghe** [comment]
Closing the issue for now as we won't get to it anytime soon.
