### ISSUE TITLE
Reflecting an array of structured buffers reports the buffer size as 0

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#91]
```
struct LightCB
{
    float3 vec3Val; // We're using 2 values. [0]: worldDir [1]: intensity
};

RWStructuredBuffer<LightCB> gRWBuffer[5]; // Only UAV counter used
```

I get the correct array size, but the size is 0. If I'm not using array the size is reported correctly.
Might be user error, in both cases I'm calling `(uint32_t)pSlangElementType->getSize()`

**Comment by tfoleyNV** [comment]
As discussed in person, I'm pretty sure this was user error (although the API might make this more confusing than it should be).

If you have a `VariableLayoutReflection` for `gRWBuffer`, it effectively has a type of `RWStructuredBuffer<LightCB>[5]`.
If you ask that type for its "element type" the result is `RWStructuredBuffer<LightCB>` and if you ask that type for its size in bytes, the answer is `0` because a `RWStructuredBuffer` consumes no storage in "ordinary" memory (e.g., when used as a member in a CB).

In this case what a user *probably* wants is `someShaderParameter->getType()->unwrapArray()->getElementType()`, so that they can drill down to the resource type and get its element type.

I'm going to close this, and we can re-open it if I turn out to be wrong.
