### ISSUE TITLE
Using asfloat on an Enum Type results in an Ambigious Call

### ISSUE THREAD

**Issue by Shindorinn** [shader-slang/slang#924]
Doing something like :
```hlsl
enum class Example
{
   A = 0,
   B = 1,
   C = 2
}

float4 bar = float4(0);
bar.w = asfloat(Example::A);
```
Results in 
```
error 39999 : ambigious call to overloaded operation with arguments of type (Example)
hlsl.meta.slang(381) : note 39999: candidate asfloat(uint)
hlsl.meta.slang(379) : note 39999: candidate asfloat(int)
```

While doing 

```hlsl
uint enumFlag = Example::B;
bar.w = asfloat(enumFlag);
```
is completely fine.

**Comment by tfoleyNV** [comment]
Upon looking into this, I found that there are two related problems here:

1. A Slang `enum` always behaves as if declared with `enum class`, and a scoped `enum` like that should *not* be implicitly convertible to `int`/`uint`/etc. So in this case an explicit conversion is needed.

2. Slang has accidentally been allowing conversions like that to succeed without errors/warnings.

The right thing for Slang is probably to fix issue (2), so that your second example would need to chagne to:

```hlsl
uint enumFlag = uint(Example::B);
bar.w = asfloat(enumFlag);
```

Thus an explicit conversion would be required in either case.

As for the direct call to `asfloat(Example::A)` we could either make it so that Slang gives you a "no applicable overload" error, because `Example` can't convert to either `int` or `uint`, or it can give you the current "ambiguous call" error and list the two overloads you might have meant. I honestly don't know which is preferable.

**Comment by natduca** [comment]
This might be an issue. If it still exists in current builds feel free to reopen or refile.
