### ISSUE TITLE
Method to describe a backing format for a resource

### ISSUE THREAD

**Issue by jsmall-nvidia** [shader-slang/slang#932]
The motivation for this feature originates around vulkan and the use of Texture2d<half3>. 

That when output as glsl slang attempts to add markup that says what the layout of the underlying resource is. But in this particular case there is a problem because there is no half3 based backing type. 

https://www.khronos.org/opengl/wiki/Layout_Qualifier_(GLSL)#Image_formats

For DirectX 
https://docs.microsoft.com/en-us/windows/desktop/direct3d12/typed-unordered-access-view-loads

If we look at SPIR-V spec (https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.pdf) section 3.11 on Image Formats it does not list rgbf32. That currently the layout is inferred in slang from the type. As 3 element types are not available slang just goes with a 4 element type - this may not be appropriate. 

In practice it is not uncommon to use say Texture2d<float3> and have it backed by a type such as 
vulkan format: `R11fG11fB10f`
GLSL format:  `r11f_g11f_b10f`
DX: DXGI_FORMAT_R11G11B10_FLOAT

That it was thought that perhaps this might not be an issue in practice, because it seemed that the actual layout had to be specified on binding and that would be enough. But in the vk case at least the physical device features as returned by VkPhysicalDeviceFeatures has two fields 

    VkBool32    shaderStorageImageReadWithoutFormat;
    VkBool32    shaderStorageImageWriteWithoutFormat;

And with minimal testing a card was found that had shaderStorageImageReadWithoutFormat as false. Meaning in general we do need slang to output the appropriate format in shader code. 

The initial idea is that we add a new attribute that can describe the format we want on a resource. For example 

```
[[format("R11G11B10_FLOAT")]]
Texture2d<float3> gTexture;
```
That we would want to define the standard list of these formats, because as touched on earlier different APIs use different names. That seeing as hlsl is the basis of slang, it should probably takes it's cues from that world. Also if they are well understood formats, we can check that the associated type is appropriate. 

We could just pass formats through (say if not known) - but this would stop it being translatable for a target. So another feature we may want is for the format to be specified by target. That if specified by target, we could pass through and allow different targets to have different formats. This could perhaps look like

```
[[format("glsl", "r11f_g11f_b10f"]]
[[format("hlsl", "R11G11B10_FLOAT"]]
Texture2D<float3> gTexture;
```
or perhaps better (where the name style is implied by the API)

```
[[vk::format("r11f_g11f_b10f"]]
[[dx::format( "R11G11B10_FLOAT"]]
Texture2D<float3> gTexture;
```

And the spec without the target, would be used for all not specifically specified targets (if defined). Otherwise it is implied (if possible).

**Comment by tfoleyNV** [comment]
My preference would be to define a fixed set of format names that are nominally API-independent. That is, even if we base the names on some existing API or language precedent, we should use the same names across all targets.

I'm not a fan of having target-dependent attributes. We have to live with them for things like parameter binding/layout since that is target-specific, but:

1. It seems like the incremental benefit of supporting target-dependent formats is small. How often does one want the same parameter to use a different format per API? How often would that not just be handled via `#ifdef` anyway?

2. If we are going to extend the support for target-dependent attributes, I'd like to pull together a more complete spec for a feature where *any* attribute can be filtered to only apply on certain targets. Adding an ad-hoc extra argument to certain attributes to specify the target to which they pertain seems unpleasant.

3. I'm really strongly against using, e.g., `vk::` vs `dx::` as a target marker, because the `::` implies namespacing so that `vk::format` and `dx::format` would seemingly be distinct attributes (living in distinct namespaces), and might only coincidentally support matching arguments. If we really want things to be parametric, then we should express it as such.

Anyway, I'm supportive of the feature, but I'd advocate for starting with a basic `[format("...")]` for now and not include anything target-specific. For simplicity I might advocate for starting with the GLSL format strings just because it is what users need in the immediate case, but we could consider defining our own names that match Slang naming conventions down the road (and leave in the old strings as aliases).

One forward-looking idea would be to define an `enum` in Slang that covers the formats, and have the `[format(...)]` attribute take that in a strongly-typed fashion:

```
[format(Format.R11G11B10_Float)]
Texture2D<float3> gTexture;
```

That has the benefit of not requiring string-based checking in the core of the compiler, and would make it relatively easy to add new formats to the stdlib over time. The one catch there would probably be making sure that we have both a Slang-stdlib `enum` and a host-code `enum` that agree on the numeric values of those formats so that we can `switch` over them in `emit.cpp`.

**Comment by Nimanf** [comment]
A case we need to consider is the support of `unknown `format in Vulkan, and not setting `layout(format) `in GLSL. This helps us skip adding explicit formats, if we know the hardware allows an unknown format to be set (For example Vulkan on Turing).

No matter what, this change will introduce a different regression if someone was already relying on the format set for a typed UAV (on Intel hardware for example). Even without this change, the existing type is still incorrect for some types. For example, we are setting rgba32f for float4, instead of `rgb10_a2` case.

So my suggestion is to use `[format()]` to always determine if `layout()` should be set or not, and avoid future problems.

Also, not sure what is the best approach for setting formats. Using Vulkan formats or GLSL formats. It should be something easy for developers to pick as equivalent to HLSL.

**Comment by tfoleyNV** [comment]
This issue seems related to #935. For D3D targets, the element type of an image must be qualified with `unorm` or `snorm` if the underlying format will be one of the `*_UNORM` or `*_SNORM` DXGI formats.

This creates a challenge for saying that lack of a `[format(...)]` attribute should default to the "unknown" case, because D3D is already setting a convention where the format is (at least partially) inferred from the element type of a typed UAV in HLSL.

If the user writes:

```hlsl
RWTexture2D<unorm float> myTexture;
```

then the assumption for a D3D target is that this image will be backed with an `R8_UNORM` texture. It seems reasonable for us to assume on VK targets that we should emit `layout(r8)` on the equivalent GLSL declaration.

Similarly, if the user specifies a `[format("R8_UNORM")]` but declares a texture without the `unorm` type qualifier:

```hlsl
[format("R8_UNORM")]
RWTexture2D<float> myTexture;
```

then it seems likely that the user wants us to output HLSL with a `unorm` qualifier on that declaration, to express the intention of the `[format(...)]` attribute.

We need a clear design here on two things:

* When format information is required (even partial format information), how should it be conveyed? Type qualifiers like `unorm`? Attributes like `[format(..)]`? A combination?

* When should the compiler assume that a lack of format information is intended? When should it infer format information from the element type of a texture?

One option to consider is whether texel formats should be treated as types directly (following the precedent of `unorm float4`), so that the user can declare, e.g., a `RWTexture2D<RGB10_A2>`.

I'm not sure what is best here, but I don't want to lock us into a design choice where we have two competing ways to specify the same information, each applicable to only one target API.

**Comment by Nimanf** [comment]
What about 3 formats like `R32_UINT`,  `R16_UINT`, and `R8_UINT`?
Don't they declare it as `RWTexture2D<uint> myTexture;` in HLSL?

what format currently we choose for it in vulkan/GLSL?

**Comment by natduca** [comment]
We think this might be fixed. Please file new issue if you know of new issues or this sstill exists in current builds.
