### ISSUE TITLE
Including an imported module file in a translation unit results duplicate definitions

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#945]
In my engine, most shader types are defined in `ShaderLib.slang`, and an entry-point is defined in `ForwardBase.slang`. The entry point takes several generic parameters, and the types that can be used as generic arguments are also defined in `ShaderLib.slang`.

In order to compile a specialized shader, the engine creates a compile request that includes a single translation unit, and add `ForwardBase.slang`, as well as the source files that define each generic type argument to the translation unit. Since I am using a type defined in `ShaderLib.slang` as type argument, the engine adds `ShaderLib.slang` to the translation as well.

However, since `ForwardBase.slang` also `import`s `ShaderLib.slang`, the symbols defined in the `ShaderLib.slang` will be parsed into the syntax tree of the translation unit. When the compiler is checking the `import` statement, it will still determine that the file `ShaderLib.slang` has not been imported yet, and so will proceed to parse the file and include it into the lookup context. As a result, further type lookups to symbols defined in `ShaderLib.slang` will become ambiguous.

This problem can be solved if `ShaderLib.slang` is added as a separate translation unit. However, the engine will not have the knowledge of what modules are imported by `ForwardBase.slang`, and therefore cannot do this. It is also necessary to ensure that all files are in the same translation unit, since that is the way to make sure all argument types can be found.

The easiest way to address this problem is to fix the compiler so we always keep track of what files are used to form the current translation unit, and do not recursively load a module if the module source is one of the files in the current translation unit.

**Comment by tfoleyNV** [comment]
The behavior you are seeing is consistent with my mental model for how things are supposed to work, but it definitely causing problems when trying to work around #943.

In my mind a translation unit is equivalent to a module: each translation unit in a compile request becomes an output module. Having the same file both be used as an `import`ed module (so that the file is a full module on its own), *and* as just another file in the translation unit (so that it’s code is just part of a larger user-defined module) is something I’d expect to cause problems. It’s the moral equivalent of both compiling `foo.c` directly *and* doing `#include “foo.c”` in another source file.

The right fix is for us to improve the API so that the name lookup for generic arguments stops being an issue. We could maybe kludge something by making side name lookup is using all the modules that ever got imported in the compile request.

I wouldn’t want to add any subtle rules that try to catch this case based on using the “same” file as both an import and a direct source file, just because that behavior sounds a bit too magical and special-case.

**Comment by csyonghe** [comment]
Fixing name lookup for #943 makes sense to me.  For now I can work around this by removing the `import` statement in the source files and add `ShaderLib.slang` when creating a linkage. I may need to look into this  issue later.
