### ISSUE TITLE
Using generic type argument and associated types as VertexOutput / Fragment Input causes error

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang#946]
I don't think we have a such a test case, and currently Slang is crashing trying the figure out the layout during `getOrCreateLayout` for an associated type field.

For example,

```
interface IVertexFormat
{
     associatedtype ColorSet : IColorSet;
     float3 position;
     ColorSet colors;
}

type_param TVertex : IVertexFormat;
struct VertexOut
{
    float4 projPos : SV_POSITION;
    TVertex.ColorSet colors;
};

VertexOut vs(TVertex vertexIn) {}
float4 fs(VertexOut vert) {}  // crash checking layout for varying parameter `vert`
// because `vert.colors` is a `associated type` that is not handled by `processEntryPointVaryingParameter`.
```

This is a blocking issue for me, so I am going to fix it today.

**Comment by tfoleyNV** [comment]
Yes, this looks important to fix, but isn’t something that has come up in existing user code.

Obviously the usual constraint with generic parameters applies where the layout information will be complete until specialization, so mixing generic-dependent and ordinary varying parameters could get tricky.

The other gotcha to think about is that a generic varying parameter like that should always have a user-defined semantic, and shouldn’t rely on nested field semantics (nor can it have any `SV_` semantics in its nested fields),

(We might eventually want to allow varying parameters without semantics since they are just busy-work, but in this kind of case it would be important since having a user-defined semantic on `colors` is what would guarantee to the compiler that it need not consider whether there is a hidden `SV_` semantic on one of the fields of the concrete type that gets plugged in.

**Comment by tfoleyNV** [comment]
Also: I think that allowing genericity in varying vertex inputs is a huge thing we never explored enough on the research side, so I wouldn’t be surprised if we learn some interesting things from investigating it now.

I eagerly look forward to your fix, and to seeing your code to use the feature.

**Comment by csyonghe** [comment]
I have created a test case to reproduce the issue, and I am working on the fix now.
Here is the test case:
```
//TEST(compute):COMPARE_RENDER_COMPUTE:

//TEST_INPUT: global_type AssembledVertex
//TEST_INPUT: ubuffer(data=[0], stride=4):dxbinding(1),glbinding(0),out
interface IColorSet
{
    float3 getColor();
}

struct NoColorSet : IColorSet
{
    float3 getColor() { return float3(0.0); }
};

struct SingleColorSet : IColorSet
{
    float3 color;
    float3 getColor() { return color; }
};

interface IVertexFormat
{
    associatedtype ColorSet : IColorSet;
    ColorSet getColorSet();
    float3 getPosition();
    float2 getUv();
}

type_param TVertex : IVertexFormat;

cbuffer Uniforms
{
	float4x4 modelViewProjection;
}
RWStructuredBuffer<float> outputBuffer;

struct AssembledVertex : IVertexFormat
{
    typedef SingleColorSet ColorSet;
	float3	position;
	SingleColorSet	colorSet;
    float2  uv;
    ColorSet getColorSet() { return colorSet; }
    float3 getPosition() { return position; }
    float2 getUv() { return uv; }
};

struct CoarseVertex
{
	TVertex.ColorSet	color;
    float2  uv;
};

struct Fragment
{
	float4 color;
};


// Vertex  Shader

struct VertexStageInput
{
	TVertex assembledVertex	: A;
};

struct VertexStageOutput
{
	CoarseVertex	coarseVertex	: CoarseVertex;
	float4			sv_position		: SV_Position;
};

VertexStageOutput vertexMain(VertexStageInput input)
{
	VertexStageOutput output;

	float3 position = input.assembledVertex.getPosition();
	output.sv_position = mul(modelViewProjection, float4(position, 1.0));
    output.coarseVertex.uv = input.assembledVertex.getUv();
    output.coarseVertex.color = input.assembledVertex.getColorSet();
	return output;
}

// Fragment Shader

struct FragmentStageInput
{
	CoarseVertex	coarseVertex	: CoarseVertex;
};

struct FragmentStageOutput
{
	Fragment fragment	: SV_Target;
};

FragmentStageOutput fragmentMain(FragmentStageInput input)
{
	FragmentStageOutput output;
	float3 color = input.coarseVertex.color.getColor();
    float2 uv = input.coarseVertex.uv;
	output.fragment.color = float4(color, 1.0);
    outputBuffer[0] = color.x;
	return output;
}
```
