### ISSUE TITLE
Find a solution for VS_OUT

### ISSUE THREAD

**Issue by nbenty** [shader-slang/slang#95]
This is here just so I won't forget about it.
In order for a define-based solution to work for GLSL, I need to know when I'm compiling a Slang shader (so I can define the struct) vs when I'm compiling GLSL (so that I can remove the struct).
We may also need a SHADER_STAGE macro to know how to use `in` and `out`

**Comment by tfoleyNV** [comment]
We've discussed this over slack, and it seems like Slang is going to have to help solve this issue. There are a few pieces to the puzzle here:

- `struct` types are already allowed as varying input/output by GLSL/glslang, for everything *except* vertex shader input and fragment output. If that alone is the ask, then nothing is actually needed from Slang.

- `struct` types as VS input seem to be required, to handle `VS_IN` (which is defined in the same place as `VS_OUT`, so that seems to be part of the request (can you confirm, Nir?)

- The other thing I think is hidden in this ask (and this was subtle enough I almost missed it) is the ability for a struct like `VS_OUT` to declare "system-value semantic" inputs/outputs, and to translate a GLSL shader that uses that type to use the appropriate `gl_*` built-in variables, just like we would do when that type is used as a parameter to the entry point.

That last issue forces Slang to scalarize a `struct` being used as varying input/output even when it might not seem to be required by GLSL/glslang. If we don't scalarize things, and switch an `SV_Position` output over to `gl_Position`, then we will be declaring something very different from what the user meant.

This is a big, messy feature, but it seems tied in to a bunch of places where Slang is already doing a bad job with GLSL style global-scope varying input/output, so it probably makes sense to try to bite this off.

Nir, can you confirm that your expectation is for Slang to auto-magically handle the system-value semantic fields inside `VS_OUT` when it is used for a global-scope `in` or `out` variable?

**Comment by tfoleyNV** [comment]
This basics of this should be implemented in #118.
I'm going to keep this open a bit longer to confirm that the changes actually work in the context of Falcor (instead of just for my Slang test case).

**Comment by tfoleyNV** [comment]
Okay, "customer" feedback tells me this is working well enough in simple cases, so I'll close it for now and we can open new issues when things break in more involved cases.
